### ISSUE TITLE
Cmake configuration error 

### ISSUE THREAD

**Issue by evilone79** [aws/aws-iot-device-sdk-cpp-v2#100]
Hey. Since release of 1.5.3 I'm getting the following error trying to cross-compile the SDK (it worked flawlessly before). 

`cmake -DCMAKE_TOOLCHAIN_FILE=/home/user/build/buildtest2/toolchain/cross-toolchain.cmake -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON -DS2N_NO_PQ_ASM=ON -DCMAKE_INSTALL_PREFIX=$(pwd)/install -DCMAKE_PREFIX_PATH=$(pwd)/install ..`

> -- The C compiler identification is GNU 6.3.1
> -- The CXX compiler identification is GNU 6.3.1
> -- Check for working C compiler: /home/user/build/buildtest2/toolchain/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
> -- Check for working C compiler: /home/user/build/buildtest2/toolchain/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /home/user/build/buildtest2/toolchain/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
> -- Check for working CXX compiler: /home/user/build/buildtest2/toolchain/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Performing Test AWS_HAVE_GCC_INLINE_ASM
> -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
> **CMake Error at aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-common/cmake/AwsFeatureTests.cmake:48 (string):
>   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
>   command.**
> Call Stack (most recent call first):
>   aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-common/CMakeLists.txt:28 (include)

Thanks!

**Comment by bretambrose** [comment]
The line in question is
```
string(REGEX MATCH "^(aarch64|arm)" ARM_CPU ${CMAKE_SYSTEM_PROCESSOR})
```

which is clearly 5 arguments, but cmake being cmake, if CMAKE_SYSTEM_PROCESSOR has no value, it will probably think it only has 4 arguments.  

That variable appears to be defined for a long time now, version-wise.  What is the version of your cmake install?

**Comment by evilone79** [comment]
Cmake ver. 3.16.2

Probably it had skipped this check in the past somehow, since absolutely no change has been made to the build process. The toolchain we use doesn't set this var, but if you say it's supposed to fix the issue, I'll set it up.

**Comment by bretambrose** [comment]
Seems like it ought to work then.  You should be able to temporarily modify that file directly in the submodule directory.  Can you output its value? ( message(STATUS ....))

Also, it may be worth running cmake with trace/debug flags on and scanning to see if CMAKE_SYSTEM_PROCESSOR is getting manipulated prior to that line executing.
