### ISSUE TITLE
IotJobsClient returns empty response on "$next" job ID

### ISSUE THREAD

**Issue by evilone79** [aws/aws-iot-device-sdk-cpp-v2#101]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Platform/OS/Device**
Linux 4.9.68 aarch64 GNU/Linux

Hi,
I'm trying to correlate the behavior described here: [(https://docs.aws.amazon.com/iot/latest/developerguide/jobs-devices.html#option-a:-get-the-next-job)] with the cpp-sdk. In short: when I'm starting the app and calling the IotJobsClient.PublishDescribeJobExecution() while there's a pending job - everything goes well, job gets received ,performed and updated. BUT THEN: Upon the next call to PublishDescribeJobExecution I expect it to stay in a waiting state until new job hasn't been published, but what actually happens is I receive a OnSubscribeToDescribeJobExecutionAcceptedResponse with an empty execution, which essentially boils down to POLLING for iot jobs. Should it work like this or am i totally missing something?

Thanks!

**Comment by justinboswell** [comment]
There will only be a job description in the response if there is actually a next job. That's what the first step in that list is about:

> When a device first comes online, it should subscribe to the device's notify-next topic.

In this API, that would be calling ```IotJobsClient.SubscribeToNextJobExecutionChangedEvents()```. When you get a response to this handler, then call ```PublishDescribeJobExecution()``` with the id from that response, and follow the rest of the list from there.

**Comment by evilone79** [comment]
Thanks! I was really wandering how to subscribe to "notify-next" with IotJobsClient. Now it's clear! :)
