### ISSUE TITLE
Cross Compilation failure

### ISSUE THREAD

**Issue by jvasanthan** [aws/aws-iot-device-sdk-cpp-v2#104]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution
  
**Describe the bug**
I am cross compiling latest version of aws-iot-device-sdk-cpp-v2 for ARM. The SDK compilation fails at compiling std::promise. The lastest gcc compiler supported in the tool chain is gcc version 6.2.1 and I understand the support for std::promise is implemented from ARM Gcc 7.x. 

Any workaround is appreciated. 

_/aws-iot-device-sdk-cpp-v2/aws-common-runtime/aws-crt-cpp/include/aws/crt/http/HttpConnectionManager.h:114:36: error: field ‘m_shutdownPromise’ has incomplete type ‘std::promise<void>’
                 std::promise<void> m_shutdownPromise;_

**Platform/OS/Device**
ARM GCC V6.2.1

Regards,
James

**Comment by jvasanthan** [comment]
I have gcc 5.4 in my ubuntu desktop version which compiles the sdk absolutely fine. The cross compiler toolchain has gcc5.9.4, gcc 6.2.1 which doesn't compile the sdk and throws error about std::promise usage.

I came across https://godbolt.org/ (compiler explorer) tool to check different gcc versions, the "ARM Gcc 7.x" terminology is from there. 

Most of the searches in different forums pointed me to try higher versions of gcc. I got the latest toolchain from the vendor which had gcc v7.1 and with that the sdk compiled fine.

**Comment by bretambrose** [comment]
Good to hear that you're able to make progress.  Pure speculation but it sounds more like an issue with the cross compile toolchain -- either it's not getting c++11 enabled or a problem with the C++ standard library that its using or how it's selecting it.

How are you getting the cross compile toolchain?

For curiosity's sake, can you paste the full command lines (can be found in the generated cmake files) for the non-working gcc invocation vs. the working gcc invocation?

**Comment by jvasanthan** [comment]
Hi Bret,
Your speculation is reasonable. I am getting the toolchain from chipset vendor.

Do you want me to upload the makefiles?

**Comment by bretambrose** [comment]
Not the makefiles.  When I get some extra time, I'll do a build and see exactly where a good compile command representative can be found.

**Comment by walt-2020** [comment]
Hi, can you show me the good compile command of cross compile,thanks.
