### ISSUE TITLE
Segfault when MqttClientConnectionConfigBuilder is destructed.

### ISSUE THREAD

**Issue by samvik** [aws/aws-iot-device-sdk-cpp-v2#107]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution
  
**Describe the bug**
The following code segfaults, when the clientConfigBuilder is destructed, on the following assert AWS_FATAL_PRECONDITION(allocator->mem_release != NULL).

Only happens with C++17, 11 and 14 seems to work.

#include <aws/crt/Api.h>
#include <aws/iot/MqttClient.h>
int main(int argc, char *argv[])
{
    Aws::Crt::ApiHandle apiHandle;
    {
        auto clientConfigBuilder = Aws::Iot::MqttClientConnectionConfigBuilder("cert.pem", "key.pem");
    }
    return 0;
}

**Platform/OS/Device**
Linux

**SDK version number**
v1.5.5

**To Reproduce (observed behavior)**
Compile (C++17) and run the program pasted above.

**Expected behavior**
The object should be destructed correctly.

**Logs/output**
N/A

**Additional context**
N/A

**Comment by JaanViru** [comment]
I have seen similar problems with ConfigBuilder. Both with clang and GCC on Linux and embedded Linux. 
For me, it was a statistical error, that was way more frequent with C++ 14, 17. Reverting back to C++11 somehow mitigated the problems.

**Comment by samvik** [comment]
For me it is 100% reproducible.

I tested C++11 and 14 and that seems to work (@JaanViru Thanks). I will update the issue with this information.

**Comment by rccarper** [comment]
Hello, sorry that you are running into this.  What compiler are you using, and would you be able to post a call stack for when you hit the assert?

**Comment by jaan-viru** [comment]
@rccarper - I'll look into it next week. If I remember correctly I was able to produce this error with C++ 17 with clang 9 & gcc 6.?. Also ubuntu 18.04 gcc ???.

**Comment by jmklix** [comment]
@jaan-viru where you able to solve your issues with ConfigBuilder?
