### ISSUE TITLE
getaddrinfo() returns only ipv6 when using AF_UNSPEC

### ISSUE THREAD

**Issue by jvasanthan** [aws/aws-iot-device-sdk-cpp-v2#109]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

getaddrinfo function in posix/host_resolver returns only IPv6 resolved addresses in my target platform(ARM uclibc).The same function returns both IPv4 and IPv6 addresses in my host environment(Ubuntu glibc).  

After I changed hints.ai_family to AF_INET, I do get IPv4 addresses. A quick google search revealed similar problems related to hosts files settings. I tried them but nothing helped. 
https://stackoverflow.com/questions/55627377/getaddrinfo-returns-only-ipv6-when-using-af-unspec

I would like to keep the AWS core libraries unmodified. is there any other solution to fix IPv4 issue.

**Comment by jmklix** [comment]
Can you provide a minimum code sample where while using the sdk that reproduces this?

**Comment by JonathanHenson** [comment]
Also, is ipv6 a valid route? The getaddrinfo usage is designed to return usable addresses. Usually if an address family isn’t being returned, it’s because it’s not a valid route.
