### ISSUE TITLE
Error : AWS_ERROR_MQTT_UNEXPECTED_HANGUP

### ISSUE THREAD

**Issue by jvasanthan** [aws/aws-iot-device-sdk-cpp-v2#110]
Confirm by changing [ ] to [x] below:
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

Platform:
Both in Ubuntu 16.04 and ARM

I am receiving the following messages continuously. The behavior is intermittent though. There is no issue in the way the certs, key etc., are handled, made sure there are no  2 instances running with same Client_ID and IOT policy is set right. 

Connection interrupted with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
Connection resumed
Connection interrupted with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
Connection resumed

**Comment by jvasanthan** [comment]
Sometimes it throws "Error 5136 occured" and continues with 

Connection interrupted with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
Connection resumed
Connection interrupted with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
Connection resumed

**Comment by graebm** [comment]
Is this causing you an issue, or you're just curious why it's happening occasionally? Is the connection resuming successfully in a reasonable amount of time?

What kind of internet connection do you have (wireless, ethernet, etc)? Wireless connections can be flaky. Is there any pattern to the connection duration (ex: interrupted every 24hrs)? 

Are you connecting over websockets? The server will end the connection after [24 hours](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot) and the client must reconnect, that's expected behavior.

**Comment by jvasanthan** [comment]
Hi,

Thank you for your reply

Yes it is creating problem and I am also curious to know why its happening. AWS_ERROR_MQTT_UNEXPECTED_HANGUP message comes up every 500ms-1sec and during that time shadow & job updates are not intermittent, most of the time not received (I tested only shadow & jobs update)

I have tested it with both wireless and ethernet. Ethernet connection seemed to work better but still missed some shadow updates. I have attached application output messages.


Till now I haven't seen any pattern, I ran the application without logger in both wifi  and ethernet then I switched on logger to send you more data, AWS_ERROR_MQTT_UNEXPECTED_HANGUP  messages didnt come. 

No I am not using websockets

[ethernet.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4520651/ethernet.txt)
[wifi.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4520652/wifi.txt)

**Comment by khm971** [comment]
For me, this is caused by a duplicate client_id in the mqtt connection.  Fort instance, if I have two devices running the same test code, I have to make sure that client_id in the mqtt connection constructor is not duplicated if I'm running the program twice.

**Comment by jvasanthan** [comment]
Yes I saw your earlier post in the forum and made sure there is no duplication.

**Comment by bretambrose** [comment]
Can you attach trace level logs showing the failures (https://github.com/awslabs/aws-crt-cpp/blob/master/include/aws/crt/Api.h#L47) ?

**Comment by ndvbd** [comment]
Same problem here. The python sdk works fine, but the cpp sdk with the same parameters throw: 

Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.

**Comment by patrickwerz** [comment]
Same Issue here. I am currently testing the aws iot core device defender and testing the connect/disconnect metric. So I connected and disconnected in a loop untill:
File "/Users/patrick/.pyenv/versions/3.7.5/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/Users/patrick/.pyenv/versions/3.7.5/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
awscrt.exceptions.AwsCrtError: AwsCrtError(name='AWS_ERROR_MQTT_UNEXPECTED_HANGUP', message='The connection was closed unexpectedly.', code=5134)

**Comment by jmklix** [comment]
Are you using the ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

Also take a look at these issues to see if they fix your problem:
- #137 
- #144 

If you are still having problems please open a new ticket and include logs to help us diagnose the issue. As always make sure to sanitize your personal info from the logs.

**Comment by wes-novack** [comment]
Posting here in case this helps any future searchers, I was also getting the error `awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_UNEXPECTED_HANGUP: The connection was closed unexpectedly.` and for me, it turns out that I had not _activated_ the AWS IoT thing certificate. After creating it, there's another step to activate it.

**Comment by sukruavcuoglu** [comment]
> For me, this is caused by a duplicate client_id in the mqtt connection. Fort instance, if I have two devices running the same test code, I have to make sure that client_id in the mqtt connection constructor is not duplicated if I'm running the program twice.

love u <3

**Comment by evanmiller29** [comment]
I was having the same issue and the certificate was active. I had to select this certificate to my policy and re-run. That seemed to fix the issue

**Comment by yigit-bwise** [comment]
For me this was caused by not attaching policy to the certificate.

**Comment by philipogorman** [comment]
> For me, this is caused by a duplicate client_id in the mqtt connection. Fort instance, if I have two devices running the same test code, I have to make sure that client_id in the mqtt connection constructor is not duplicated if I'm running the program twice.

Thank you!

**Comment by karlpokus** [comment]
Gonna chime in here too as I had the same error. For me it was a permission issue. I had both `config-shadow` and `sample-shadow` enabled but only permissions for `sample-shadow`.

**Comment by lijingshanxi** [comment]
Hi, Please check if you have subscription of  topic $aws/xxx, the subscription may cause the isuue  AWS_ERROR_MQTT_UNEXPECTED_HANGUP

**Comment by lesau** [comment]
For future reference. I was getting the same error when testing out Just-in-time provisioning using "./aws-iot-device-sdk-python-v2/samples/pubsub.py"
awscrt.exceptions.AwsCrtError: AWS_ERROR_MQTT_UNEXPECTED_HANGUP: The connection was closed unexpectedly

To fix this:
1/ Check whether the client certificate is active
2/ Check whether the provisioning template (i.e., JITP) is active. If you have multiple templates, look for the one that is linked with the CA that issued the client certificate you are trying to register.
3/ Re-run the pubsub example twice. 
4/ If still doesn't work, issue a new client certificate using the same CA, and try again.

**Comment by alan-alvarenga-telus** [comment]
The client id is defined at the policy level. 
| Policy effect | Policy action | Policy resource |
| ------------- | -------------- | ---------------- |
Allow | iot:Connect | arn:aws:iot:{region}:{account}:client/basicPubSub
Allow | iot:Connect | arn:aws:iot:{region}:{account}:client/yourDeviceClientID

**Comment by RomanKhudobei** [comment]
In my case this issue was caused by exceeding message body size limit (128kB)

**Comment by cyber274** [comment]
> Are you connecting over websockets? The server will end the connection after [24 hours](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot) and the client must reconnect, that's expected behavior.

I have created connection over Websocket and the connection gets disconnect in 24 hours due to IOT core [limitation](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot). Can you help here that how to reconnect in such case?

I have created fresh issue here for [this](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/771) for the details.

**Comment by eduelias** [comment]
I am having the same issue, and it is random, sometimes it happens, and sometimes it doesn't. I believe it is something with the SDK trying to connect twice with the `/presence/` topic. For some reason, I get `DUPLICATE_CLIENTID` and get disconnected, even 100% sure the only device with said name/connection is on.

```
[ERROR] {SharedCrtResourceManager.cpp}: MQTT Connection interrupted with error: `libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.`. Device Client will retry connection until it is
```

![Image](https://github.com/user-attachments/assets/1c3465c6-7229-4916-95cc-6b0ddd26ca30)

I believe it tries to connect through both IPV4 and IPV6 (my device has both) and, as such, it creates a duplicated connection. How can we setup that we want just one route? Is it possible? 

```
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffad8ddd00] [dns] - static, invoking resolution callback for host xxxx-ats.iot.eu-west-1.amazonaws.com with **2** addresses
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [task-scheduler] - id=0xffff9c00b810: Scheduling attempt_connection task for immediate execution
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [task-scheduler] - id=0xffff9c00b930: Scheduling attempt_connection task for immediate execution
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [task-scheduler] - id=0xffff9c00b810: Running attempt_connection task with <Running> status
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001120 fd=8: initializing with domain 1 and type 0
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001120 fd=8: setting socket options to: keep-alive 0, keep idle 0, keep-alive interval 0, keep-alive probe count 0.
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001120 fd=8: beginning connect.
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001120 fd=8: connecting to endpoint 2a01:xxxxx:3::22fd:7e98:443.
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [task-scheduler] - id=0xffffa4001610: Scheduling (null) task for future execution at time 2078632299985920
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [task-scheduler] - id=0xffff9c00b930: Running attempt_connection task with <Running> status
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001a00 fd=9: initializing with domain 0 and type 0
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001a00 fd=9: setting socket options to: keep-alive 0, keep idle 0, keep-alive interval 0, keep-alive probe count 0.
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001a00 fd=9: beginning connect.
[DEBUG] [2025-01-23T10:48:33Z] [0000ffffae0edd00] [socket] - id=0xffffa4001a00 fd=9: connecting to endpoint 52.xx.133.57:443.

**Comment by eduelias** [comment]
So, indeed, I found out and will leave a comment here to document my problem, that is possibly other people's problem too:

Nucleus.

As we're using Nucleus to trigger component deployment, Nucleus also registers itself on the /presence/ topic and, as it has the same thingName (thus, client id), AWS's Device Client collides with the previous connection and hangs up. That's why was erratic: Sometimes AWS IoT Device Client started before Nucleus, and then it wouldn't fail but, when it started after Nucleus, then the error appeared. 

The solution given by AWS is to re-register the thing under a different name/deployment-template, and have each connection handled by different topics. It's not cost optimal, but it does the work.
