### ISSUE TITLE
Aws::Crt::Mqtt::MqttConnection::Connect crashes on Mac

### ISSUE THREAD

**Issue by anatolyaliev** [aws/aws-iot-device-sdk-cpp-v2#114]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution
  
**Describe the bug**
The application crashes on the first connection attempt

**Platform/OS/Device**
MacOS Mojave

**SDK version number**
v1.5.5

**To Reproduce (observed behavior)**
We are upgrading amazon sdk from version taken at March 8 2020, to official release 1.5.5
I've cloned the repository and built with cmake according the instructions
Then all the project settings were changed to point to the 1.5.5 sdk
Since then the application crashes on the first connection attempt. 

**Expected behavior**
No regression from the previous version expected

**Logs/output**
Please find the extract of crash dump of our application, relevant to the issue below:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [59704]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   fpbd                                0x000000010ee73a8c std::__1::__function::__func<Aws::Iot::MqttClientConnectionConfigBuilder::Build()::$_2, std::__1::allocator<Aws::Iot::MqttClientConnectionConfigBuilder::Build()::$_2>, void (std::__1::shared_ptr<Aws::Crt::Http::HttpRequest>, std::__1::function<void (std::__1::shared_ptr<Aws::Crt::Http::HttpRequest> const&, int)> const&)>::operator()(std::__1::shared_ptr<Aws::Crt::Http::HttpRequest>&&, std::__1::function<void (std::__1::shared_ptr<Aws::Crt::Http::HttpRequest> const&, int)> const&) + 332 (MqttClient.cpp:304)
1   fpbd                                0x000000010ee74ff8 Aws::Crt::Mqtt::MqttConnection::s_onWebsocketHandshake(aws_http_message*, void*, void (*)(aws_http_message*, int, void*), void*) + 216
2   fpbd                                0x000000010ee57dd4 aws_mqtt_client_connection_reconnect + 628
3   fpbd                                0x000000010ee579f2 aws_mqtt_client_connection_connect + 738 (client.c:1085)
4   fpbd                                0x000000010ee759ca Aws::Crt::Mqtt::MqttConnection::Connect(char const*, bool, unsigned short, unsigned int) + 282
5   fpbd                                0x000000010ecab72e AWSIoT::open(AWS*) + 3166 (AWSIoT.cpp:163)
6   ???                                 0x000000010ef2ae60 s_sha256_hmac_new_fn + 8

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
ApiHandle::InitializeLogging(...)
```

**Additional context**

**Comment by KaibaLopez** [comment]
Hi @anatolyaliev,
Sorry but can you provide a bit more info on this so that I may try and reproduce it?

Does this error happen when you run one of our samples? And if so how are you running it?
If it's not one of our samples, can you try them anyway to see if you face the same problem?

**Comment by anatolyaliev** [comment]
Hi @KaibaLopez ,
The error happens in our product execution after upgrading to  the version 1.5.5, but worked well with the previous version of SDK. We did not run the samples, could you please point me of how to execute them?

**Comment by anatolyaliev** [comment]
Hi @KaibaLopez, 
Could you please provide the instructions of how to run the required samples?

**Comment by jmklix** [comment]
To run the basic pubsub example the command should look like this
./basic-pub-sub --endpoint <endpoint> --root-ca <path to root CA>  --cert <path to the certificate> --key <path to the private key>  --topic TestTopic

Did you have questions about any specific examples?
