### ISSUE TITLE
Does a full shadow subscribe need to occur when network drops

### ISSUE THREAD

**Issue by psiphi75** [aws/aws-iot-device-sdk-cpp-v2#115]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Platform/OS/Device**
Compiling on Ubuntu, target is ARM Cortex processor (Linux based).

**Describe the question**
We expect many network interruptions when using the AWS SDK because of poor network connectivity that we can't mitigate.  It's not clear what happens when the underlying network connection is re-established, does a full shadow subscribe need to occur?  Such that a shadow GET/UPDATE is performed?  We are aiming to reduce the number of subscribe requests to keep our mobile data consumption low.

Considering the shadow is stored in memory on our thing, is it possible to keep this persistent across network and MQTT terminations?

**Comment by jmklix** [comment]
https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html
There is a persistent-session option. If the device calls connect() and passes false for cleanSession AND sessionPresent is true in the OnConnectionResumedHandler callback, then the server has remembered the client's subscriptions, and the server will send any QoS 1 messages that the client missed while they were offline.

But if sessionPresent is false, then the server has forgotten the client's subscriptions so the application *does* need to resubscribe. Also, the client might have missed a message from the server while they were offline, so the client might want to get the current shadow state again.

**Comment by psiphi75** [comment]
Thanks.  I think that solves the issue.
