### ISSUE TITLE
Connection/Client pointer

### ISSUE THREAD

**Issue by JerATie** [aws/aws-iot-device-sdk-cpp-v2#117]
Confirm by changing [ ] to [x] below:
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Linux

**Describe the question**
I'm using the SDK as part of a program that needs to subscribe and unsubscribe once a certain signal is received. I tried creating this by turning most of the variables inside the function to pointers, such as the connection and client. This works up to a certain point. That certain point being a topic name longer than 12 characters. Once the topic name goes over 12 characters the Stlallocator throws an error. So my question is if I'm abusing the SDK or if this should be possible?

The error happens when a message is received from a topic containing more than 12 characters or when subscribing to a topic containing more than 12 characters.

Error message:
Fatal error condition occurred in ~/Documents/newaws/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-common/source/allocator.c:76: allocator != ((void *)0)
Exiting Application
################################################################################
Resolved stacktrace:
################################################################################
0x00005617935aac4d: ?? ??:0
0x00005617935a33fd: ?? ??:0
0x00005617935a2831: ?? ??:0
0x0000561793515a8a: ?? ??:0
0x0000561793514589: ?? ??:0
0x0000561793512c03: ?? ??:0
0x0000561793512dda: ?? ??:0
0x000056179355a433: ?? ??:0
0x000000000019db27: s_packet_handler_publish at client_channel_handler.c:187 (discriminator 3)
0x000000000019d363: s_process_read_message at client_channel_handler.c:457 (discriminator 5)
0x00000000001d711d: s_s2n_handler_process_read_message at s2n_tls_channel_handler.c:492
0x00000000001d8d3c: s_do_read at socket_channel_handler.c:174
0x00000000001d9466: s_on_readable_notification at socket_channel_handler.c:233 (discriminator 5)
0x00000000001d5f86: s_on_socket_io_event at socket.c:1505
0x00000000001d1506: s_main_loop at epoll_event_loop.c:586
0x00000000001e40e1: thread_fn at thread.c:51
0x0000000000009609: start_thread at pthread_create.c:478 (discriminator 6)
0x00007f26d2acd103: ?? ??:0
################################################################################
Raw stacktrace:
################################################################################
./testaws(aws_backtrace_print+0x7d) [0x5617935aac4d]
./testaws(aws_fatal_assert+0x4d) [0x5617935a33fd]
./testaws(aws_mem_acquire+0x61) [0x5617935a2831]
./testaws(_ZN3Aws3Crt12StlAllocatorIcE8allocateEmPKv+0x2e) [0x561793515a8a]
./testaws(_ZNSt16allocator_traitsIN3Aws3Crt12StlAllocatorIcEEE8allocateERS3_m+0x2c) [0x561793514589]
./testaws(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcEN3Aws3Crt12StlAllocatorIcEEE9_M_createERmm+0xc3) [0x561793512c03]
./testaws(_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcEN3Aws3Crt12StlAllocatorIcEEE12_M_constructIPKcEEvT_SB_St20forward_iterator_tag+0x96) [0x561793512dda]
./testaws(_ZN3Aws3Crt4Mqtt14MqttConnection11s_onPublishEP26aws_mqtt_client_connectionPK15aws_byte_cursorS7_Pv+0x63) [0x56179355a433]
./testaws(+0x19db27) [0x561793564b27]
./testaws(+0x19d363) [0x561793564363]
./testaws(+0x1d711d) [0x56179359e11d]
./testaws(+0x1d8d3c) [0x56179359fd3c]
./testaws(+0x1d9466) [0x5617935a0466]
./testaws(+0x1d5f86) [0x56179359cf86]
./testaws(+0x1d1506) [0x561793598506]
./testaws(+0x1e40e1) [0x5617935ab0e1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x9609) [0x7f26d2ecf609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f26d2acd103]
Aborted (core dumped)

**Comment by TingDaoK** [comment]
Hi, thank you for reaching out. Can you provide us what platform and compiler Version you are using? I cannot reproduce the error with a topic name containing over 100 characters on my Linux machine. We may need more information to track it down. Thank you!

**Comment by JerATie** [comment]
Hey sorry I forgot about this. 
The reason why it happend was the api handle going out of scope which was causing this to happen.

Sorry for not closing this.
