### ISSUE TITLE
Error including aws-iot-device-sdk-cpp-v2 in esp-idf CMake project

### ISSUE THREAD

**Issue by kangks** [aws/aws-iot-device-sdk-cpp-v2#122]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on? MacOS 10.15.4, esp32

**Describe the question**

I attempted to include aws-iot-device-sdk-cpp-v2 into my esp-idf CMake project but encountered the following errors, how do I resolve?

Error as follows:
```
esp-idf-template % idf.py build
Executing action: all (aliases: build)
Running ninja in directory ~/Documents/github/esp-idf-template/build
Executing "ninja all"...
[0/1] Re-running CMake...
-- Building ESP-IDF components for target esp32
CMake Error at ~/Documents/github/esp-idf/tools/cmake/component.cmake:221 (message):
  CMake Error at
  ~/Documents/github/esp-idf-template/components/aws-iot-device-sdk-cpp-v2/CMakeLists.txt:2
  (project):

    project command is not scriptable

  Call Stack (most recent call first):

    ~/Documents/github/esp-idf/tools/cmake/scripts/component_get_requirements.cmake:60 (include)
    ~/Documents/github/esp-idf/tools/cmake/scripts/component_get_requirements.cmake:76 (__component_get_requirements)

  

  

Call Stack (most recent call first):
  ~/Documents/github/esp-idf/tools/cmake/build.cmake:405 (__component_get_requirements)
  ~/Documents/github/esp-idf/tools/cmake/project.cmake:395 (idf_build_process)
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "~/Documents/github/esp-idf-template/build/CMakeFiles/CMakeOutput.log".
FAILED: build.ninja 
~/.espressif/tools/cmake/3.16.4/CMake.app/Contents/bin/cmake -S~/Documents/github/esp-idf-template -B~/Documents/github/esp-idf-template/build
ninja: error: rebuilding 'build.ninja': subcommand failed
ninja failed with exit code 1
```

These are my steps:
1. Clone the esp-idf-template 
```
~/Documents/github % git clone https://github.com/espressif/esp-idf-template.git
```
2. Clone the aws-iot-device-sdk-cpp-v2 and update to pull in recursively 
```
~/Documents/github % cd esp-idf-template 
~/Documents/github/esp-idf-template % mkdir components && cd components
~/Documents/github/esp-idf-template/components % git submodule add https://github.com/aws/aws-iot-device-sdk-cpp-v2.git && git submodule update --init --recursive
```
3. Update the CMakeLists.txt in main/ folder to include aws-iot-device-sdk-cpp-v2 `set(COMPONENT_REQUIRES aws-iot-device-sdk-cpp-v2)`
3. Attempt to build 
```
~/Documents/github/esp-idf-template % idf.py build
```

**Comment by kangks** [comment]
Yes it is FreeRTOS based. Reason of looking at C++ SDK is because Provisioning API is in the main branch. This might not be the right place for this question, but do you know when will the Provisioning API be merged into main branch of the Embedded C SDK?

**Comment by justinboswell** [comment]
You would have to ask the Embedded C SDK team for that info, I honestly have no idea.

**Comment by jmklix** [comment]
Please ask any questions about the Embedded C SDK here: https://github.com/aws/aws-iot-device-sdk-embedded-C/issues
If you are still experiencing issues with c++ sdk you can open a new issue here
