### ISSUE TITLE
AWS_IO_SOCKET_NOT_CONNECTED error when machine is online

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#129]
Hi, I'm using SDK version 1.6.2. we are running soak tests on our machines, and we have an issue related to connectivity:

When a machine is running and communicating with AWS, from time to time we get onInterrupted callback (with AWS_IO_SOCKET_NOT_CONNECTED error code), followed by onResumed (I don't know what is the reason of the interruption). eventually we are getting onInterrupted callback without onResumed and we stay thinking that we are offline (although we are actually online).

I'm attaching SDK log file. you can see that from time to time AWS_IO_SOCKET_NOT_CONNECTED appears followed by on_resumed invocation, but at 23:16:47Z the connection error appears again, and there is no onResumed until the end of the log, hours later. although the machine is actually online.

thanks...

[awssdk.zip](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4877267/awssdk.zip)

**Comment by bretambrose** [comment]
Hello, thank you for the logs.  I wasn't able to make much sense of the disconnect and reconnects, but while looking at that I noticed that you have a very significant number of failing (with 403 forbidden) websocket handshakes, sometimes for very long intervals (grep 'Attempting reconnect' and look at the sequences of 128s) .  Looking at the logs of the handshakes and the signer, it looks like you're somehow injecting session credentials into a static provider and my guess is that the lifetime of those credentials are often getting out of sync with their authorization lifetime (i.e. they're expired).  The credentials look like they're changing over time, but there are still extended periods of repeated websocket upgrade failures (grep 'Incoming response status: 403 (Forbidden)')

The C libraries now have implementations of all the standard AWS credentials providers, but we haven't exposed all of them at the CRT level, beyond the default chain.  Is the default chain insufficient for your needs?  Do you need a binding for a provider we haven't exposed yet?  I know this is only tangentially related to your original issue, but clearing out all of these upgrade failures would make log analysis quite a bit easier.

**Comment by elad-ep** [comment]
we are using Aws::Iot::WebsocketConfig for the connection, and we initialize the WebsocketConfig with  Auth::CredentialsProviderStaticConfig - indeed with credentials that have short lifetime (verified against AWS STS). I would assume that the credentials are needed only for the initial connection and they are not needed any more even if the connection is interrupted and resumed (i.e. we don't care if the credentials are expired after the initial connection).

Do you see any issue with this mode of work?

**Comment by bretambrose** [comment]
Yeah, that's not ideal.  Every reconnect requires a new handshake which must be signed.  

Where are you getting those session credentials?  If it's IMDS, ECS, or from the aws profile (via an assume role entry), the default chain will work for you.  SDK-sourced credentials are aware of their own lifetimes and so when the credentials get near expiration, the default chain will requery and obtain fresh ones for you.  In this way, you should never seen 403 forbiddens due to signing with expired credentials.

If you're getting session credentials in some other way (x509, sts web identity are the other session-based ones I think) then we'll need to expose that provider for you, but that's a pretty straightforward task.

**Comment by elad-ep** [comment]
I'm getting session credentials from STS (by sending request to API gateway to get the credentials). since the credentials expire after a few minutes, how can it work with interruptions and reconnections? if credentials are needed also for reconnections, maybe you can expose a callback when you get 403, and I'll refresh the credentials in the static provider inside the callback? maybe you have another idea? thanks...

**Comment by bretambrose** [comment]
In that case, there are a couple of different possibilities:

1. We can expose the StsCredentialsProvider (https://github.com/awslabs/aws-c-auth/blob/master/include/aws/auth/credentials.h#L623) and/or a Cached-wrapped StsCredentialsProvider and you can use it directly by replacing the static provider with it.  The StsCredentialsProvider will get new credentials each time, and a cached-wrapped one will fetch new ones before expiration.
1. Use the existing default credentials provider chain (https://github.com/awslabs/aws-crt-cpp/blob/master/include/aws/crt/auth/Credentials.h#L319) and an on-device aws profile file (~/.aws/credentials is the default location) and specify a default profile (or override the AWS_PROFILE environment variable) that will do an assume role for you ala:
```
[default]
role_arn=arn:aws:iam::...
source_profile=stssource
region=...

[stssource]
aws_access_key_id=...
aws_secret_access_key=...
```
which creates a default profile that will use the static credentials in [stssource] to get session credentials that assume the specified role.

The second setup would work right now without any CRT/SDK changes.

Both solutions only require you to configure the  WebsocketConfig structure differently.  All of the refresh, caching, etc... is handled internally.

**Comment by elad-ep** [comment]
the second solution is less suitable because we don't want to save credentials on the disk. so the first solution is preferable. but what I didn't understand is how you know to get credentials from STS. when we get credentials from STS we fetch them from a URL that looks like: https://<iot:CredentialProvider endpoint>/role-aliases/<role alias>/credentials
and this is the scheme we use:
https://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html

(earlier on I wrote by mistake we get credentials from API gateway. please ignore that)

we identify ourselves to STS using our key and iot certificate (as describe in the above link).

So will the Cached StsCredentialsProvider be able to get the credentials from the STS URL using our key and certificate? how will it know the credentials URL? thanks..

**Comment by bretambrose** [comment]
In that case you're not using STS directly and instead you'll want to use the x509 credentials provider.  We've already exposed that in Java for another customer (https://github.com/awslabs/aws-crt-java/blob/master/src/main/java/software/amazon/awssdk/crt/auth/credentials/X509CredentialsProvider.java).  You can have a look there; the configuration for C++ will be comparable.

**Comment by elad-ep** [comment]
excellent - can you please also expose it for C++ as well?

**Comment by bretambrose** [comment]
I will try and get it done in the next few days.

**Comment by elad-ep** [comment]
@bretambrose thanks... can you please cut a new release version with those changes?

**Comment by elad-ep** [comment]
Is the mentioned PR (X509 Credentials Provider Binding awslabs/aws-crt-cpp#151) is the final PR for those changes? is there an expectation when will it merged and released? thanks...

**Comment by bretambrose** [comment]
The x509 binding has now been merged and the pub sub example can be configured to use it via command line options.  Give it a try and if successful, check your soak tests and see if behavior is improved.

**Comment by elad-ep** [comment]
When I initialize the TlsContext (as in the pub sub sample), the program crashes. I can see that TlsContext calls aws_import_key_pair_to_cert_context in windows_pki_utils.c (I verified the private_key parameter is fine - it is my private key buffer). then CryptDecodeObjectEx is called inside this function and it fails with last error "0x8009310b : ASN1 bad tag value met.". then LocalFree is called on the key (which is null) and the program crashes.

I couldn't understand why CryptDecodeObjectEx fails. do you have an idea?

**Comment by bretambrose** [comment]
Make sure your cert and key are both clean, stripped pem files, with no additional attributes outside of:

```
-----BEGIN CERTIFICATE-----
[stuff]
-----END CERTIFICATE-----
```
or something similar for the key file.

Are you running pub sub or your own re-doing?  I'd start with pub sub without using x509, then switch to pub sub x509, if you weren't already.

**Comment by bretambrose** [comment]
Can you use pub sub (with no x509) with the cert?  Also, please don't attach any potential secrets on the issue.  How did you source the cert/key pair?

**Comment by elad-ep** [comment]
I see the pub sub crashes with those files also without x509. the files are not secret - those are test files (the key was generated using openssl, the certificate was generated in AWS).

**Comment by elad-ep** [comment]
I create private key and csr with openssl, the csr is sent to cloud and in the cloud side certificate is generated from the csr using CreateCertificateFromCsr iot API and sent to the endpoint.

**Comment by bretambrose** [comment]
The API call failure is a win32 call that is simply decoding the private key, and the cert isn't involved.  So something about the private key's format or properties is making windows unhappy.  

I'd like to follow the exact, literal steps you are doing to generate everything, down to all the individual options on the openssl calls as well as the exact steps to register the csr and then create the certificate from it (ideally using the aws cli, but AWS console steps are ok too).  Can you provide that?

**Comment by elad-ep** [comment]
yes, I will send you by email the openssl call sequence

**Comment by elad-ep** [comment]
I read here there is incompatibility between openssl and windows crypto api in regards to key format:
https://stosd.wordpress.com/2017/04/22/capi-openssl/

(I tried manually decoding the base64 string in the key, reverse the byte order and re-encode. but CryptDecodeObjectEx still didn't accept this new encoded key)

**Comment by bretambrose** [comment]
Interesting, that could be the issue.  As we investigate this, do you have access to a Mac or linux machine to test on?  If so, can you try there and post the results?

**Comment by elad-ep** [comment]
I don't have currently non-windows machine for this test.. I can try tomorrow. is it possible to handle this in the sdk (i.e. converting openssl formatted certificates to Crypto api format)?

**Comment by bretambrose** [comment]
I just consulted with our crypto/tls expert and it looks like a pkcs7 vs pkcs8 issue.  In particular, right now we only support pkcs7 import on Windows (we need to get the additional support in asap) and based on the sample code you mailed me, you are exporting the private key via pkcs8.  Can you try changing your export to pkcs7 and seeing what happens?

**Comment by elad-ep** [comment]
thanks, I changed openssl to export the key in the older RSA format and processing of the key doesn't fail any more. however, now the pub sub sample (with x509) doesn't manage to get credentials from STS. I get AWS_AUTH_SIGNING_NO_CREDENTIALS error. attached full log:
[awssdk.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4964301/awssdk.log)

**Comment by bretambrose** [comment]
What's the command line you're passing in?  It's using the default
credentials provider which is what's used when you select websockets and
don't set the x509 flag.

**Comment by elad-ep** [comment]
but I debugged the pub sub sample and see it uses the x509 parameters. I will email you the exact parameters

**Comment by elad-ep** [comment]
OK, so currently after the latest fix in sample, the x509 connects successfully. I'm now testing disconnections/reconnections with the sample, and when I disable the network adapter the onInteruptted callback is not invoked (even if I wait some time). can you please check why onInteruppted/onResumed doesn't work properly?

**Comment by bretambrose** [comment]
Without a low ping/keepalive, disconnects can take a while to be discovered at the socket level.  More information here: https://github.com/aws/aws-iot-device-sdk-python-v2/issues/90

**Comment by elad-ep** [comment]
I see.. so far my testing is successful. can you please cut a new release version with the x509 support?

**Comment by bretambrose** [comment]
I've made a new release that includes the updated sample.
