### ISSUE TITLE
Samples CMake Files don't work in Standalone project

### ISSUE THREAD

**Issue by jlong29** [aws/aws-iot-device-sdk-cpp-v2#135]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
I successfully installed the SDK according to the instructions on the Github page. I am looking to include the aws-iot-device-sdk-cpp-v2 in my own project that uses them. I had a feeling the CMake bit was going to be trouble, so I started by forking my own branch and adding my project under the Samples directory. That worked. Now it is time to pull the band-aid off by separating out my project and finding the relevant packages. I had hoped to modify the CMakeLists.txt files provided in the Samples, but this isn't working at all. It seems like there are dependencies upon information upstream of the Sample CMakeLists.txt and it is not clear what it is. I've tried, but I am getting very frustrated. I believe the path towards integrating the SDK into other projects is buggy. I don't think this is an additional feature.

**Platform/OS/Device**
Ubuntu 16.04

**SDK version number**
It is the V2 SDK, but I'm not sure where the version information is. I synced with master on July 10 2020

**To Reproduce (observed behavior)**
Make an external project that looks to bring in the SDK and see what happens. LMK if I am doing something wrong

**Expected behavior**
If you do what I'm doing, it won't work. It seems like the required information to integrate the SDK into a project is spread over several cmake files. Shouldn't one be able to adapt one of the example Sample CMakeLists.txt?

**Logs/output**
I run cmake with `cmake -DCMAKE_INSTALL_PREFIX=/path/to/aws-iot-device-sdk-cpp-v2/build/install ..`
In my CMakeList.txt, I have...

```
cmake_minimum_required(VERSION 3.1)
project(My-App CXX)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_INSTALL_PREFIX}/lib/cmake")

MESSAGE(STATUS "CMAKE_MODULE_PATH: ${CMAKE_MODULE_PATH}")

file(GLOB MY_APP_SRC
       "*.cpp"
)

MESSAGE(STATUS "MY_APP_SRC: ${MY_APP_SRC}")

set(MY_APP_PROJECT_NAME My-App)
add_executable(${MY_APP_PROJECT_NAME} ${MY_APP_SRC})
set_target_properties(${MY_APP_PROJECT_NAME} PROPERTIES LINKER_LANGUAGE CXX)

set(CMAKE_CXX_STANDARD 11)

include(AwsFindPackage)

#set warnings
if (MSVC)
    target_compile_options(${MY_APP_PROJECT_NAME} PRIVATE /W4 /WX /wd4068)
else ()
    target_compile_options(${MY_APP_PROJECT_NAME} PRIVATE -Wall -Wno-long-long -pedantic -Werror)
endif ()

if (CMAKE_BUILD_TYPE STREQUAL "" OR CMAKE_BUILD_TYPE MATCHES Debug)
    target_compile_definitions(${MY_APP_PROJECT_NAME} PRIVATE "-DDEBUG_BUILD")
endif ()

aws_use_package(aws-crt-cpp)
target_include_directories(${MY_APP_PROJECT_NAME} PUBLIC
        ${PNG_INCLUDE_DIR}
        ${CMAKE_INSTALL_PREFIX}/include
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>)

target_link_libraries(${MY_APP_PROJECT_NAME} ${DEP_AWS_LIBS})

```

When I run the cmake command, I get...
```
-- The CXX compiler identification is GNU 6.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_MODULE_PATH: /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/cmake
-- MY_APP_SRC: My-App.cpp
CMake Warning (dev) at /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/cmake/AwsFindPackage.cmake:14 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'IN_SOURCE_BUILD'.
Call Stack (most recent call first):
  CMakeLists.txt:21 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found LibCrypto: /usr/local/lib/libcrypto.a  
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
CMake Warning (dev) at /usr/me/.local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (LibCrypto)
  does not match the name of the calling package (LibCryptoCAL).  This can
  lead to problems in calling code that expects `find_package` result
  variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/cmake/FindLibCryptoCAL.cmake:61 (find_package_handle_standard_args)
  /usr/me/.local/share/cmake-3.17/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/aws-c-cal/cmake/aws-c-cal-config.cmake:4 (find_dependency)
  /usr/me/.local/share/cmake-3.17/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/aws-crt-cpp/cmake/aws-crt-cpp-config.cmake:5 (find_dependency)
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/cmake/AwsFindPackage.cmake:29 (find_package)
  CMakeLists.txt:64 (aws_use_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
CMake Warning (dev) at /usr/me/.local/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (LibCrypto)
  does not match the name of the calling package (LibCryptoCAL).  This can
  lead to problems in calling code that expects `find_package` result
  variables (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/cmake/FindLibCryptoCAL.cmake:61 (find_package_handle_standard_args)
  /usr/me/.local/share/cmake-3.17/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/aws-c-cal/cmake/aws-c-cal-config.cmake:4 (find_dependency)
  /usr/me/.local/share/cmake-3.17/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/aws-c-auth/cmake/aws-c-auth-config.cmake:4 (find_dependency)
  /usr/me/.local/share/cmake-3.17/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/aws-crt-cpp/cmake/aws-crt-cpp-config.cmake:6 (find_dependency)
  /path/to/aws-iot-device-sdk-cpp-v2/build/install/lib/cmake/AwsFindPackage.cmake:29 (find_package)
  CMakeLists.txt:64 (aws_use_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- LibCrypto Include Dir: /usr/local/include
-- LibCrypto Shared Lib:  /usr/local/lib/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/lib/libcrypto.a
-- DEP_AWS_LIBS: AWS::aws-crt-cpp.
-- Configuring done
-- Generating done
-- Build files have been written to: /path/to/MyApp/build

```
Which is similiar to what I see when I run cmake with MyApp as another Sample. Though, one difference is that I build the Dependencies, so IN_SOURCE_BUILD is set to ON. This doesn't seem to matter. When I don't set IN_SOURCE_BUILD and run `make` I get:
```
`CMakeFiles/My-App.dir/build.make:129: *** target pattern contains no `%'.  Stop.
make[1]: *** [CMakeFiles/My-App.dir/all] Error 2
make: *** [all] Error 2
`

```
And when I look at the build.make file, AWS::aws-crt-cpp is NOT FOUND. When I run my cmake command with IN_SOURCE_BUILD set to ON, make returns:
```
/usr/bin/x86_64-linux-gnu-ld: cannot find -laws-crt-cpp
collect2: error: ld returned 1 exit status
make[2]: *** [My-App] Error 1
make[1]: *** [CMakeFiles/My-App.dir/all] Error 2
make: *** [all] Error 2
```
I have even tried manually including the  specific library, but then is complains about missing all other dependency libraries. At this point, am reduced to including them by hand. This is not a good solution. Am I doing something wrong? Is there a problem?

**Comment by DavidOgunsAWS** [comment]
For simplicity you could install the this, aws-crt-cpp, and all aws-c-* libraries in your default system paths. Assuming CMake is configured sensibly on your system, and you don't have multiple projects wanting different versions this should work well and easily enough:

**Pre:** Ensure you have all of the git submodules initialized and updated in the aws-common-runtime directory.

1. Build and install aws-iot-device-sdk-cpp-v2 using system paths in a build directory by running the following:
`cmake -DBUILD_DEPS=ON ../`  <- this command assumes you are in a direct child build directory from 
aws-iot-device-sdk-cpp-v2/
`make -j`
`sudo make install` <- this command needs write access to a path like /usr/lib, or /usr/local/lib. Look at the output to verify where it is copying files to and make sure CMake is looking there

2. In your own project, you can reference/depend on the CRT and IoT Device SDK CPP just as the samples do and a normal cmake -> make command will work provided all of the commands in step 1 worked.

You can choose to install aws-crt stuff in another path using `-DCMAKE_INSTALL_PREFIX=/some/dir/A` in step 1. This will remove the need to run  `sudo` for `make install`; but then step 2 your cmake command must specify `-DCMAKE_PREFIX_PATH=/some/dir/A` so it knows where to find the CRT.

I hope this helps and clarifies things.

**Comment by JonathanHenson** [comment]
The samples follow a different cmake pattern than a consuming application would. For example, if you run cmake on aws-iot-device-SDK-v2 with BUILD_DEPS=ON, and install it to a predefined location, then use CMAKE_PREFIX_PATH when building your app, you’ll need to use find_package(aws-iot-device-sdk-cpp-v2) that should work. If you include it as a subdirectory (as the samples do), you don’t use find_package

**Comment by dwjbosman** [comment]
find_package(aws-iot-device-sdk-cpp-v2) doesn't seem to work. Building and Installing aws-iot-device-sdk-cpp-v2 doesn't install the required cmake script to use find_package 

`By not providing "Findaws-iot-device-sdk-cpp-v2.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "aws-iot-device-sdk-cpp-v2", but CMake did not find one.

  Could not find a package configuration file provided by
  "aws-iot-device-sdk-cpp-v2" with any of the following names:

aws-iot-device-sdk-cpp-v2Config.cmake
aws-iot-device-sdk-cpp-v2-config.cmake` 

Did a 

find . -name *aws-iot-device-sdk-cpp-v2*.cmake

but nothing found.

**Comment by MarcoRBosco** [comment]
@DavidOgunsAWS I tried your proposal (everything compiled correctly in /usr/local) and using a similar CMakeFile as provided by @jlong29 in my project I still have the same output error:
```
/build.make:83: *** target pattern contains no '%'.  Stop.
```
In my CMakeFile:
```
set(CMAKE_AWS_INSTALL_PREFIX /usr/local)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_AWS_INSTALL_PREFIX}/lib/cmake")
```
And as @dwjbosman mentioned there is no configuration file of aws-iot-device-sdk-cpp-v2.

**Comment by JonathanHenson** [comment]
``By not providing "Findaws-iot-device-sdk-cpp-v2.cmake" in CMAKE_MODULE_PATH
this project has asked CMake to find a package configuration file provided
by "aws-iot-device-sdk-cpp-v2", but CMake did not find one.

Could not find a package configuration file provided by
"aws-iot-device-sdk-cpp-v2" with any of the following names:

aws-iot-device-sdk-cpp-v2Config.cmake
aws-iot-device-sdk-cpp-v2-config.cmake `

This is an antiquated useless cmake output I wish the cmake team would fix. That’s not modern cmake advice.

Anyways, I unintentionally misled you. aws-iot-device-sdk-cpp-v2 isn’t a target so of course find package doesn’t work. Look at the CMakeLists.txt for the component you want to use and use that target.

a.) yes all of the cmake files are indeed installed
b.) you never need to point directly at the cmake config stuff. Use the find_package command, make sure CMAKE_PREFIX_PATH is set to where you installed
c.) use an actual target.

**Comment by MarcoRBosco** [comment]
First of all let me apologize for my lack of experience with CMake.

I'm trying to compile the sample basic_pub_sub standalone with the following cmake file:

```
cmake_minimum_required(VERSION 3.16)

project(basic-pub-sub CXX)

set(CMAKE_INSTALL_PREFIX /usr/local)

message(STATUS "MY_APP_SRC: ${CMAKE_INSTALL_PREFIX}")

list(APPEND CMAKE_MODULE_PATH "${CMAKE_INSTALL_PREFIX}/lib/cmake")

message(STATUS "CMAKE_MODULE_PATH: ${CMAKE_MODULE_PATH}")

file(GLOB PUB_SUB_SRC
       "*.cpp"
)

message(STATUS "MY_APP_SRC: ${PUB_SUB_SRC}")
message(STATUS "CMAKE_INSTALL_PREFIX: ${CMAKE_MODULE_PATH}")

set(PUB_SUB_PROJECT_NAME basic-pub-sub)
add_executable(${PUB_SUB_PROJECT_NAME} ${PUB_SUB_SRC})
set_target_properties(${PUB_SUB_PROJECT_NAME} PROPERTIES LINKER_LANGUAGE CXX)

find_package(aws-crt-cpp REQUIRED)

#set warnings
if (MSVC)
    target_compile_options(${PUB_SUB_PROJECT_NAME} PRIVATE /W4 /WX /wd4068)
else ()
    target_compile_options(${PUB_SUB_PROJECT_NAME} PRIVATE -Wall -Wno-long-long -pedantic -Werror)
endif ()

target_include_directories(${PUB_SUB_PROJECT_NAME} PUBLIC
        ${CMAKE_INSTALL_PREFIX}/include
        $<BUILD_INTERFACE:${CMAKE_INSTALL_PREFIX}/include>
        $<INSTALL_INTERFACE:include>)

target_link_libraries(${PUB_SUB_PROJECT_NAME} aws-crt-cpp)
```
I did all the steps indicated by @DavidOgunsAWS and everything worked fine and the library was installed in ```/usr/local```. 

With this new approach I don't ge the error:

```
/build.make:83: *** target pattern contains no '%'.  Stop.
```
But I get linking errors such as:

```
undefined reference to `aws_default_allocator'
```
I don't know what I'm missing.

Thank you for your help

**Comment by JonathanHenson** [comment]
`set(CMAKE_INSTALL_PREFIX /usr/local)`

don't do this in your cmake file. CMAKE_INSTALL_PREFIX already has a default for the system, but more importantly, that's rarely what you want. Regardless, the user passes CMAKE_INSTALL_PREFIX to your cmake project.

Let's take the install directory out of the equation. Let's just assume there's a directory called `/users/foo/artifacts`.

your cmake usage should look like:

mkdir aws-iot-device-sdk-build
cd aws-iot-device-sdk-build
cmake -DCMAKE_INSTALL_PREFIX=/users/foo/artifacts -DBUILD_DEPS=ON <path to aws-iot-device-sdk-cpp-v2>
make -j
make install

cd ..
mkdir your-project-build
cd your-project-build
cmake -DCMAKE_PREFIX_PATH=/users/foo/artifacts <path to your-project>
make -j

**Comment by JonathanHenson** [comment]
per:
`undefined reference to `aws_default_allocator'`

This looks like you used target_link_libraries with a library name without using find_package first. The package finder will automatically add transitive dependencies to your linker args. Doing it manually based on target will not.

In the example you provided:

`target_link_libraries(${PUB_SUB_PROJECT_NAME} aws-crt-cpp)`

should be:

``target_link_libraries(${PUB_SUB_PROJECT_NAME} AWS::aws-crt-cpp)``

**Comment by MarcoRBosco** [comment]
@JonathanHenson  I tried your suggestions and I get the following error:

```
aws-c-event-stream-config.cmake

  but it set aws-c-event-stream_FOUND to FALSE so package
  "aws-c-event-stream" is considered to be NOT FOUND.  Reason given by
  package:

  The following imported targets are referenced, but are missing:
  AWS::aws-checksums
```

I'm still trying, but I'm still struggling to compile.

**Comment by TingDaoK** [comment]
Did you update the submodules? 
```
git submodule update --init --recursive
```

**Comment by MarcoRBosco** [comment]
Yes, I already did that and rebuilt. Still not working.

I checked the
```
install_driectory/aws-c-event-stream/cmake/aws-c-event-stream-config.cmake 
```
and it uses find_depency(aws-checksums) 

and when you check the 
```
install_driectory/aws-checksums/cmake/aws-checksums-config.cmake 
```
it looks for
```
 include(${CMAKE_CURRENT_LIST_DIR}/static/aws-iot-device-sdk-cpp-v2-targets.cmake)
```
but when you go the folder there is no aws-iot-device-sdk-cpp-v2-targets.cmake instead there is aws-checksums-targets.cmake

I even searched in the install_directory and didn’t find it
```
find . -name *aws-iot-device-sdk-cpp-v2*.cmake
```

**Comment by MarcoRBosco** [comment]
I could compile the sample project as standalone (compiling and installing directly aws-crt-cpp) but I needed to modify the following file:

```
install_directory/lib/aws-checksums/cmake/aws-checksums-config.cmake
```
From:
```
if (BUILD_SHARED_LIBS)
    include(${CMAKE_CURRENT_LIST_DIR}/shared/aws-crt-cpp-targets.cmake)
else()
    include(${CMAKE_CURRENT_LIST_DIR}/static/aws-crt-cpp-targets.cmake)
endif()

```
To:
```
if (BUILD_SHARED_LIBS)
    include(${CMAKE_CURRENT_LIST_DIR}/shared/aws-crt-cpp-targets.cmake)
else()
    include(${CMAKE_CURRENT_LIST_DIR}/static/aws-checksums-targets.cmake)
endif()
```

**Comment by MarcoRBosco** [comment]
I think I find a solution that at least works for me. Use the last commit from aws-crt-cpp and modify the following file (aws-crt-cpp/aws-common-runtime/aws-checksums/cmake/aws-checksums-config.cmake)

From:
```
if (BUILD_SHARED_LIBS)
    include(${CMAKE_CURRENT_LIST_DIR}/shared/@CMAKE_PROJECT_NAME@-targets.cmake)
else()
    include(${CMAKE_CURRENT_LIST_DIR}/static/@CMAKE_PROJECT_NAME@-targets.cmake)
endif()
```
To:
```
if (BUILD_SHARED_LIBS)
    include(${CMAKE_CURRENT_LIST_DIR}/shared/@PROJECT_NAME@-targets.cmake)
else()
    include(${CMAKE_CURRENT_LIST_DIR}/static/@PROJECT_NAME@-targets.cmake)
endif()
```
As it use @CMAKE_PROJECT_NAME@ and not @PROJECT_NAME@ it will use aws-iot-device-sdk-cpp-v2-targets instead of 
aws-checksums-targets generating a CMakeError.

https://github.com/awslabs/aws-checksums/pull/28

But change was not done in aws-checksums/aws-checksums-config.cmake.

I will open a issue in aws-checksums.

**Comment by HpLightcorner** [comment]
Hey,

**Environment:** 

- CMake-Project compiled with MSVC Toolchain (MSVC19.27)
- CMake 3.18
- Visual Studio Code with C/C++ and CMake Integration
- Working on Windows

**Issue:**
 I am actually facing the same problem as it is really hard to get from the samples-CMake File to a running standalone setup. I am not sure why, but in my case `asws-c-common ` was not linked. As it took me a lot of time to completely automize the build, I want to add/share my experience here.

My CMakeLists root file looks like the following:

```
cmake_minimum_required(VERSION 3.17)
#
# Make Fetch-Content available
include(FetchContent)

#
# Ensure VCPKG is installed or available on environment-variable VCPKG_ROOT before including external dependencies
include(./cmake/InstallVcpkg.cmake)

#
# Ensure dependencies are installed
include (./extern/InstallVcpkgDependencies.cmake)
include (./extern/InstallAwsIotDeviceSdkCppV2.cmake)

#
# Plugin and Target-Name
set(PLUGIN_NAME ...)

#
# Call project command onces
project(${PLUGIN_NAME})

add_executable(${PLUGIN_NAME}
    ${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
)

#
# Set Compile-Options
target_compile_options(${PLUGIN_NAME} PRIVATE /W4 /WX /wd4068 /EHsc)

#
# Set C++ Standard
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

#
# Include external dependencies
add_subdirectory(extern)
```

First of all, setting  `target_compile_options` is - at least with my current MSVC install, cruciual. I am totally unsure why I had to set `\EHsc` to get everything working - but at least it did solve my issues.

As you can see, I am building and installing `aws-iot-device-sdk-cpp-v2` in a seperate CMake by invoking `include (./extern/InstallAwsIotDeviceSdkCppV2.cmake)` script which is given as follows:

```
set(AWS_DEPS_BUILD_DIR ${CMAKE_CURRENT_BINARY_DIR}/deps/aws)
set(AWS_DEPS_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/deps/aws/install)

list(APPEND CMAKE_MODULE_PATH "${AWS_DEPS_INSTALL_DIR}/lib/cmake")
list(APPEND CMAKE_MODULE_PATH "${AWS_DEPS_INSTALL_DIR}/lib64/cmake")

if (NOT DEFINED CMAKE_PREFIX_PATH)
    set(CMAKE_PREFIX_PATH ${AWS_DEPS_INSTALL_DIR})
endif()

if(NOT EXISTS ${AWS_DEPS_BUILD_DIR})
    file(MAKE_DIRECTORY ${AWS_DEPS_BUILD_DIR})
    message("Building AWS-IOT-Device-SDK-Cpp-V2...")
    
    execute_process(
        COMMAND ${CMAKE_COMMAND} -G ${CMAKE_GENERATOR}
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_INSTALL_PREFIX=${AWS_DEPS_INSTALL_DIR}
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${CMAKE_CURRENT_BINARY_DIR}/bin
        -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
        -DBUILD_DEPS=ON
        -DBUILD_SAMPLES=OFF
        ${CMAKE_CURRENT_SOURCE_DIR}/extern/aws-iot-device-sdk-cpp-v2
        WORKING_DIRECTORY ${AWS_DEPS_BUILD_DIR}
        RESULT_VARIABLE BUILD_AWSCRT_EXIT_CODE
    )
    
    if (NOT ${BUILD_AWSCRT_EXIT_CODE} EQUAL 0)
    message(FATAL_ERROR "Failed to configure aws iot device libraries.")
    endif()
    
    execute_process(COMMAND ${CMAKE_COMMAND} --build . --config ${CMAKE_BUILD_TYPE}
    WORKING_DIRECTORY ${AWS_DEPS_BUILD_DIR}
    RESULT_VARIABLE BUILD_AWSCRT_EXIT_CODE)
    
    if (NOT ${BUILD_AWSCRT_EXIT_CODE} EQUAL 0)
    message(FATAL_ERROR "Failed to build aws iot device libraries.")
    endif()
    
    execute_process(COMMAND ${CMAKE_COMMAND} --install . --config ${CMAKE_BUILD_TYPE}
    WORKING_DIRECTORY ${AWS_DEPS_BUILD_DIR}
    RESULT_VARIABLE BUILD_AWSCRT_EXIT_CODE)
    
    if (NOT ${BUILD_AWSCRT_EXIT_CODE} EQUAL 0)
    message(FATAL_ERROR "Failed to install aws iot device libraries.")
    endif()
else()
    message("AWS-IOT-Device-SDK-Cpp-V2 has already been build. Delete folder ${AWS_DEPS_BUILD_DIR} to trigger a rebuild.")
endif()

message("AWS-IOT-Device-SDK-Cpp-V2 is installed at: ${AWS_DEPS_INSTALL_DIR}")

list(APPEND CMAKE_PREFIX_PATH "${AWS_DEPS_INSTALL_DIR}")
list(APPEND CMAKE_MODULE_PATH "${AWS_DEPS_INSTALL_DIR}/lib/cmake")
list(APPEND CMAKE_MODULE_PATH "${AWS_DEPS_INSTALL_DIR}/lib64/cmake")

include(AwsCFlags)
include(AwsSharedLibSetup)
include(AwsSanitizers)
include(AwsFindPackage)

message("\
AWS-IOT-Device-SDK-Cpp-V2 added the following variable: AWS_DEPS_INSTALL_DIR ${AWS_DEPS_INSTALL_DIR} \r\n\
which has been added to CMAKE_PREFIX_PATH. Example-useage: \r\n\
aws_use_package(aws-c-common) \r\n\
aws_use_package(aws-crt-cpp) \r\n\
target_link_libraries(\${target-name} \${DEP_AWS_LIBS}) \r\n\
target_include_directories(\${target-name} PRIVATE \${AWS_DEPS_INSTALL_DIR}/include)\
 ")
```

And finally, and that was my major concern when setting up my CMake-Project, im am including the lib by invoking `add_subdirectory(extern)` (of course after calling project and creating the target correctly:

```
#
# Add AWS IOT
aws_use_package(aws-c-common)
aws_use_package(aws-crt-cpp)
target_link_libraries(${PLUGIN_NAME} ${DEP_AWS_LIBS})
target_include_directories(${PLUGIN_NAME} PRIVATE ${AWS_DEPS_INSTALL_DIR}/include)
```

You see, i had to include both, `aws-c-common` and `aws-crt-cpp`, which is in **contrast to the example** (I actually have not found out what is going wrong in my setup - so if I am missing something it would be nice to give me some advice). 

**Suggestions:**

- Improve the documentation regarding necessary/mandatory compile options for standalone projects
- Add some tips/documentation regarding how to automatically build the sdk - especially as it is not available on a package-manager like `vcpkg `or `conan`.
- Clarify which libs are mandatory to link to setup a standalone example or at least what the CMake build system is actually doing to build examples as diving into CMake does take time
- I also tried using the library with `FetchContent` CMake module. However, I was not able to set it up correctly ending writing a CMake script to do a more traditional build. Maybe it would be a good idea to investigate if making `FetchContent` would be an option?

**Comment by bretambrose** [comment]
SDK samples have been made standalone and now have detailed build instructions in the samples readme.
