### ISSUE TITLE
AWS_ERROR_MQTT_UNEXPECTED_HANGUP

### ISSUE THREAD

**Issue by ndvbd** [aws/aws-iot-device-sdk-cpp-v2#137]
The python sdk works fine for me, but when I run this cpp client with the same parameters it throws:

Connecting...
Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.

Any ideas?

**Comment by bretambrose** [comment]
Hello,

To cut down on boilerplate iteration and red herrings, it's best to fill in the issue template when creating a new issue.

Can you supply: your platform, the SDK version you're using, reproduction steps (reproduction by running a sample is the easiest for us to work with), and attach a trace log of the failing run.

**Comment by ndvbd** [comment]
That's the command:

```
basic-pub-sub.exe --endpoint a1bli8kvdl3b9v-ats.iot.us-east-2.amazonaws.com --cert 50b5ac4b99-certificate.pem.crt --key 50b5ac4b99-private.pem.key --topic sdk/test/Python --ca_file root.ca
Connecting...
Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
```

We're talking about c++ on windows at the moment. I don't see the SDK version in the code (where is it?) but I was just cloned from github.
I downloaded the certificates with "One-click certificate creation (recommended)"

**Comment by bretambrose** [comment]
What's the permission policy associated with the certificate?  A common problem is having a topic or client-id restriction in the policy and then trying to connect or publish/subscribe outside the restriction.

**Comment by ndvbd** [comment]
I solved the problem by adding a command line argument:

--client_id basicPubSub

But here's the thing. Your python sdk doesn't require this parameter (it has this value by default), and the CPP sdk example doesn't do that. I would be helpful if you do the same in both the python and cpp example, otherwise it's confusing...

**Comment by bretambrose** [comment]
Normalizing command line parameters and support in the samples across all the SDKs is a good idea.  We'd happily take PRs that work towards that as well.

**Comment by TingDaoK** [comment]
The client_id and topic are not required for cpp-v2 as python-v2 does now.
https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/128

**Comment by Radagan** [comment]
I'm getting this error currently.

`
~/Development/libs/aws-iot-device-sdk-cpp-v2-build/samples/mqtt/basic_pub_sub/basic-pub-sub --endpoint a3rvmixc811azv-ats.iot.us-west-2.amazonaws.com --ca_file root-CA.crt --cert cert.pem.crt --key private.key --topic test
Connecting...
Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
`

As this is just a test account, my policy is very permissive.
`
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-west-2:424091364653:topic/test"
    }
  ]
}
`

I'm very new to AWS IoT Core. Any help would be very appreciated.
