### ISSUE TITLE
Application crashed when wrong configuration provided

### ISSUE THREAD

**Issue by laurenceliu1** [aws/aws-iot-device-sdk-cpp-v2#145]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
We found the application will crash when using the return in code if wrong configuration is provided like wrong cert.
I know the ext(-1) in the sample code doesn't have problem, but it's not applicable to us.
It's reproducible when using return -1.

**Platform/OS/Device**
Windows 10
Compile with Visual Studio 2019

**SDK version number**
v2, not sure the version, sync on August 24 2020.

**To Reproduce (observed behavior)**
1. Change sample project basic-pub-sub line 375~382 to
``` 
if (!clientConfig)
{ 
    fprintf(
        stderr,
        "Client Configuration initialization failed with error %s\n",
        ErrorDebugString(clientConfig.LastError()));
    **return -1;**
}
```
2. Run sample code with wrong cert
3. The application will crash on
```
basic-pub-sub.exe!aws_tls_ctx_destroy(aws_tls_ctx * ctx) Line 1733
```

**Expected behavior**
The application should exit normally without crash.

**Logs/output**
N/A

**Additional context**
Currently, we add NULL check in function aws_tls_ctx_destroy before release the aws_tls_ctx object to avoid the crash.

**Comment by rccarper** [comment]
Hello, it looks like when the context fails to create due to the bad certificate, a shared pointer is incorrectly storing a strong reference to a null pointer.  I just opened up a new PR for a fix.

**Comment by rccarper** [comment]
We've merged in a couple of fixes, but still need to do some additional work to get those into a release for this SDK.  We'll respond back once we have that ready!

**Comment by TingDaoK** [comment]
The new release with the fix is published, closing the issue. If you still have the issue with the latest version, please reopen the issue
