### ISSUE TITLE
Can't build samples (Unknown CMake command "aws_use_package")

### ISSUE THREAD

**Issue by Dystroxic** [aws/aws-iot-device-sdk-cpp-v2#147]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
Successfully built/installed the SDK as specified in the README, no errors. When I then go to one of the sample directories and run `cmake build .`, I get the error:

> Unknown CMake command "aws_use_package"

This seems like an issue, as I would think the samples should build straight out of the box if the installation is completed as specified. I'm relatively inexperienced with CMAKE though, so maybe I'm missing something? If I am, instructions for how to build the samples should be added to the documentation I think.

**Platform/OS/Device**
ARM (Raspberry Pi)

**SDK version number**
Example: v1.7.5

**To Reproduce (observed behavior)**
- Build/Install SDK as specified in README.md
- `cd ~/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/samples/mqtt/basic_pub_sub`
- `cmake build .`

**Expected behavior**
The sample should build.

**Logs/output**
```
CMake Error at CMakeLists.txt:30 (aws_use_package):
  Unknown CMake command "aws_use_package".
```

**Comment by rccarper** [comment]
Hello, it sounds like you may be missing the project submodules; you can check by looking to see if the aws-common-runtime folder is empty.  If that's the case, when cloning, you can include the --recursive flag, and it should grab all submodules.  Alternatively, after cloning, you should be to do the following from the root project directory: git submodule update --init --recursive

**Comment by Dystroxic** [comment]
Thanks for the tips, but I don't believe that's the issue. I did use `--recurse` for the submodules and the built libraries are all present at `~/sdk-cpp-workspace/lib/libaws-c-*`.

**Comment by rccarper** [comment]
I believe you are correct--I misunderstood your issue, sorry!  You shouldn't actually have to do any additional building for the samples.  If you were able to successfully build the project, you should see a samples folder in your build folder, which should contain subfolders that have the sample binaries.

**Comment by Dystroxic** [comment]
OK, that makes sense. But what's the process for integrating the IoT SDK into existing projects then? Is it possible to get some instructions/documentation for what's needed for that in CMAKE (minimal config)? I thought the samples would be a good starting point, but if they don't build... then I guess not.

**Comment by bretambrose** [comment]
When you build the samples you still need to tell cmake where to find the sdk installation, so you need to provide CMAKE_PREFIX_PATH (and might as well provider CMAKE_INSTALL_PREFIX just in case) when setting up the build.

Also, it looks like your source directory, installation directory, and build directory are all the same location which can lead to a lot of build problems depending on the setup.  I would suggest making sure all of these directories are distinct from one another:
  (1) make a separate build directory and run cmake from it, referencing the source directory
  (2) make an install directory and tell cmake to install output artifacts to it via -DCMAKE_INSTALL_PREFIX

**Comment by Dystroxic** [comment]
@bretambrose I followed the README.md file exactly, which sets up the following structure:

Source dir: `~/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2`
Build dir: `~/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build`
Install dir: `~/sdk-cpp-workspace`

So there are separate directories for each one. Having done that, I tried running this command while in one of the sample directories:
`cmake -DCMAKE_PREFIX_PATH="~/sdk-cpp-workspace"` (also tried the absolute path, `-DCMAKE_PREFIX_PATH="/home/pi/sdk-cpp-workspace"`)

To set the CMAKE_PREFIX_PATH as you recommend, but even that command spits out the same thing:
```
CMake Error at CMakeLists.txt:30 (aws_use_package):
  Unknown CMake command "aws_use_package".
```

**Comment by bretambrose** [comment]
Ok, I see what you mean now; I glossed over some of the initial points.  It would be worthwhile to include a separate sample that was stand-alone and consumed the SDK.

**Comment by Dystroxic** [comment]
@bretambrose That would be awesome. In the meantime, could you provide some quick pointers so I can get it working?

**Comment by Dystroxic** [comment]
What would also be super helpful is a standalone example that includes the `aws-iot-device-sdk-cpp-v2` project in an `extern` subdirectory and builds it, instead of assuming it's been installed separately.

**Comment by TingDaoK** [comment]
Stand-alone samples are provided at master now! Please refer to the [samples](https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/master/samples/stand-alone-samples) to integrate the IoT SDK into existing projects!
