### ISSUE TITLE
Need guidance regarding retries and thread-safety

### ISSUE THREAD

**Issue by adilevin** [aws/aws-iot-device-sdk-cpp-v2#151]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Windows 10

**Describe the question**
(I hope this is the right channel for this - it's my first time submitting an issue here...)

I need your guidance: I built an application, based on v.1.7.5 of the SDK, that publishes MQTT messages periodically, and also reconnects in case of a disconnect. It works well, but I'm not sure about the right way to do the auto-reconnect. I saw in the code that internally the SDK is trying to reconnect, but it didn't seem to work, and it seemed that I don't have a way to control the retry behavior - so I ended up disconnecting in OnInterrupted, and then try to connect again after 0.5 second. As experts - do you think this is okay? Would you recommend a different implementation?

And - can you help me find information about the thread-safety of MqttClient and MqttConnection?

Thanks!

**Comment by TingDaoK** [comment]
The SDK should be able to auto reconnect. The time between reconnect attempts will start at 1 sec and multiply by 2 until 128 secs. So, if the connection lost for a while, it will take upto 128 secs to reconnect. If the auto reconnect is not happening, it's probably a bug we need to fix. Please let us know more detail.

But yeah, your approach is correct. You can disconnect from the callback, and it will cancel the auto-reconnect task.

I am not sure what you mean about the information of thread-safety of MqttConnection and MqttClient. Our code should be thread-safe. So, if you check the dependency from [aws-c-mqtt](https://github.com/awslabs/aws-c-mqtt/blob/master/include/aws/mqtt/private/client_impl.h#L160), we have lock to protect the data that can be touched from multiple threads

**Comment by adilevin** [comment]
@TingDaoK - thanks a lot for the quick response! This is helpful. Let me explain my question about thread-safety: What I really want is to control the reconnect logic. If I can safely call methods of MqttConnection from concurrent threads, this means that I can have one thread monitoring the connection and reconnecting when needed - while other producer threads call Publish. This makes the producer threads simpler. What do you think about my approach?

And a related question: If I call MqttConnection::Publish, which thread will run the OnOperationCompleteHandler? Is this a thread managed by the EventLoopGroup?

**Comment by TingDaoK** [comment]
Yeah, it should be safe to call the function of MqttConnection from any thread (includes concurrent threads). Our SDK will ensure the thread-safety from the call. The message will be sent via the thread managed by EventLoopGroup.

Yes. The thread created by EventLoopGroup will invoke the OnOperationCompleteHandler once the Publish is completed.

**Comment by adilevin** [comment]
Perfect. Thanks!

Sent from my iPhone

On 1 Sep 2020, at 23:17, Dengke Tang <notifications@github.com> wrote:

﻿
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Yeah, it should be safe to call the function of MqttConnection from any thread (includes concurrent threads). Our SDK will ensure the thread-safety from the call. The message will be sent via the thread managed by EventLoopGroup.

Yes. The thread created by EventLoopGroup will invoke the OnOperationCompleteHandler once the Publish is completed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faws%2Faws-iot-device-sdk-cpp-v2%2Fissues%2F151%23issuecomment-685107858&data=02%7C01%7Calevin%40aligntech.com%7C373aec00d62f4d9a8b7c08d84eb40cca%7C9ac44c96980a481bae23d8f56b82c605%7C0%7C0%7C637345882513514637&sdata=UVIvI6%2BXiJ%2FORcBxR3BFiatkMvZxL2qjBJY4s3NJjlE%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABYAEYUAC5SIJFJXHHHA4X3SDVJFRANCNFSM4QRRXWYQ&data=02%7C01%7Calevin%40aligntech.com%7C373aec00d62f4d9a8b7c08d84eb40cca%7C9ac44c96980a481bae23d8f56b82c605%7C0%7C0%7C637345882513514637&sdata=MaSebc4bTyduHNwOQA%2BpFTI2nnFCZK91MSpdJCjPhH4%3D&reserved=0>.

This message and any attachments may contain information that is confidential, proprietary, and private and may be legally protected from disclosure. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete this message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.

**Comment by adilevin** [comment]
@TingDaoK - one more question: I saw that there's a logger inside the code. Is there any way for me, as a user of the library, to see those logs? I think this will give me better insight on what goes on under the hood.

Thanks!

**Comment by TingDaoK** [comment]
Sorry that our documentation is still not very clear. 
To enable the log, you will need to call [InitializeLogging](https://awslabs.github.io/aws-crt-cpp/classAws_1_1Crt_1_1ApiHandle.html#a43ddce38d8b357ff8dfb64838d544f0a). Our [integration test](https://github.com/awslabs/aws-crt-cpp/blob/master/bin/elasticurl_cpp/main.cpp#L255) is a good sample of how this function works.

**Comment by adilevin** [comment]
This is very helpful. Thanks a lot!
