### ISSUE TITLE
Build failing on ARM target

### ISSUE THREAD

**Issue by jckgore** [aws/aws-iot-device-sdk-cpp-v2#154]
Confirm by changing [ ] to [x] below:
- [ x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?

An ARM-based controller that runs a custom Linux.

**Describe the question**
I'm building directly on the controller and finally got through figuring out all the dependencies I needed. Now my actual build is failing. I'm seeing similar issues on both WSL/Ubuntu and on my ARM target. Attaching the output of the build from the ARM target. I don't have a ton of experience with debugging the build process of libraries like this. I'm just tying to get this built for my platform in order to access it in a higher level language like C# or LabVIEW.

[cRIO Build Errors.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5177350/cRIO.Build.Errors.txt)

**Comment by jmklix** [comment]
I was able to compile it successfully on a clean ubuntu install. What versions of g++ and gcc are you using? I would suggest making sure that they are up to date and retrying.

Also what ARM-based controller are you using?

**Comment by jckgore** [comment]
Well that confirms that it must be on my end. I'll try a clean clone and update everything in my WSL/Ubuntu environment.

The ARM controller is from National Instruments ([NI cRIO-9063](https://www.ni.com/en-us/support/model.crio-9063.html)) and runs their own spin of Linux. It's opkg based and their latest version has a pretty decent repository.

**Comment by jmklix** [comment]
Please let us know if you are still having issues with the build failing.

**Comment by jckgore** [comment]
I have the build completing, but with several warnings. The key to my issues were that the default installation of linux on the device had no symlink from `/usr/bin/g++` to `/usr/bin/arm-nilrt-linux-gnueabi-g++` as part of the opkg for g++. I was mistakenly trying to use gcc as my g++ compiler which didn't completely fail...

My issues on my WSL testing must have been related to not having everything cleaned properly. I still get a few warnings on WSL during build, but it completes fine.

With all the being said, I've started exploring the API for this library and it seems just too complicated to wrap into another language. I'm a C# developer first and foremost, and the 550 lines of C++ code for the basic pub sub example using promises and other C++ idioms is a lot to parse. I'm hoping I can build the embedded C version as a shared library and use it's simpler API to get what I need done.

Thanks for testing and support.

**Comment by graebm** [comment]
If you're looking to use a higher level language, we have also have SDKs for [Python](https://github.com/aws/aws-iot-device-sdk-python-v2) and [Java](https://github.com/aws/aws-iot-device-sdk-java-v2). These use the same underlying C codebase, wrapped into another language, but we've already done the wrapping for you ;)

**Comment by jckgore** [comment]
Yes, but unfortunately not for C#. I've considered contributing a C# wrapper, actually. Are the Python/Java wrappers built off of the Embedded C SDK or the C++ SDK?

You just forced me to check an assumption though. Historically, LabVIEW (as a language) has only been interoperable with C/C++ (Linux/Windows) and C# (Windows only). It looks like they added Python support in 2018, but it's unfortunately not supported on their Linux real-time targets. Perhaps in the future.

In the meantime it looks like compiling the embedded C client SDK as a shared library and then accessing it from LabVIEW is my best bet.
