### ISSUE TITLE
How can I use shared library in g++?

### ISSUE THREAD

**Issue by surygeng** [aws/aws-iot-device-sdk-cpp-v2#158]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Debian

**Describe the question**
The libraries are installed in folder /usr/local using these commands:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_DEPS=ON -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2
sudo cmake --build . --target install
```
I call the shared libraries to compile my example project using `g++ -std=c++11 -o main main.cpp -laws-crt-cpp` but get the following errors:
```
/usr/bin/ld: //usr/local/lib/libaws-crt-cpp.so: undefined reference to symbol 'aws_mem_acquire'
/usr/bin/ld: //usr/local/lib/libaws-c-common.so.0unstable: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Can I use these libraries in this way? 
Thanks for any suggestions.

**Comment by JonathanHenson** [comment]
Technically you can use it by manually invoking g++ but it will be a chore. I recommend you use cmake with find_package and target_link_libraries and it will handle all of this for you. If you want to do it manually you’ll need to handle the linker and compiler arguments manually.
