### ISSUE TITLE
macOS error errSecInteractionNotAllowed when trying open a connection with a private key

### ISSUE THREAD

**Issue by EeroKurimo** [aws/aws-iot-device-sdk-cpp-v2#162]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
macOS Darwin Kernel Version 19.5.0

**Describe the question**

We're having some problems with using private keys on macOS. We're calling ``MqttClient::NewConnection(<opts>, Io::TlsContext(tls_ctx_opt, Io::TlsMode::CLIENT))`` like this

```
auto tls_ctx_opt = Io::TlsContextOptions::InitClientWithMtls(
	ByteCursorFromCString(certificates.cert.c_str()),
	ByteCursorFromCString(certificates.private_key.c_str())
);
uint16_t port = 8883;
if (Io::TlsContextOptions::IsAlpnSupported()) {
	port = 443;
	if (!tls_ctx_opt.SetAlpnList("x-amzn-mqtt-ca")) {


Io::SocketOptions sock_opt;
sock_opt.SetConnectTimeoutMs(3000);
auto connection = mqttClient.NewConnection(
	endpoint.c_str(), //This is "<server>-ats.iot.eu-west-1.amazonaws.com"
	port,
	sock_opt,
	Io::TlsContext(tls_ctx_opt, Io::TlsMode::CLIENT)
);
```

The contents of the other options (with keys omitted) look like this:

```
(uint16_t) port = 443

(Aws::Crt::Io::SocketOptions) sock_opt = {
  options = {
    type = AWS_SOCKET_STREAM
    domain = AWS_SOCKET_IPV4
    connect_timeout_ms = 3000
    keep_alive_interval_sec = 0
    keep_alive_timeout_sec = 0
    keep_alive_max_failed_probes = 0
    keepalive = false
  }
}

(Aws::Crt::Io::TlsContextOptions) tls_ctx_opt = {
  m_options = {
    allocator = 0x0000000103c41248
    minimum_tls_version = AWS_IO_TLS_VER_SYS_DEFAULTS
    cipher_pref = AWS_IO_TLS_CIPHER_PREF_SYSTEM_DEFAULT
    ca_file = {
      len = 1188
      buffer = 0x000061a000003680 "-----BEGIN CERTIFICATE-----\n<REMOVED>"...
      capacity = 1189
      allocator = 0x0000000103c41248
    }
    ca_path = 0x0000000000000000
    alpn_list = 0x0000604000001e50
    certificate = {
      len = 1314
      buffer = 0x000061a000003080 "-----BEGIN CERTIFICATE-----\n<REMOVED>"...
      capacity = 1315
      allocator = 0x0000000103c41248
    }
    private_key = {
      len = 1678
      buffer = 0x000061c000002080 "-----BEGIN RSA PRIVATE KEY-----\n<REMOVED>"...
      capacity = 1679
      allocator = 0x0000000103c41248
    }
    pkcs12 = {
      len = 0
      buffer = 0x0000000000000000
      capacity = 0
      allocator = 0x0000000000000000
    }
    pkcs12_password = {
      len = 0
      buffer = 0x0000000000000000
      capacity = 0
      allocator = 0x0000000000000000
    }
    max_fragment_size = 16384
    verify_peer = true
  }
  m_isInit = true
}
```

However after this the initialization fails in ``aws_import_public_and_private_keys_to_identity`` of ``darwin_pki_utils.c`` (https://github.com/awslabs/aws-c-io/blob/ca96a75aecca05b8c25f0464a303b06f5a5a51af/source/darwin/darwin_pki_utils.c#L58) when we always get the error ``-25308 (errSecInteractionNotAllowed)`` from ``SecItemImport()`` which is trying to import our private key.

We'd hope to run as a non-root account, but even when running the same code as root, the error still persists. Are we doing something obviously wrong here, or are we missing some steps needed to make MQTT connections from macOS using private key authentication?

**Comment by rccarper** [comment]
I'm still looking into this, and this might not be the issue, but I'm wondering if the application might be trying to access the keychain for finding an already stored private key, but fails because it doesn't have permission to.

**Comment by rccarper** [comment]
Would it be possible to provide a log?  This should help us double check that there isn't an earlier failure.

**Comment by EeroKurimo** [comment]
The issue was indeed with keychain access! The account I was testing with was apparently created in a somewhat abnormal manner, where the `/Users/abnormal_user/` had been created manually and had no `~/Library/` dir for the keychains! With another account that was created properly, the connection seems to work as intended after ``security unlock-keychain`` has been called.

I think this issue can be closed, as it was matter of a misconfigured keychain at my end.
