### ISSUE TITLE
CMake Command must run twice to use aws_find_package correctly in other project

### ISSUE THREAD

**Issue by hartmir** [aws/aws-iot-device-sdk-cpp-v2#164]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
Running the command `cmake` on a project with this repo cloned into a subdirectory requires the cmake configure command to be run twice before being successful.

**Platform/OS/Device**
Ubuntu 18.04

**SDK version number**
master

**To Reproduce (observed behavior)**

Execute the following to set up the repo:
``` sh
mkdir -p test-project/extern
cd test-project/extern
git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
```

Edit `test-project/CMakeLists.txt` to contain the following:
```cmake
cmake_minimum_required(VERSION 3.2)
project(test-project)
set(BUILD_DEPS ON)
add_subdirectory(extern/aws-iot-device-sdk-cpp-v2)
```

Run the commands as follows:
``` sh
cd test-project
mkdir build
cd build
cmake ..  # Fails to find aws_use_package
cmake ..  # This time, succeeds and configures correctly
```

**Expected behavior**
The first `cmake` command should finish successfully.

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
➜  user@blah build cmake ..             
CMake Error at extern/aws-iot-device-sdk-cpp-v2/CMakeLists.txt:53 (include):
  include could not find load file:

    AwsFindPackage


CMake Error at extern/aws-iot-device-sdk-cpp-v2/jobs/CMakeLists.txt:94 (aws_use_package):
  Unknown CMake command "aws_use_package".


-- Configuring incomplete, errors occurred!
See also "/user/user/tmp/test-project/build/CMakeFiles/CMakeOutput.log".
➜  user@blah build cmake ..
-- AWS CRT C++ v0.10.5
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Success
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Building SIMD base64 decoder
-- Packaging currently only supported on Fedora.
-- Attempting to try_compile PQ ASM
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- PQ ASM try_compile succeeded - using optimized x86_64 assembly for PQ crypto
-- Attempting to try_compile PQ ASM with ADX support
-- PQ ASM try_compile with ADX support succeeded - using ASM code with ADX instructions
-- Performing Test S2N_HAVE_EXECINFO
-- Performing Test S2N_HAVE_EXECINFO - Success
-- Found LibCrypto: /usr/lib/x86_64-linux-gnu/libcrypto.a  
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.a
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.a
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/tmp/test-project/build
```

**Additional context**
I found this error as I was trying to write documentation for #147.

**Comment by TingDaoK** [comment]
Sorry for a late response.
Instead of `add_subdirectory(extern/aws-iot-device-sdk-cpp-v2)`, you can use `find_package()` and link them with your program. Please refer to the latest CMakefile of our samples https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/master/samples/shadow/shadow_sync/CMakeLists.txt#L21-L26. Our samples are all stand-alone now, can provide useful guidance about how to use our SDK as dependency.

**Comment by hartmir** [comment]
Hi, I think the point of this is that it's not the recommended method to build. In my project, I don't want to be installing the libraries because I need to export the shared objects as outputs of the build; I need to build all the libraries at the same time. That is the purpose of using `add_subdirectory`; all of the artifacts end up in the same place and can be exported easily.

I should also note that the referenced issue is not relevant. I meant to link to #135

**Comment by TingDaoK** [comment]
I see what do you mean now. As I tested following the steps you provided, `set(BUILD_DEPS ON)` this line does not work. So, the following commands work for me.
```
cd test-project
mkdir build
cd build
cmake -DBUILD_DEPS=ON ..
```

**Comment by hartmir** [comment]
That's ideal - consider this issue dealt with. I'll try to find time soon to submit a PR to document this, it that would be welcome.
