### ISSUE TITLE
Windows builds fail if base directory is longer than 53 characters

### ISSUE THREAD

**Issue by EeroKurimo** [aws/aws-iot-device-sdk-cpp-v2#165]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
If you try build the release version of the sdk on Windows in a base directory longer than 53 characters, the build will fail because MSBuild doesn't support paths longer than 260 characters regardless of the `LongPathsEnabled` registry setting, giving the error:

```
FileTracker : error FTK1011: could not create the new file tracking log file: C:\data\aws-sdk-cpp-workspace_123456789_123456789_123\aws-iot-device-sdk-cpp-v2-build\aws-common-runtime\aws-crt-cpp\aws-common-runtime\aws-c-event-stream\bin\aws-c-event-stream-write-test-casedir\RelWithDebInfo\aws-c-ev.0D0EAE0E.tlog\link-cvtres.write.1.tlog. The system cannot find the path specified. [C:\data\aws-sdk-cpp-workspace_123456789_123456789_123\aws-iot-device-sdk-cpp-v2-build\aws-common-runtime\aws-crt-cpp\aws-common-runtime\aws-c-event-stream\bin\aws-c-event-stream-write-test-case.vcxproj]
```

This is slightly related to https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/157 which we worked around by doing the checkout elsewhere, but in this case with build directories it is often not that easy in e.g. CI build environments. If the base directory is even longer, say 60 characters, there's even more build errors, though all appear to be coming from `aws-c-event-stream` builds.

To avoid a lot of future hassle for people building this on Windows, possible suggestions to allow longer base directory names could be:

- Clone `aws-crt-cpp` directly under `aws-iot-device-sdk-cpp-v2` without the intermediate `aws-common-runtime` directory.
- Under `aws-crt-cpp` clone the dependencies under a shorter dir `aws-crt` instead of `aws-common-runtime`.
- Under `aws-c-event-stream` avoid repeating the repo name, e.g. use test dir `write-test-casedir` instead of `aws-c-event-stream-write-test-casedir`.

**Platform/OS/Device**
Windows 10

**SDK version number**
Example: v1.8.2 

**To Reproduce (observed behavior)**

```
mkdir C:\data\aws-sdk-cpp-workspace_123456789_123456789_123
cd C:\data\aws-sdk-cpp-workspace_123456789_123456789_123
git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
mkdir aws-iot-device-sdk-cpp-v2-build
cd aws-iot-device-sdk-cpp-v2-build
cmake -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo ../aws-iot-device-sdk-cpp-v2
cmake --build . --config RelWithDebInfo
```

**Expected behavior**
Build succeeds.

**Logs/output**
```
Building Custom Rule C:/data/aws-sdk-cpp-workspace_123456789_123456789_123/aws-iot-device-sdk-cpp-v2/aws-common-runti me/aws-crt-cpp/aws-common-runtime/aws-c-event-stream/bin/CMakeLists.txt
event_stream_write_test_case.c
FileTracker : error FTK1011: could not create the new file tracking log file: C:\data\aws-sdk-cpp-workspace_123456789_123456789_123\aws-iot-device-sdk-cpp-v2-build\aws-common-runtime\aws-crt-cpp\aws-common-runtime\aws-c-event-stream\bin\aws-c-event-stream-write-test-case.dir\RelWithDebInfo\aws-c-ev.0D0EAE0E.tlog\link-cvtres.write.1.tlog. The system cannot find the path specified. [C:\data\aws-sdk-cpp-workspace_123456789_123456789_123\aws-iot-device-sdk-cpp-v2-build\aws-common-runtime\aws-crt-cpp\aws-common-runtime\aws-c-event-stream\bin\aws-c-event-stream-write-test-case.vcxproj]
```

**Comment by graebm** [comment]
We've shortened the submodule directories: "aws-common-runtime/" -> "crt/". That saves 30 characters, since it occurs twice in the longest paths.

These changes are currently in `master`, tagged as [v1.8.3](https://github.com/aws/aws-iot-device-sdk-cpp-v2/releases/tag/v1.8.3)

We've also added the following warning to the [README](https://github.com/aws/aws-iot-device-sdk-cpp-v2#building-on-windows):

> Due to maximum path length limitations in the Windows API, we recommend [enabling long paths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later) on your development machines, or cloning to a short path like: `C:\dev\iotsdk`

**Comment by EeroKurimo** [comment]
Thanks a lot for making the path shorter! It really helped.

As a comment about the README addition, I'm not sure if the new guidance about enabling long paths helps, as I don't think that msbuild and its components have been built with the `longPathAware` element yet as required to opt-in in https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later.

It also won't help with git checkout that was discussed in https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/157, as the limit `MAX_PATH - 40` is hardcoded into the git executable.

It might be more helpful just to instruct developers to use a short path on Windows.

**Comment by graebm** [comment]
Reopening issue.

We'll take further action to shorten paths. I got my hands on a windows machine to test with and you're right that it's not easy to work around

**Comment by bretambrose** [comment]
I think we've managed to shorten these paths sufficiently for now.
