### ISSUE TITLE
I'm getting AWS_ERROR_MQTT_UNEXPECTED_HANGUP currently.

### ISSUE THREAD

**Issue by Radagan** [aws/aws-iot-device-sdk-cpp-v2#167]
I'm getting this error currently.

`
~/Development/libs/aws-iot-device-sdk-cpp-v2-build/samples/mqtt/basic_pub_sub/basic-pub-sub --endpoint a3rvmixc811azv-ats.iot.us-west-2.amazonaws.com --ca_file root-CA.crt --cert cert.pem.crt --key private.key --topic test

Connecting...
Connection failed with error libaws-c-mqtt: AWS_ERROR_MQTT_UNEXPECTED_HANGUP, The connection was closed unexpectedly.
`

As this is just a test account, my policy is very permissive.
`
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:*",
      "Resource": "arn:aws:iot:us-west-2:424091364653:topic/test"
    }
  ]
}
`

I'm very new to AWS IoT Core. Any help would be very appreciated.

_Originally posted by @Radagan in https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/137#issuecomment-700901663_

**Comment by jmklix** [comment]
Try using --root-ca instead of --ca_file. The arguments are currently not consistent across the iot sdks.

**Comment by Radagan** [comment]
Thank you for the quick response. I tried --root-ca, but receive the same error. I also tried removing it with the same error as well.

**Comment by Radagan** [comment]
I'm not sure why my first policy file didn't work, but adding the suggested example policy below to the cert got me past this error, and I was able to publish a test message.  

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Publish",
        "iot:Receive"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:424091364653:topic/test/topic"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:424091364653:topicfilter/test/topic"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": [
        "arn:aws:iot:us-west-2:424091364653:client/test-*"
      ]
    }
  ]
}
```
