### ISSUE TITLE
Missing documentation for the SDK

### ISSUE THREAD

**Issue by massi-ang** [aws/aws-iot-device-sdk-cpp-v2#169]
**Is your feature request related to a problem? Please describe.**
The python and javascript SDKs have an accompanying documentation which is missing from the CPP SDK

**Describe the solution you'd like**
Documentation for the SDK similar to the one available for the other languages and the CRT https://awslabs.github.io/aws-crt-cpp/

**Describe alternatives you've considered**

**Additional context**
Ensure consistency across SDKs

**Comment by jmklix** [comment]
This is something that we want to add, but I can't give timeline for when it would be added.
