### ISSUE TITLE
Problem linking with libs using eclipse

### ISSUE THREAD

**Issue by identisoft-alaric** [aws/aws-iot-device-sdk-cpp-v2#174]
Confirm by changing [ ] to [x] below:
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Linux Mint 20

**Describe the question**
I have build the sdk as per the instructions (https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/master/README.md) and am trying to use the static libs (libaws-crt-cpp.a, etc) in a test application using eclipse ide. It compiles fine however when it come to linking I get many "unresolved" errors i.e 

"/usr/bin/ld: /home/build/eclipse-workspace/awsiot-test/sdk-cpp-workspace/lib/libaws-crt-cpp.a(Types.cpp.o): in function `Aws::Crt::Base64Decode(std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Crt::StlAllocator<char> > const&)':
/home/build/eclipse-workspace/awsiot-test/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/source/Types.cpp:57: undefined reference to `aws_base64_compute_decoded_len'"

Here is the sample c++ project created in eclipse - https://drive.google.com/file/d/1_fgA5gx9jYuIB4Z_jhaRA2UKLv4s58wQ/view?usp=sharing

I may have done something really stupid so forgive me but any help would be greatly appreciated.

Thanks.
Alaric

**Comment by jmklix** [comment]
Have you been able to get the [basic_pub_sub](https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/master/samples/mqtt/basic_pub_sub) working while using eclipse?

**Comment by identisoft-alaric** [comment]
Hi jmklix,
Thanks for the reply, unfortunately we haven't yet.

**Comment by jmklix** [comment]
You should be able to get the basic_pub_sub working with just the command line and I recommend that you do that first. As far as ide's go eclipse is not the best. Maybe try VSCode?

**Comment by identisoft-alaric** [comment]
OK, thought I'd try AWS libs but will go back to using the mosquitto c libs which we have used in previous projects.
Thanx.
