### ISSUE TITLE
HTTPS proxy certificate specification

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#176]
Hi, we are using `CredentialsProviderX509Config` with `ProxyOptions` set with proxy host and port. I would like to know how to specify HTTPS proxy certificate? I'm already using `MqttClientConnectionConfigBuilder.WithCertificateAuthority` for verifying server certificate. If I add the proxy certificate to the cacert file I pass to `WithCertificateAuthority`, will it work to verity the proxy?

CURL for example provides CURLOPT_PROXY_CAINFO option for specifying proxy certificate, which is in addition to the server certificate specified with CURLOPT_CAINFO.

Can `WithCertificateAuthority` be provided with certificate file that contains both server certificate and proxy certificate? or should the proxy certificate specified in another way?

**Comment by elad-ep** [comment]
I don't see that proxy `TlsConnectionOptions` currently exposes a way to set proxy certificate such as `WithCertificateAuthority`, right? is it because HTTPS proxy secure connection is not currently supported? 
can we please ask for this support?

**Comment by bretambrose** [comment]
It looks like you can create a TlsContextOptions instance and call OverrideDefaultTrustStore.  Then create a TlsContext(options) and call NewConnectionOptions to create something you can stick in the proxy config.  Not the most intuitive flow admittedly.

**Comment by elad-ep** [comment]
I see - and that certificate will be used for verification against the HTTPS proxy? or you say that it's not supported yet?

**Comment by bretambrose** [comment]
It should be used as soon as the referenced bug is fixed in the http library.  

I can look into this when I get some free cycles, but things are a little busy right now unfortunately.  The biggest issue is getting time for test setup and debugging.

**Comment by elad-ep** [comment]
OK, can you please prioritize it? if it can be supported sometime soon it will be great... thanks...

**Comment by bretambrose** [comment]
So I spent a few hours looking into this today and I keep running into the brick wall of not being able to find an easily installable, configurable proxy that accepts tls connections.  So far, both burp and squid only appear to support CA configuration based on establishing MITM visibility on https connections to remote hosts.  I cannot find any configuration that allows me to make the initial proxy TCP connection over TLS (client hello is never replied to in all cases).

Do you have any advice here?

Just to make sure, I want to verify the use case here that you want "double" tls support: an independent tls session from client <-> proxy, and an independent tls session from client <-> server via the proxy.  It would seem like the main difference is that the initial CONNECT request would not be visible.

**Comment by elad-ep** [comment]
I'm working with enterprise proxy that supports various protocol, including HTTPS. not sure about easily configurable one... the use case is communication with HTTPS proxy that has its own certificate (CURLOPT_PROXY_CAINFO in CURL language). it looks to me we are talking about the same use case...

**Comment by elad-ep** [comment]
you can also use squid for that:
https://elatov.github.io/2019/01/using-squid-to-proxy-ssl-sites/

see the following in the config:
```
http_port 3128 ssl-bump \
  cert=/etc/squid/certs/squid-ca-cert-key.pem \
  generate-host-certificates=on dynamic_cert_mem_cache_size=16MB
```

**Comment by bretambrose** [comment]
That configuration is for dynamic cert generation and allowing a mitm decoding of the end-to-end tls stream.

**Comment by elad-ep** [comment]
I see - I thought this is for communicating tls with the proxy... in any case, if you implement the secure connection with the proxy we could try search/setup for such proxy configuration in order to test it...

**Comment by elad-ep** [comment]
Hi, I have another question in the same matter - is there an option for the SDK to work with the native operating system certificates store (windows and mac), so I don't need to specifically supply the proxy CA, and also skip `MqttClientConnectionConfigBuilder.WithCertificateAuthority`? (as the certificates are already in the OS certificate store)

**Comment by elad-ep** [comment]
@bretambrose can you please refer to my last 2 question: 
1. can you please add HTTPS proxy support?
2. does the SDK have an option to work with the OS certificate store (for both the proxy CA and server validation CA)?

**Comment by JonathanHenson** [comment]
If you don’t set a CA, the OS cert store is used by default.

**Comment by elad-ep** [comment]
thanks, I tested and it works fine with the OS cert store. I have another request please:

can you please provide an official flag similar to CURL's [CURLSSLOPT_REVOKE_BEST_EFFORT](https://curl.haxx.se/libcurl/c/CURLOPT_SSL_OPTIONS.html)? when using this flag CURL uses the `SCH_CRED_IGNORE_NO_REVOCATION_CHECK` Win API flag, so the connection is not failing on certificates without CRL.

This is useful for connection though MITM proxies, where the proxy certificate is installed on the machine, but usually doesn't have CRL. without this flag connection though the proxy will fail due to certificate revocation check error.

due to customers with such proxy configuration I added the `SCH_CRED_IGNORE_NO_REVOCATION_CHECK` manually in the SDK source (but we would like an official flag for it, so we don't need to change the source).

my change in line 1860 in secure_channel_tls_handler.c:

```
else if (is_client_mode) {
        secure_channel_ctx->credentials.dwFlags |=
            **SCH_CRED_IGNORE_NO_REVOCATION_CHECK** | SCH_CRED_REVOCATION_CHECK_CHAIN | SCH_CRED_IGNORE_REVOCATION_OFFLINE;
    }
```

thanks...

**Comment by elad-ep** [comment]
Hi, can you please refer to the request in the last comment?

**Comment by elad-ep** [comment]
Hi, please help. those issue are high importance and affect our customers. how can we get expedited support? should we open tickets to Amazon AWS support?

**Comment by bretambrose** [comment]
Given current team workload, that would be ideal.

**Comment by elad-ep** [comment]
opened AWS case. case ID: 7653457801

**Comment by bretambrose** [comment]
v1.10.2 was just released and contains nested tls support.

Note that sometime in the near future we're going to be changing the proxy API a bit to polymorphically support more authentication methods as well as allow explicit (rather than implict based on tls/non-tls) control of the proxy connection type (forwarding, tunneling, etc...) as well as new proxy connection types (socks5, etc...)  We will try and keep these changes backwards compatible with the existing API, but there may be some ugliness as a result (duplicate controls for basic auth, for example).
