### ISSUE TITLE
IoT throttling

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#179]
Hi, 
we encountered in cases where IoT messages are discarded by the cloud side due to throttling error. apparently in specific cases clients pass the [throttling limits](https://docs.aws.amazon.com/general/latest/gr/iot-core.html) for cloud inbound messages.

Is it possible with the SDK to control the messages sending rate? i.e. setting max messages per second, and if this limit is passed the SDK should wait with the extra messages (instead of sending immediately) in order to control the sending rate... I didn't find any SDK setting for that. is it possible?

**Comment by elad-ep** [comment]
Hi, any answer regarding this?.... thanks

**Comment by bretambrose** [comment]
The SDK does not contain support for any kind of higher-level rate limiting.
