### ISSUE TITLE
I am cross compiling latest version of aws-iot-device-sdk-cpp-v2 for MIPS,but I don't know how to change the .cmake file or Makefile,please give me some suggestion

### ISSUE THREAD

**Issue by walt-2020** [aws/aws-iot-device-sdk-cpp-v2#187]
**Known Issue**
I am cross compiling latest version of aws-iot-device-sdk-cpp-v2 for MIPS

**Platform/OS/Device**
MIPS/Linux/AR9531

**Describe the question**
I don't know how to change the .cmake file or Makefile,please give me some suggestion

**Comment by Radagan** [comment]
Hi Walt, 

I feel your pain. I was recently in your shoes trying to compile for armhf. I was able to pass the cmake file for my toolchain to cmake as:

```
-DCMAKE_TOOLCHAIN_FILE=/opt/arm-buildroot-linux-gnueabihf_sdk-buildroot/share/buildroot/toolchainfile.cmake
```

Unfortunately, I found the aws-iot-device-... dependencies unstable and had many compiler warnings for armhf. It was also difficult to setup my project outside of aws-iot-device-...'s own CMake project, thought that has at least been addressed now if not documented. 

I was also unable to use C++17, which is a requirement for another library in my project, so I switched to:

https://github.com/redboltz/mqtt_cpp

This is a great option if you want pure MQTT and C++17. It is based on Boost.ASIO. 

Hope that helps!

**Comment by walt-2020** [comment]
I cross compile the aws-iot-device-sdk-cpp-v2,there is a error exist below,how to resolve it?

[w1967@ubuntu aws-iot-device-sdk-cpp-v2-build-mips]$ sudo cmake -DCMAKE_INSTALL_PREFIX=/home/w1967/Downloads/sdk-cpp-mips-workspace/ -DBUILD_DEPS=ON -DBUILD_SHARED_LIBS=ON  -DCMAKE_TOOLCHAIN_FILE=/home/w1967/Downloads/sdk-cpp-mips-workspace/ToolchainFile.cmake ../aws-iot-device-sdk-cpp-v2/
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc
-- Check for working C compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-g++
-- Check for working CXX compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.11.0
-- CMake 3.16.6
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Failed
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Attempting to try_compile PQ ASM
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc
-- PQ ASM try_compile failed - using generic C code for PQ crypto
-- Performing Test S2N_HAVE_EXECINFO
-- Performing Test S2N_HAVE_EXECINFO - Failed
-- Found LibCrypto: /usr/lib/x86_64-linux-gnu/libcrypto.so  
-- LibCrypto Include Dir: /usr/include
-- LibCrypto Shared Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.so
-- LibCrypto Static Lib:  /usr/lib/x86_64-linux-gnu/libcrypto.a
CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LibCrypto (missing: LibCrypto_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  crt/aws-crt-cpp/crt/aws-c-io/cmake/modules/FindLibCrypto.cmake:61 (find_package_handle_standard_args)
  crt/aws-crt-cpp/crt/aws-c-io/CMakeLists.txt:167 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by walt-2020** [comment]
I compile the SDK on my ubuntu is fine, but I cross compile SDK failed,can you help me?

problem: -- Performing Test S2N_HAVE_EXECINFO - Failed 

The command is :sudo cmake -DCMAKE_INSTALL_PREFIX=/home/w1967/Downloads/sdk-cpp-mips-workspace/ -DBUILD_DEPS=ON -DBUILD_SHARED_LIBS=ON S2N_NO_PQ_ASM=ON -DCMAKE_TOOLCHAIN_FILE=/home/w1967/Downloads/sdk-cpp-mips-workspace/ToolchainFile.cmake ../aws-iot-device-sdk-cpp-v2/

-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc
-- Check for working C compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-g++
-- Check for working CXX compiler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.11.0
-- CMake 3.16.6
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Failed
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Attempting to try_compile PQ ASM
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc
-- PQ ASM try_compile failed - using generic C code for PQ crypto
-- Performing Test S2N_HAVE_EXECINFO
-- Performing Test S2N_HAVE_EXECINFO - Failed
-- Found LibCrypto: /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib64/libcrypto.so  
-- LibCrypto Include Dir: /usr/local
-- LibCrypto Shared Lib:  /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib64/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib64/libcrypto.a
-- LibCrypto Include Dir: /usr/local
-- LibCrypto Shared Lib:  /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib64/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib64/libcrypto.a
-- LibCrypto Include Dir: /usr/local
-- LibCrypto Shared Lib:  /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib64/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/mips/toolchain-mips_r2_gcc-4.6-linaro_uClibc-0.9.33.2/lib64/libcrypto.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/w1967/Downloads/sdk-cpp-mips-workspace/aws-iot-device-sdk-cpp-v2-build-mips

**Comment by Radagan** [comment]
I noticed that you are using a pretty old version of GCC. Some C++11 features were not implemented until 4.8. Perhaps that is part of the problem? This link can help insure that your compiler supports all the language features that you need:

https://en.cppreference.com/w/cpp/compiler_support

**Comment by bretambrose** [comment]
You will need gcc 4.9 minimum for the C++ SDK.  Beyond that, what you've included in the issue does not show any errors.  Feature detection failures aren't build problems.

**Comment by jmklix** [comment]
@walt-2020 have you successfully cross compiled after updating your gcc version? or are you still having problems?
