### ISSUE TITLE
JITP not working on Windows?

### ISSUE THREAD

**Issue by adilevin** [aws/aws-iot-device-sdk-cpp-v2#190]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Windows 10

**Describe the question**
I'm failing to use JITP (this may be related to [a similar issue on MAC](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/108)): I confirmed using mosquitto_pub, that JITP works if I concatenate the Client Cert and CA Cert (that was used to sign the client cert) in the Cert file I give when publishing a message - as in this example: [device_cert_with_ca.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5505247/device_cert_with_ca.txt). But when I try to do the same with the cpp sdk, the connection always fails. It seems that it expects me to only send the client Cert without the CA concatenated (which works well for registered certificates, but it doesn't trigger JITP). I I'm right about this, what is the proper way to send the CA cert along with the client cert in the cpp sdk?

Thanks!

**Comment by DovAmir** [comment]
+1

**Comment by jmklix** [comment]
Have you taken a look at this branch with detailed instructions for [fleet provisioning](https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/fleet-provisioning-docs/samples#fleet-provisioning-detailed-instructions)?

**Comment by adilevin** [comment]
Thanks for the useful reference, @jmklix. I think this is showing how to use fleet provisioning, but what I was really hoping to do is use JITP (https://docs.aws.amazon.com/iot/latest/developerguide/jit-provisioning.html), which works well if I use mosquitto_pub, but not through the CPP SDK, and it's because the SDK doesn't let me concatenate the device cert with its CA, as required for JITP... Any idea how I can accomplish this?

**Comment by jmklix** [comment]
Can you include the step you used to make Client and CA certs? Also can you include a log from when you try to connect with the concatenated cert? To enable logging use the following:
```
ApiHandle::InitializeLogging(...)
```
*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Comment by jmklix** [comment]
There has been a recent patch fixing a error with cert generation. Can you try updating to the latest version and generate a new [jitp device and ca cert pair](https://github.com/aws-samples/aws-iot-device-management-workshop/blob/master/AWS_IoT_Device_Management_Workshop.md#jitp---just-in-time-provisioning)? Also how are you using the concatenated deviceandcacert with the sdk?

**Comment by adilevin** [comment]
@jmklix - thanks a lot for your help. I apologize for not answering earlier - but since we've decided to not use JITP for now, I expect that it will be a while until I get back to this issue... Should we close the issue then?
