### ISSUE TITLE
Does this sdk support arm64?

### ISSUE THREAD

**Issue by kjnoh77** [aws/aws-iot-device-sdk-cpp-v2#191]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Tizen/Linux/arm64

**Describe the question**

I wonder that this SDK can be built for target device of arm64.
I have solved a bunch of build problems fixing our CMakeList but following problem still remains on our build environment.

[   27s] [ 57%] Building C object aws-iot-device-sdk-cpp-v2/aws-common-runtime/aws-crt-cpp/aws-common-runtime/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/compression.c.o
[   28s] [ 57%] Linking C shared library libaws-checksums.so
[   28s] [ 57%] Linking C shared library libaws-c-compression.so
[   28s] [ 57%] Linking C shared library libaws-c-cal.so
[   28s] [ 57%] Built target aws-c-compression
[   28s] {standard input}: Assembler messages:
[   28s] {standard input}:1658: Error: selected processor does not support `crc32b r2,r2,r3' in Thumb mode
[   28s] {standard input}:1721: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:1738: Error: selected processor does not support `crc32w fp,r2,r1' in Thumb mode
[   28s] {standard input}:1754: Error: selected processor does not support `crc32w r3,fp,r3' in Thumb mode
[   28s] {standard input}:1770: Error: selected processor does not support `crc32w r3,r3,r10' in Thumb mode
[   28s] {standard input}:1787: Error: selected processor does not support `crc32w r3,r3,r9' in Thumb mode
[   28s] {standard input}:1803: Error: selected processor does not support `crc32w r3,r3,r2' in Thumb mode
[   28s] {standard input}:1818: Error: selected processor does not support `crc32w r3,r3,r8' in Thumb mode
[   28s] {standard input}:1834: Error: selected processor does not support `crc32w r3,r3,r1' in Thumb mode
[   28s] {standard input}:1851: Error: selected processor does not support `crc32w r3,r3,r6' in Thumb mode
[   28s] {standard input}:1869: Error: selected processor does not support `crc32w r3,r3,r10' in Thumb mode
[   28s] {standard input}:1882: Error: selected processor does not support `crc32w r3,r3,r9' in Thumb mode
[   28s] {standard input}:1888: Error: selected processor does not support `crc32w r2,r3,r2' in Thumb mode
[   28s] {standard input}:1898: Error: selected processor does not support `crc32w r2,r2,r8' in Thumb mode
[   28s] {standard input}:1904: Error: selected processor does not support `crc32w r2,r2,r1' in Thumb mode
[   28s] {standard input}:1914: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:1920: Error: selected processor does not support `crc32w r2,r2,r7' in Thumb mode
[   28s] {standard input}:1956: Error: selected processor does not support `crc32w r2,r2,r5' in Thumb mode
[   28s] {standard input}:1962: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:1987: Error: selected processor does not support `crc32w r2,r2,r5' in Thumb mode
[   28s] {standard input}:1993: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:2018: Error: selected processor does not support `crc32w r2,r2,r5' in Thumb mode
[   28s] {standard input}:2024: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:2049: Error: selected processor does not support `crc32w r2,r2,r5' in Thumb mode
[   28s] {standard input}:2055: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:2080: Error: selected processor does not support `crc32w r2,r2,r5' in Thumb mode
[   28s] {standard input}:2086: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:2111: Error: selected processor does not support `crc32w r2,r2,r5' in Thumb mode
[   28s] {standard input}:2117: Error: selected processor does not support `crc32w r2,r2,r6' in Thumb mode
[   28s] {standard input}:2140: Error: selected processor does not support `crc32w r2,r2,r5' in Thumb mode
[   28s] {standard input}:2146: Error: selected processor does not support `crc32w r2,r2,r1' in Thumb mode
[   28s] {standard input}:2168: Error: selected processor does not support `crc32b r2,r2,r1' in Thumb mode
[   28s] {standard input}:2186: Error: selected processor does not support `crc32b r2,r2,r1' in Thumb mode
[   28s] {standard input}:2204: Error: selected processor does not support `crc32b r2,r2,r1' in Thumb mode
[   28s] {standard input}:2222: Error: selected processor does not support `crc32b r2,r2,r1' in Thumb mode
[   28s] {standard input}:2240: Error: selected processor does not support `crc32b r2,r2,r1' in Thumb mode
[   28s] {standard input}:2258: Error: selected processor does not support `crc32b r2,r2,r1' in Thumb mode
[   28s] {standard input}:2269: Error: selected processor does not support `crc32b r2,r2,r3' in Thumb mode
[   28s] {standard input}:2359: Error: selected processor does not support `crc32cb r2,r2,r3' in Thumb mode
[   28s] {standard input}:2422: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2439: Error: selected processor does not support `crc32cw fp,r2,r1' in Thumb mode
[   28s] {standard input}:2455: Error: selected processor does not support `crc32cw r3,fp,r3' in Thumb mode
[   28s] {standard input}:2471: Error: selected processor does not support `crc32cw r3,r3,r10' in Thumb mode
[   28s] {standard input}:2488: Error: selected processor does not support `crc32cw r3,r3,r9' in Thumb mode
[   28s] {standard input}:2504: Error: selected processor does not support `crc32cw r3,r3,r2' in Thumb mode
[   28s] {standard input}:2519: Error: selected processor does not support `crc32cw r3,r3,r8' in Thumb mode
[   28s] {standard input}:2535: Error: selected processor does not support `crc32cw r3,r3,r1' in Thumb mode
[   28s] {standard input}:2552: Error: selected processor does not support `crc32cw r3,r3,r6' in Thumb mode
[   28s] {standard input}:2570: Error: selected processor does not support `crc32cw r3,r3,r10' in Thumb mode
[   28s] {standard input}:2583: Error: selected processor does not support `crc32cw r3,r3,r9' in Thumb mode
[   28s] {standard input}:2589: Error: selected processor does not support `crc32cw r2,r3,r2' in Thumb mode
[   28s] {standard input}:2599: Error: selected processor does not support `crc32cw r2,r2,r8' in Thumb mode
[   28s] {standard input}:2605: Error: selected processor does not support `crc32cw r2,r2,r1' in Thumb mode
[   28s] {standard input}:2615: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2621: Error: selected processor does not support `crc32cw r2,r2,r7' in Thumb mode
[   28s] {standard input}:2657: Error: selected processor does not support `crc32cw r2,r2,r5' in Thumb mode
[   28s] {standard input}:2663: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2688: Error: selected processor does not support `crc32cw r2,r2,r5' in Thumb mode
[   28s] {standard input}:2694: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2719: Error: selected processor does not support `crc32cw r2,r2,r5' in Thumb mode
[   28s] {standard input}:2725: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2750: Error: selected processor does not support `crc32cw r2,r2,r5' in Thumb mode
[   28s] {standard input}:2756: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2781: Error: selected processor does not support `crc32cw r2,r2,r5' in Thumb mode
[   28s] {standard input}:2787: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2812: Error: selected processor does not support `crc32cw r2,r2,r5' in Thumb mode
[   28s] {standard input}:2818: Error: selected processor does not support `crc32cw r2,r2,r6' in Thumb mode
[   28s] {standard input}:2841: Error: selected processor does not support `crc32cw r2,r2,r5' in Thumb mode
[   28s] {standard input}:2847: Error: selected processor does not support `crc32cw r2,r2,r1' in Thumb mode
[   28s] {standard input}:2869: Error: selected processor does not support `crc32cb r2,r2,r1' in Thumb mode
[   28s] {standard input}:2887: Error: selected processor does not support `crc32cb r2,r2,r1' in Thumb mode
[   28s] {standard input}:2905: Error: selected processor does not support `crc32cb r2,r2,r1' in Thumb mode
[   28s] {standard input}:2923: Error: selected processor does not support `crc32cb r2,r2,r1' in Thumb mode
[   28s] {standard input}:2941: Error: selected processor does not support `crc32cb r2,r2,r1' in Thumb mode
[   28s] {standard input}:2959: Error: selected processor does not support `crc32cb r2,r2,r1' in Thumb mode
[   28s] {standard input}:2970: Error: selected processor does not support `crc32cb r2,r2,r3' in Thumb mode
[   28s] lto-wrapper: fatal error: /usr/bin/cc returned 1 exit status
[   28s] compilation terminated.

I got wonder if this SDK supports target of linux arm64.
If I need to change a configuration in SDK to support it, could you please let me know it?

Thanks!

**Comment by jmklix** [comment]
I was able to build the latest version of this on an Ubuntu arm64 ec2 instance. If you haven't already make sure everything is up to date. What Linux distro are you using?

**Comment by kjnoh77** [comment]
I was up to date again after hearing you and still build error is occurring.

I have found new things looks like error as following.
                          : 
(**in fact, it's ARM64**)
[   16s] -- Performing Test AWS_ARCH_ARM64
[   16s] -- Performing Test AWS_ARCH_ARM64 - Failed
[   16s] -- Performing Test AWS_ARCH_ARM32
**[   16s] -- Performing Test AWS_ARCH_ARM32 - Success**
                           :
[   26s] [ 53%] Building C object aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/s2n/CMakeFiles/s2n.dir/utils/s2n_timer.c.o
[   26s] [ 53%] Linking C shared library ../../../../../lib/libs2n.so
[   29s] {standard input}: Assembler messages:
**[   29s] {standard input}:4357: IT blocks containing 32-bit Thumb instructions are deprecated in ARMv8**
                            :
[   29s] [ 57%] Linking C shared library libaws-c-cal.so
[   29s] [ 57%] Built target aws-c-compression
[   29s] {standard input}: Assembler messages:
**[   29s] {standard input}:1658: Error: selected processor does not support `crc32b r2,r2,r3' in Thumb mode**

I wonder what in this sdk package makes build recognize the arch of target.

Tizen my target is another linux distribution which might different from what you already know.
It obviously is using linux kernel and the current target processor is ARM64.

Thanks.
