### ISSUE TITLE
How to enable the logger in this SDK?

### ISSUE THREAD

**Issue by cpp-59487** [aws/aws-iot-device-sdk-cpp-v2#192]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Ubuntu 16.04 LTS

**Describe the question**
I would like to display the log messages recorded within SDK. It seems like it internally uses other AWS libraries written in C. I would like to dump the log messages as well. How could I create a logger in my application before calling the APIs to display logs?

Thanks.

**Comment by jmklix** [comment]
To enable the log, you will need to call InitializeLogging. Our [integration test](https://github.com/awslabs/aws-crt-cpp/blob/master/bin/elasticurl_cpp/main.cpp#L255) is a good sample of how this function works.

**Comment by kkozachuk** [comment]
Is it possible to change date-time log format? Or log to some callback?
