### ISSUE TITLE
AWS_IO_TLS_ERROR_WRITE_FAILURE when publishing large payload with MQTT over WebSocket

### ISSUE THREAD

**Issue by tonakat** [aws/aws-iot-device-sdk-cpp-v2#194]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
We can not publish with "MQTT over WebSocket" when using payload size larger than about 16280 Byte.

**Platform/OS/Device**
Ubuntu 16.04 and later

**SDK version number**
aws-iot-device-sdk-cpp-v2: v1.8.3 and v1.9.0

**To Reproduce (observed behavior)**
This is an example I published 20KB payload with MQTT over Websocket.
```
$ ./basic-pub-sub --endpoint xxxx-ats.iot.<region>.amazonaws.com --ca_file ~/root.ca.pem --signing_region <region> --use_websocket
...
[ERROR] [2020-11-04T08:19:20Z] [00007f1115f91700] [http-connection] - id=0x7f110801ac60: Destroying write message without passing it along, error 1031 (AWS_IO_TLS_ERROR_WRITE_FAILURE)
[ERROR] [2020-11-04T08:19:20Z] [00007f1115f91700] [websocket] - id=0x7f110801b0f0: Closing websocket due to failure during write, error 1031 (AWS_IO_TLS_ERROR_WRITE_FAILURE).
```

**Expected behavior**
Publish succeeds.

**Logs/output**
```
[ERROR] [2020-11-04T08:19:20Z] [00007f1115f91700] [http-connection] - id=0x7f110801ac60: Destroying write message without passing it along, error 1031 (AWS_IO_TLS_ERROR_WRITE_FAILURE)
[ERROR] [2020-11-04T08:19:20Z] [00007f1115f91700] [websocket] - id=0x7f110801b0f0: Closing websocket due to failure during write, error 1031 (AWS_IO_TLS_ERROR_WRITE_FAILURE).
```

**Additional context**
I suppose that this code might raise the error.
https://github.com/awslabs/aws-c-io/blob/2fb7007483c270410c40c3aff8abdcaa36df8050/source/s2n/s2n_tls_channel_handler.c#L572

It seems that the connection is getting closed due to some mishandling of the input data during the publish operation.
Further, we have tested the same using the Python SDK, we confirm works fine.

**Comment by DavidOgunsAWS** [comment]
Can you share the full log? If not, the critical sections would be the details of the TLS handshake at the start of the connect, logs setting up the IO write processing that happened before the above failure.

We would appreciate it and can take a look into it.

**Comment by JonathanHenson** [comment]
I think we'd need trace level for these logs as well.

**Comment by TkMorishita** [comment]
[failed.log (try to send 26478Bytes payload with 78Bytes TopicName (QoS=1))](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5613238/failed.log)
[successed.log (try to send 16238Bytes payload with 78Bytes TopicName (QoS=1))](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5613239/successed.log)
It seems to me that when sending a payload larger than 1685 bytes, the payload is split and fails as a result of an unexpected recursive call s_try_write_outgoing_frames.
In s_try_write_outgoing_frames, which is recursively called from s2n_flush in the first s_try_write_outgoing_frames, it seems that the state variable (s2n_connection-> current_user_data_consumed) is being processed in an invalid state without being reset.

**Comment by TkMoris** [comment]
[failed.log (try to send 26478Bytes payload with 78Bytes TopicName (QoS=1))](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5613369/failed.log)
It seems to me that when sending a payload larger than 1685 bytes, the payload is split and fails as a result of an unexpected recursive call s_try_write_outgoing_frames.
In s_try_write_outgoing_frames, which is recursively called from s2n_flush in the first s_try_write_outgoing_frames, it seems that the state variable (s2n_connection-> current_user_data_consumed) is being processed in an invalid state without being reset.

**Comment by tonakat** [comment]
I also attached my trace level logs. (published 20001 Bytes payload)

[trace.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5616204/trace.log)

**Comment by graebm** [comment]
Thank you @TkMoris! You perfectly diagnosed the underlying issue 🙇‍♂️

**Comment by graebm** [comment]
Fixed!
