### ISSUE TITLE
Crash in AWS IoT Device SDK

### ISSUE THREAD

**Issue by hesq1523** [aws/aws-iot-device-sdk-cpp-v2#196]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Describe the bug**
I am using aws-iot-device-sdk-cpp-v2 to communicate with AWS IoT Core. I found some crash issues while sending the MQTT message to AWS IoT Core quickly when the size of each packet is about 2k.
I also found the same crash issue has been reported in aws-iot-device-sdk-java-v2: [Crash in AWS IoT Device SDK Java v2](https://github.com/aws/aws-iot-device-sdk-java-v2/issues/53)

**Platform/OS/Device**
Hardware: Desktop PC
OS: Windows 10

**SDK version number**
aws-iot-device-sdk-cpp-v2
commit: 2cef480b9c79a2e5d8ef9f879f2bc3ff1fa30bde

**To Reproduce (observed behavior)**
Send data to IoT Core quickly. 

**Expected behavior**
It should be run without any problem.

**Additional context**
Screenshot of the call stack when the crash happened.
![Crash](https://user-images.githubusercontent.com/5314815/99783367-4ed92400-2b55-11eb-9f83-9e977c00b754.png)

**Comment by DavidOgunsAWS** [comment]
Can you update to a newer version of the C++ V2 SDK as it will pick up the same fix made available to Java from the related issue (https://github.com/aws/aws-iot-device-sdk-java-v2/issues/53)?

It's likely the fix applies since the problem was in code shared by both the C++ and Java device SDKs.

**Comment by hesq1523** [comment]
Thanks @DavidOgunsAWS .
We updated to a new version, which the commit number is: 7be91fe560f1e12702a85ca0b579c401a23c4821.
This crash issue did not happen again after we updated to this version.
