### ISSUE TITLE
Linker issues related to ShadowClient and/or JSON

### ISSUE THREAD

**Issue by angrdtsk** [aws/aws-iot-device-sdk-cpp-v2#199]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Ubuntu 18.04

**Describe the question**
I am writing a C++ daemon program that has interfaces to AWS cloud and D-Bus. It uses Glibmm for D-Bus and main event loop and spdlog for logging.

So far, I have been building it inside the AWS SDK source tree. I made a copy of the basicPubSub example project and started modifying that to my needs.

That worked fine as long as I had no need for AWS related functionality that wasn't already included in basicPubSub. That changed when I needed to start using ShadowClient. When I added code that instantiates it and also added it into my CMakeLists.txt, I got a linker error complaining about undefined reference on every line that referenced the ShadowClient.

I couldn't find a way around that so I decided to try slightly different approach. In the AWS SDK source package I had downloaded earlier, I found an example of using ShadowClient meant to be built stand-alone i.e. not inside the SDK source tree. I liked that because I had been interested in being able to build stand-alone.

I replaced the example code with my own (at this point, without ShadowClient), and that worked. But when I added instantiation of ShadowClient, I got linker errors again. This time it was different, though: libIotShadow had undefined references to JSON-related stuff in Aws::Crt namespace.

What I have now is two stand-alone projects that, as far as my understanding goes, have no differences that should affect linking. One is the original ShadowClient example and the other is my own code with CMakeLists.txt based on the one from that example. For some reason, though, the example project builds while my own code doesn't. If I remove the lines in my code that refer to ShadowClient, it does build.

To make the projects more similar, I added the lines related to Glib and spdlog to the clean example project too, which didn't introduce any problems.

This is what I have in my CMAkeLists.txt files for includes:
```
find_package(aws-crt-cpp REQUIRED)
find_library (
    SHADOW_LIB
    NAMES IotShadow-cpp
)

target_link_libraries(${PROJECT_NAME} AWS::aws-crt-cpp ${SHADOW_LIB})

find_package(PkgConfig)
pkg_check_modules(GLIBMM glibmm-2.4)
link_directories(${GLIBMM_LIBRARY_DIRS})
include_directories(${GLIBMM_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} ${GLIBMM_LIBRARIES})
pkg_check_modules(GIOMM giomm-2.4)
link_directories(${GIOMM_LIBRARY_DIRS})
include_directories(${GIOMM_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME}  ${GIOMM_LIBRARIES})

find_package(spdlog REQUIRED)
target_link_libraries(${PROJECT_NAME} spdlog::spdlog)
```

At some point of trying things, I got some warnings from cmake suggesting me to add some policies to my CMakeLists.txt. There were a few of them mentioned, but unfortunately, I only remember one, which is CMP0003. Using that is not helping, though.

This is what I have built and installed the SDK with:
```
cmake -DCMAKE_INSTALL_PREFIX="/usr/local"  -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=Debug ..
cmake --build . --config Debug
sudo checkinstall
```

And this is how I am building the applications:
```
cmake -DCMAKE_INSTALL_PREFIX="/usr/local"  -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE=Debug ..
make
```

Does my explanation of the problem give any clue on what might be going wrong with my own code?

**Comment by jmklix** [comment]
Recently we have changed all of the samples to run stand alone by default. Please update your sdk to the latest release and try building the basic_pub_sub and take note of the changes to CMakeLists.txt. If this does not work please let me know and I will try my best to help.

Also note standalone build  instructions have been added to the samples Readme.md:

> mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH="<absolute path sdk-cpp-workspace dir>" -DCMAKE_BUILD_TYPE="<Release|RelWithDebInfo|Debug>" ..
cmake --build . --config "<Release|RelWithDebInfo|Debug>"

**Comment by angrdtsk** [comment]
> 
> 
> Recently we have changed all of the samples to run stand alone by default. Please update your sdk to the latest release and try building the basic_pub_sub and take note of the changes to CMakeLists.txt. If this does not work please let me know and I will try my best to help.
> 
> Also note standalone build instructions have been added to the samples Readme.md:
> 
> > mkdir build
> > cd build
> > cmake -DCMAKE_PREFIX_PATH="" -DCMAKE_BUILD_TYPE="<Release|RelWithDebInfo|Debug>" ..
> > cmake --build . --config "<Release|RelWithDebInfo|Debug>"

The problem was solved with help of this. Thanks!
