### ISSUE TITLE
Negotiation failed with error Invalid signature algorithm when using ECDSA private key for mutual authentication

### ISSUE THREAD

**Issue by Morena291** [aws/aws-iot-device-sdk-cpp-v2#200]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Software details**
OS: Linux ubuntu-dev-cm 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OpenSSL: OpenSSL 1.1.1f 31 Mar 2020
aws-iot-device-sdk-cpp-v2: commit 171ec02960377278597bff751577225415260f9cd (20 Nov 2020)

**Bug description**
Using the default basic_pub_sub example (with logging enabled), we were unable to connect to aws endpoint. The connection fails with the following error:

**_[WARN] [2020-11-23T12:01:41Z] [00007f5a42ec9700] [tls-handler] - id=0x7f5a3c001c80: negotiation failed with error Invalid signature algorithm (Error encountered in /home/parallels/Repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/s2n/crypto/s2n_ecdsa.c line 44)
Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed_**

The ECDSA private key has been generated with openssl using the following command:
openssl ecparam -genkey -name prime256v1 -out eckey.pem

**More details**
the same client certificate and private key have been successfully tested with "mosquitto_pub" and with a NodeJS application using aws-iot-device-sdk-js

![image](https://user-images.githubusercontent.com/74976566/100115468-d636d800-2e72-11eb-9cc5-ed636b45d56a.png)

**Comment by jmklix** [comment]
Can you provide the logs from when you try to run the basic-pub-sub?

```
ApiHandle::InitializeLogging(...)
```
*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Comment by JonathanHenson** [comment]
Any chance you could capture the client hello and server hello for us?

**Comment by JonathanHenson** [comment]
alternatively, this may simply be a matter of the configured allowed cipher suites in s2n. I'm digging through that code now.

**Comment by JonathanHenson** [comment]
the bad news is, we're not having trouble loading your cert and it's not a cipher negotiation problem. We're failing during client-key-exchange with an alert code of 21, which means this is going to be a somewhat involved issue and I'm going to have to pull in a cryptography expert. I'm working on it actively.

**Comment by JonathanHenson** [comment]
which libcrypto are you using? how was it built? Could I see your cmake configure step's output?

**Comment by JonathanHenson** [comment]
Why are you generating:

openssl req -x509 -new -SHA384 -nodes -key ca.key -days 3650 -out ca.crt?

The issue seems to be around SHA384 could you possibly try with SHA256? That may be a work around for you.

**Comment by JonathanHenson** [comment]
Pr filed for fix:

https://github.com/awslabs/s2n/pull/2434

**Comment by JonathanHenson** [comment]
If you’d like to test with the fix feel free to update your submodule for s2n to the commit in the PR. As soon as we’ve verified the fix we’ll update main here.

**Comment by bretambrose** [comment]
Are you still having an issue with the latest SDK version?
