### ISSUE TITLE
Simplified MQTT custom auth example

### ISSUE THREAD

**Issue by massi-ang** [aws/aws-iot-device-sdk-cpp-v2#204]
**Is your feature request related to a problem? Please describe.**

The `raw_pub_sub` example has too many options and does not provide a clean example for using MQTT username and password authentication

**Describe the solution you'd like**

A dedicated sample for MQTT username / password authentication

**Describe alternatives you've considered**

**Additional context**

**Comment by jmklix** [comment]
Thanks for taking the time to create this example!
