### ISSUE TITLE
Cannot build project, not on windows 10, not on Ubuntu 18.04

### ISSUE THREAD

**Issue by gellerilan** [aws/aws-iot-device-sdk-cpp-v2#212]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
Using build instruction I cannot built the project for use

**Platform/OS/Device**
Window 10 x64
Ubuntu 18.04

**SDK version number**
v2

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
mkdir build
mkdir install
cd build
cmake -DCMAKE_INSTALL_PREFIX="../install" -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE="Release" ..
cmake --build . --target install

**Expected behavior**
Build should finish with project built

**Logs/output**
[ 98%] Linking CXX executable IotDeviceDefender-cpp-tests
../libIotDeviceDefender-cpp.so: undefined reference to `aws_iotdevice_defender_v1_stop_task'
../../iotdevicecommon/libIotDeviceCommon-cpp.so: undefined reference to `aws_iotdevice_library_clean_up'
../../iotdevicecommon/libIotDeviceCommon-cpp.so: undefined reference to `aws_iotdevice_library_init'
../libIotDeviceDefender-cpp.so: undefined reference to `aws_iotdevice_defender_v1_report_task'
collect2: error: ld returned 1 exit status
devicedefender/tests/CMakeFiles/IotDeviceDefender-cpp-tests.dir/build.make:132: recipe for target 'devicedefender/tests/IotDeviceDefender-cpp-tests' failed
make[2]: *** [devicedefender/tests/IotDeviceDefender-cpp-tests] Error 1
CMakeFiles/Makefile2:2084: recipe for target 'devicedefender/tests/CMakeFiles/IotDeviceDefender-cpp-tests.dir/all' failed
make[1]: *** [devicedefender/tests/CMakeFiles/IotDeviceDefender-cpp-tests.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

**Additional context**
Also need to build on windows, fails on building most of the projects:
error C2220: warning treated as error - no 'object' file generated [C:\...\build\crt\aws-c-iot.vcxproj] and the files are not generated on the /install folder

**Comment by jmklix** [comment]
There have been some recent changes that allow/require the sample to be build stand alone. This allows you to build your project anywhere, not just inside the samples folder. If you are using the latest version of the sdk then it looks like you are missing a few steps required to build your project: Instructions can be found [here](https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples#build-samples)

Can you please let us know if you are still having issues building this sdk when using these steps?

**Comment by gellerilan** [comment]
Hi,

Still doesn't work:
The steps I have followed on Windows:

mkdir sdk-cpp-workspace
cd sdk-cpp-workspace
git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
mkdir aws-iot-device-sdk-cpp-v2-build
cd aws-iot-device-sdk-cpp-v2-build
cmake -DCMAKE_INSTALL_PREFIX="C:\workspace\iot_sandbox\sdk-cpp-workspace\install" -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE="Release" ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install

My output:
c:\workspace\iot_sandbox\sdk-cpp-workspace\aws-iot-device-sdk-cpp-v2-build>cmake --build . --target install
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/workspace/iot_sandbox/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-c
  ommon/CMakeLists.txt
cl : Command line error D8016: '/O2' and '/RTC1' command-line options are incompatible [C:\workspace\iot_sandbox\sdk-cp
p-workspace\aws-iot-device-sdk-cpp-v2-build\crt\aws-crt-cpp\crt\aws-c-common\aws-c-common.vcxproj]

**Comment by jmklix** [comment]
Try using this cmake command and let me know if this works:
```
cmake -DCMAKE_INSTALL_PREFIX="C:\workspace\iot_sandbox\sdk-cpp-workspace" -DCMAKE_PREFIX_PATH="C:\workspace\iot_sandbox\sdk-cpp-workspace" -DBUILD_DEPS=ON ../aws-iot-device-sdk-cpp-v2
```

**Comment by gellerilan** [comment]
Hi,

OK,

It did work on Windows now, Can you tell me what is the difference? is it the CMAKE_BUILD_TYPE ??

Also, 
What is the right command line to run on ubuntu Linux?

Ilan

**Comment by jmklix** [comment]
I think it adding DCMAKE_PREFIX_PATH and removing CMAKE_BUILD_TYPE was what helped it work. But I'm not entirely sure why it helped other than that DCMAKE_PREFIX_PATH explicitly defines what dir to look for dependencies in and CMAKE_BUILD_TYPE defaults to DEBUG if not specified.

As for ubuntu I was able to get it working by using the following command:
```
cmake -DCMAKE_INSTALL_PREFIX="/home/<username>/Documents/sdk-cpp-workspace" -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE="Debug" ../aws-iot-device-sdk-cpp-v2
```
You might also be having different issues with libcrypto on ubuntu, so let me know it the above doesn't work.
