### ISSUE TITLE
mqtt msg lost when interrupt happens

### ISSUE THREAD

**Issue by chengyouyang** [aws/aws-iot-device-sdk-cpp-v2#217]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
if an interrput happens while sending a mqtt msg (with QOS==1), there are chances that the message get lost without notification.

env: aws-iot-device-sdk-cpp-v2

config: mqtt pub/sub with (qos == 1), connection with cleanSession==false

**Platform/OS/Device**
MacOS

**SDK version number**
v1.10.0

**To Reproduce (observed behavior)**
steps:
   1. puber keeps sending msg with an increasing counter; puber starts sending a new msg only when previous puback is received; counter get increased only when puback reveals success
   2. suber receives msg, and check against the counter;
   3. when interrup+resume happens (for example due to network disconnection), suber would report mismatch.
   4. seems like the missing msg was not sent to the iot-broker neither

**Expected behavior**
The qos1 msg get published successfully.
Or at least get notified from the failure.

**Logs/output**
[Code snippet](https://gist.github.com/chengyouyang/fcaccf466f3ab7da8747a836c8373373) tweaked from your [example]( https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/main/samples/mqtt/basic_pub_sub/main.cpp)
Example output from the code snippet:
```
PUBACK on packetId 1 Succeeded
Msg received on topic test/topic, Message: 16 
PUBACK on packetId 2 Succeeded.     <---------------msg17 puback success, this message is received
Msg received on topic test/topic, Message: 17 
PUBACK on packetId 3 Succeeded    <---------------msg18 puback success, this message is LOST!!
Connection interrupted with error libaws-c-mqtt: AWS_ERROR_MQTT_TIMEOUT, Time limit between request and response has been exceeded.
Connection resumed
PUBACK on packetId 1 Succeeded    <---------------msg19 puback success, this message is received
Msg received on topic test/topic, Message: 19 
Msg mismatch!!!! expect: 18, recvd: 19
PUBACK on packetId 2 Succeeded
Msg received on topic test/topic, Message: 20 
```

**Additional context**

**Comment by jmklix** [comment]
Can you provide the code sample that you used to test this? 
Also you said:

> there are chances that the message get lost without notification

How often when testing this did a message get lost?

**Comment by donhpham** [comment]
Hello,
Was there any resolution for this issue? It looks like I'm seeing a similar issue where I'm losing messages sent with QoS 1 right before the the AWS_ERROR_MQTT_TIMEOUT is detected. Messages sent after the interrupt get sent properly when connection is restored.

Thanks.
