### ISSUE TITLE
Using TCP keep-alive to detect network failures, then quickly reconnect

### ISSUE THREAD

**Issue by psiphi75** [aws/aws-iot-device-sdk-cpp-v2#220]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution, namely #11, #10, and #151.

**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `aed9vpfras5v1-ats.iot.ap-southeast-2.amazonaws.com`

**Platform/OS/Device**
ARM Linux

**SDK version number**
v1.9.0 of this SDK.
  
**Describe the bug**
I'm trying to use the TCP Keep-alive feature (instead of MQTT PING) to detect network disconnects.  The reason is that we MQTT PINGS use significantly more bandwidth and are not as feature rich for our needs.

**To Reproduce (observed behavior)**
Below is the code:
```cpp
    builder.WithTcpKeepAlive();
    builder.WithTcpKeepAliveTimeout(60);
    builder.WithTcpKeepAliveInterval(30);
    builder.WithTcpKeepAliveMaxProbes(3);

// ...

    mqtt_connection_->SetReconnectTimeout(15, 30);
    bool connection_result = mqtt_connection_->Connect(client_id.c_str(), false); 
```

**Expected behavior**

I would expect this code to fail within 2.5 minutes or so after the network is reset.  However, it takes around 8 to 10 minutes to detect a network failure and restart.

Or am I missing something?  In a nutshell, we want to quick reconnect MQTT when the network comes back up such that we can access AWS IoT Shadows as well as publish on an MQTT topic.  We can detect the network going down and coming back up, how would we force MQTT to reconnect with a persistent session?

**Comment by jvasanthan** [comment]
I tried the same setting sdk detects network failure in about 3-3.5 minutes

**Comment by psiphi75** [comment]
@justinboswell, that's interesting.  What were your TCP Keep-alive settings and what platform did you test this on?

**Comment by jvasanthan** [comment]
Same as you mentioned. It's embedded Linux platform

**Comment by jmklix** [comment]
It's recommended to use [MQTT keep-alive](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/223#issuecomment-767023050). The bandwidth isn't that much different as explained [here](https://github.com/aws/aws-iot-device-sdk-python-v2/issues/90#issuecomment-662659585):

> MQTT vs TCP keep-alive
> 
> If you're worried about data usage, there's almost no different between using MQTT and TCP keepalive.
> The MQTT ping packet is 2 bytes, and the response from the server is also 2 bytes. Each of these is wrapped in TCP/IPV4/Ethernet framing which add another 64+ bytes.
> 
> A TCP keep-alive packet will not have the MQTT data so it will be 2 bytes smaller: 64 bytes instead of 66.

**Comment by psiphi75** [comment]
Thanks, but I don't think that is correct.  See my comment here: https://github.com/aws/aws-iot-device-sdk-python-v2/issues/90#issuecomment-767849078

**Comment by JonathanHenson** [comment]
Mqtt ping will also have an additional 57 bytes or so due to TLS record overhead

**Comment by jmklix** [comment]
@psiphi75 What exact hardware/linux distro are you using?

**Comment by psiphi75** [comment]
Our details are:
Linux version: Linux 5.4.0 (own build)
Arm processor: ARMv7 Processor [413fc090] revision 0 (ARMv7)
Distro: PetaLinux (which is based on Yocto Linux).

**Comment by psiphi75** [comment]
It seems like I'm getting to the bottom of this.  It appears I made some assumptions about TCP Keepalive on Linux, it also appears I'm [not the first either](https://codearcana.com/posts/2015/08/28/tcp-keepalive-is-a-lie.html).

In Linux TCP Keepalive works on idle connections, if you keep sending packets (like we do) the keepalive will not actually terminate the tcp socket.  Only when you stop sending packets will TCP keepalive kick in.

In Linux this can be countered using one of two settings:
 - Setting /proc/sys/net/ipv4/tcp_retries2 to a certain value, the problem is this is not per-socket, but for the whole OS, which is an overkill for us.
 -  Using setsockopt and setting TCP_USERTIMEOUT to a reasonable value.

We will implement the TCP_USERTIMEOUT option since we can customise for the MQTT TCP connection.  It's simple enough to change your code, but it would be great to have this as part of the appropriate SDK.

What is required to lodge a formal feature request for this setting?  It appears this setting will impact multiple layers of APIs and I don't know if this value exists on other platforms.

**Comment by jmklix** [comment]
The best option would be to open a new issue using the [feature request template](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/new?assignees=&labels=feature-request%2C+needs-triage&template=---feature-request.md&title=). Make sure to include a link back to this issue as well as a detailed description of what you what you want.

**Comment by psiphi75** [comment]
Am closing this issue with a feature request.  See #232.

**Comment by JonathanHenson** [comment]
Bad bot! Bad bot! 🗞🗞🗞🗞
