### ISSUE TITLE
basic-pub-sub application terminates when log level trace is enabled

### ISSUE THREAD

**Issue by jvasanthan** [aws/aws-iot-device-sdk-cpp-v2#224]
Hi Team, 
basic-pub-sub application gets terminated when log level is set to trace but works fine when it is set to Debug
PFA logs
[debug_log.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5854864/debug_log.txt)
[trace_log.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5854865/trace_log.txt)

**Comment by jmklix** [comment]
What hardware are you using?

**Comment by jvasanthan** [comment]
Its a custom board based on IMX6 processor. Running V1.10.1 sdk version cross compiled.

**Comment by jmklix** [comment]
Do you get any output when the program terminates? Nothing I've tested has broken when using trace, so it might be specific to the IMX6 processor.
