### ISSUE TITLE
@bretambrose Just tested with the latest release v1.10.2, and got the same crash. IMHO the bug is not related to the bad constructor or allocator. Please review the proposed fix above. The tls options variable  is  declared as Optional<Io::TlsConnectionOptions> TlsOptions; in the class AWS_CRT_CPP_API HttpClientConnectionProxyOptions. And in the code from  std::shared_ptr<ICredentialsProvider> CredentialsProvider::CreateCredentialsProviderX509 function the proxy_config.TlsOptions->GetUnderlyingHandle(); is accessed directly without checking if there is a value set. This causes garbage initialisation of the assigned variable. This garbaged tls_option is later used as source for copying during the provider creation.

### ISSUE THREAD

**Issue by anatolyaliev** [aws/aws-iot-device-sdk-cpp-v2#226]
@bretambrose Just tested with the latest release v1.10.2, and got the same crash. IMHO the bug is not related to the bad constructor or allocator. Please review the proposed fix above. The tls options variable  is  declared as Optional<Io::TlsConnectionOptions> TlsOptions; in the class AWS_CRT_CPP_API HttpClientConnectionProxyOptions. And in the code from  std::shared_ptr<ICredentialsProvider> CredentialsProvider::CreateCredentialsProviderX509 function the proxy_config.TlsOptions->GetUnderlyingHandle(); is accessed directly without checking if there is a value set. This causes garbage initialisation of the assigned variable. This garbaged tls_option is later used as source for copying during the provider creation.

Thread 20 Crashed:
0   fpneocommond                  	0x0000000101fd508b aws_mem_acquire + 11
1   fpneocommond                  	0x0000000101fdf97f aws_string_new_from_string + 47
2   fpneocommond                  	0x000000010201435f aws_tls_connection_options_copy + 143
3   fpneocommond                  	0x0000000101ffc1c8 aws_http_proxy_config_new + 248
4   fpneocommond                  	0x0000000101fe1a1a aws_http_connection_manager_new + 474
5   fpneocommond                  	0x0000000101fd10fb aws_credentials_provider_new_x509 + 715
6   fpneocommond                  	0x000000010201fc89 Aws::Crt::Auth::CredentialsProvider::CreateCredentialsProviderX509(Aws::Crt::Auth::CredentialsProviderX509Config const&, aws_allocator*) + 441
7   fpneocommond                  	0x0000000101de542c 0x101db2000 + 209964
8   fpneocommond                  	0x0000000101dddc82 0x101db2000 + 179330
9   fpneocommond                  	0x0000000101dde791 0x101db2000 + 182161
10  fpneocommond                  	0x0000000101dcf55c 0x101db2000 + 120156
11  fpneocommond                  	0x0000000101dcdf1b 0x101db2000 + 114459
12  fpneocommond                  	0x0000000101dcb49d 0x101db2000 + 103581
13  libsystem_pthread.dylib       	0x00007fff6e381109 _pthread_start + 148
14  libsystem_pthread.dylib       	0x00007fff6e37cb8b thread_start + 15

_Originally posted by @anatolyaliev in https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/225#issuecomment-765660351_

**Comment by bretambrose** [comment]
I reopened the original issue
