### ISSUE TITLE
How to build for c++ builder / embarcadero

### ISSUE THREAD

**Issue by AMuellerAtAHS** [aws/aws-iot-device-sdk-cpp-v2#235]
I am trying to build the aws-iot-device-sdk-cpp-v2 with CMake and embarcadero's C++ Builder (bcc64.exe Version 10.2) on a Windows 10 machine.

First I copied the Windows-Embarcadero.cmake from the RAD folder to the CMake folder, like described [in embarcadero documentation](http://docwiki.embarcadero.com/RADStudio/Sydney/en/Using_CMake_with_C%2B%2B_Builder).

Then I followed the steps from the aws-iot-device-sdk-cpp-v2 installing instructions. But changed the first CMake line to `cmake -DCMAKE_INSTALL_PREFIX="<absolute path sdk-cpp-workspace dir>" -DCMAKE_PREFIX_PATH="<absolute path sdk-cpp-workspace dir>" -DBUILD_DEPS=ON -DCMAKE_C_COMPILER=bcc32x.exe -DCMAKE_CXX_COMPILER=bcc32x.exe -DCMAKE_BUILD_TYPE_INIT=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -G Ninja --debug-output -v ../aws-iot-device-sdk-cpp-v2`

This step seems to succeed or I don't get any errors.

But when I try to run the command `ninja` to build the created files, it throws me the following error: `bcc32x.exe: error: Argument wird wõhrend der Compilierung nicht verwendet: '-moutline-atomics'`

When I try to find some more information in the [CMakeError.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5987973/CMakeError.log) and [CMakeOutput.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/5987974/CMakeOutput.log), I stuck that some temporary files are deleted.

May I have to change some VS specific parts to fit for c++ builder?

**Comment by jmklix** [comment]
Can you include more details about what you are trying to do and how you are using ninja?
also including the cmake info that you posted on stackoverflow would be appreciated, and more convenient to have all of the info in one place.

**Comment by AMuellerAtAHS** [comment]
@jmklix 
Thanks for your reply. Do you need other informations?
