### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by IgorV-fp** [aws/aws-iot-device-sdk-cpp-v2#236]
Hi,
Does the sdk supports Apple Silicon?
If so, where can I found the build and test instructions?
thanks

**Comment by jmklix** [comment]
No, we have not tested it on Apple Silicon yet. Feel free to try it yourself and paste any errors you encounter below. I'm going to change this to a feature request so we can let you know when we are able to test it ourselves.

**Comment by jmklix** [comment]
Yes, this sdk now supports apple silicon. You can find instructions on how to build the aws-crt-cpp for M1 [here](https://github.com/awslabs/aws-crt-cpp#apple-silicon-aka-m1-and-universal-binaries).
