### ISSUE TITLE
compile error : unknown option after #pragma GCC diagnostic kind [-Werror=pragmas]

### ISSUE THREAD

**Issue by mayurpatelgec** [aws/aws-iot-device-sdk-cpp-v2#237]
Confirm by changing [ ] to [x] below:
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Platform/OS/Device**
What are you running the sdk on?
arm-buildroot-docker-sdk (doing cross compiling for armhf)
Details: 
- armhf architecture
- Buildroot BSP
- cross compiler: **arm-linux-g++ (GNU 4.7.2)**

**Describe the question**
I am doing cross compilation and here are the steps:
```
# create workspace dir
mkdir -p /usr/src/app/sdk/sdk-cpp-workspace && cd /usr/src/app/sdk/sdk-cpp-workspace

# get aws source
echo "*** geting sdk"
git clone https://github.com/aws/aws-iot-device-sdk-cpp-v2.git -b v1.10.4  --recursive

# build aws sdk
echo "*** Building sdk"
mkdir aws-iot-device-sdk-cpp-v2-build && cd aws-iot-device-sdk-cpp-v2-build
cmake -DCMAKE_TOOLCHAIN_FILE=/var/shared/tcu_build_scripts/submodules/arm_development_support/output/host/usr/share/buildroot/toolchainfile.cmake -DCMAKE_INSTALL_PREFIX="/usr/src/app/sdk/sdk-cpp-workspace" -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE="Debug"  ../aws-iot-device-sdk-cpp-v2

```
**QUE. 1:**
why am i getting this error only for the first time when i run above given cmake command? Looking at google found out that without doing anything run the same command again will solve your problem.
![image](https://user-images.githubusercontent.com/26649420/108089336-c4cc2900-7079-11eb-9137-6e0b80d6b65f.png)

**QUE. 2:**
after solving the above problem by running the same command again, when i run the last command,  
`cmake --build . --target install` I got the below error. Do you have any idea why am i getting this?
![image](https://user-images.githubusercontent.com/26649420/108112901-0e773c80-7097-11eb-95a0-3bcb7ed4b8e8.png)

HINTS:
from my points of view it can be because of 
- very old compiler 4.7
- a wrong compile flag like "-Werror" etc. (I have tried settting CMAKE_CXX_FLAGS) but problem is i think every target has thier fixed compile flags that overwrites my set of flags. (i have checked it with `make VERBOSE=1`)

**Comment by jmklix** [comment]
Do you have the dockerfile that you are using?
