### ISSUE TITLE
packet size limitation

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#242]
Hi, we are using SKD version 1.10.3, MQTT over websockets (mac OS). seems as big packets (~40k) cannot be published.
1. is there any official limitation for published packet size? 
2. if yes, can this be configured?
3. is there any difference between Windows and Mac regarding this?

Thanks

**Comment by jmklix** [comment]
Source: https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot

1. Yes


Resource | Description
| --- | ----------- |
Message size | The payload for every publish request can be no larger than 128 KB. AWS IoT Core rejects publish and connect requests larger than this size.

2. No
3. No, there shouldn't be any

So 40 KB shouldn't run into any problems by itself, but it can hit the 512 KB per second limit pretty quickly.


Resource | Description | Default | Adjustable
| --- | ----------- | ----------- | ----------- |
Throughput per second per connection | Data received or sent over a client connection is processed at a maximum throughput rate. Data that exceeds the maximum throughput is delayed in processing. | 512 KiB | No

 What error messages are you getting in relation to this?

**Comment by elad-ep** [comment]
thanks for the info. my collogue posted the crash information in issue #173. I will close this one, thanks.
