### ISSUE TITLE
implementing custom ICredentialsProvider

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#243]
Hi, we are using SDK 10.0.3 with CredentialsProviderX509. we would like to implement our own credentials provider instead of using the SDK CredentialsProviderX509 (so we can get STS credentials in a different way, in case fetching credentials using x509 cert fails - due to Mitm proxy that doesn't allow client authentication).
looking at ICredentialsProvider in Credentials.h I can see that I need to implement GetUnderlyingHandle() for both ICredentialsProvider and Credentials objects. however, the underlying structs (aws_credentials/aws_credentials_provider) are forward declared and not exposed.

Is there a way I can provide my own ICredentialsProvider implementation?

**Comment by bretambrose** [comment]
Both of those are exposed publicly in the aws/auth/credentials.h header in the aws-c-auth submodule.  You may also want to look into other credentials providers in aws-c-auth and try building a chain from them.

**Comment by elad-ep** [comment]
thanks, I will check it out.
