### ISSUE TITLE
SDK Size and requirements

### ISSUE THREAD

**Issue by justin8** [aws/aws-iot-device-sdk-cpp-v2#245]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?

**Describe the question**
Hey,

I'm trying to figure out what the minimum requirements are to run the device SDK, mostly in terms of NAND/ROM/disk size requirements and memory requirements, but also CPU requirements. The documentation, SDK source and other sources don't seem to have any clear guidance on this. I imagine in terms of CPU it needs to be fast enough to effectively handle mutual TLS for example.

Even a vague lower bound would be quite useful to know.

**Comment by justin8** [comment]
I found that this is available for the embedded C SDK in the generated API docs, e.g. for shadow service: https://docs.aws.amazon.com/embedded-csdk/202103.00/lib-ref/libraries/aws/device-shadow-for-aws-iot-embedded-sdk/docs/doxygen/output/html/index.html

But I cannot find something equivalent for C++

**Comment by jmklix** [comment]
Any disk size bigger than the package size (which is ~270 MB on my mac) should be big enough. As for the CPU/memory, anything that runs Linux should work with preferences for: x86/x64, armv6, armv7, aarch64.

The smallest thing that I have run it on is a raspberry pie zero w, and while it takes longer to build the sdk it works fine on it. Did you have a specific device that you would like to use?
