### ISSUE TITLE
Error while trying to build/install library on windows 10 with visual studio 2019 enterprise. 

### ISSUE THREAD

**Issue by Baljitsingh2** [aws/aws-iot-device-sdk-cpp-v2#246]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Windows 10. 

**Describe the question**
I am trying to install the version two of the sdk using following command:
`cmake -DCMAKE_INSTALL_PREFIX="c:\Workspace\sdk-cpp-workspace\" -DCMAKE_PREFIX_PATH="c:\Workspace\sdk-cpp-workspace\" -DEBUILD_DEPS=ON ..\aws-iot-device-sdk-cpp-v2 `
When I run the command I get following error:
`-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.28.29337.0
-- The CXX compiler identification is MSVC 19.28.29337.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:54 (include):
  include could not find load file:

    AwsFindPackage

CMake Error at jobs/CMakeLists.txt:94 (aws_use_package):
  Unknown CMake command "aws_use_package".

-- Configuring incomplete, errors occurred!
See also "C:/Workspace/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeOutput.log".`

I am new to cmake. I might be doing something wrong. 

My filesystem setup.
c:\Workspace\sdk-cpp-workspace\
c:\Workspace\sdk-cpp-workspace\aws-iot-device-sdk-cpp-v2
c:\Workspace\sdk-cpp-workspace\aws-iot-device-sdk-cpp-v2-build
I am running the command from c:\Workspace\sdk-cpp-workspace\aws-iot-device-sdk-cpp-v2-build.

**Comment by bretambrose** [comment]
You need to clone the submodules that the SDK depends on.  From the root source directory:

`git submodule update --init --recursive`
