### ISSUE TITLE
Deactivated/Deleted certificate

### ISSUE THREAD

**Issue by donhpham** [aws/aws-iot-device-sdk-cpp-v2#247]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Embedded Linux

**Describe the question**
Hello,

When attempting to connect to AWS using a certificate that has been deactivated & deleted, we get **AWS_ERROR_MQTT_UNEXPECTED_HANGUP** error back on the OnConnectionCompletedHandler in MqttConnection. Based on the code it looks like this is a generic error being returned and is not specific to an invalid certificate.
```
    /* If there's no error code and this wasn't user-requested, set the error code to something useful */
    if (error_code == AWS_ERROR_SUCCESS) {
        if (prev_state != AWS_MQTT_CLIENT_STATE_DISCONNECTING && prev_state != AWS_MQTT_CLIENT_STATE_DISCONNECTED) {
            error_code = AWS_ERROR_MQTT_UNEXPECTED_HANGUP;
        }
    }
```
As a side question, while the device is running, and the certificate gets deactivated & deleted, we get the same **AWS_ERROR_MQTT_UNEXPECTED_HANGUP** back on the OnConnectionInterrupted in MqttConnection.
Is there an API to check if the connection failed/was interrupted due to an invalidated certificate?

Thanks

**Comment by bretambrose** [comment]
Unfortunately, the client receives no additional information in this situation that could be reflected up to the SDK consumer.  In these cases, the server simply closes the connection.

You can use cloudwatch monitoring to help debug connection/action issues with AWS IoT: https://docs.aws.amazon.com/iot/latest/developerguide/monitoring_overview.html
