### ISSUE TITLE
AWS MQTT SDK crashes randomly due to segmentation fault

### ISSUE THREAD

**Issue by cpp-59487** [aws/aws-iot-device-sdk-cpp-v2#257]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
We use the library aws-iot-device-sdk-cpp-v2 to use the MQTT service. We have setup all required objects to use the sub/pub service. During execution, it crashes randomly with the following core dump which is attached below. It is hard to reproduce this issue since it does not always happen. We doubt that this may be related to the stability of the Internet connection.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7ff5db8ba700 (LWP 65450))]
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ff5e6a3ac21 in s_request_timeout_task () from /usr/local/lib/libaws-c-mqtt.so.0unstable
#2  0x00007ff5e95fbd31 in aws_task_scheduler_cancel_task () from /usr/local/lib/libaws-c-common.so.0unstable
#3  0x00007ff5e63848bc in s_on_shutdown_completion_task () from /usr/local/lib/libaws-c-io.so.0unstable
#4  0x00007ff5e95fb78e in s_run_all () from /usr/local/lib/libaws-c-common.so.0unstable
#5  0x00007ff5e638e1a8 in s_main_loop () from /usr/local/lib/libaws-c-io.so.0unstable
#6  0x00007ff5e95f8e4b in thread_fn () from /usr/local/lib/libaws-c-common.so.0unstable
#7  0x00007ff5f86436ba in start_thread (arg=0x7ff5db8ba700) at pthread_create.c:333
#8  0x00007ff5f8eae4dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

**Platform/OS/Device**
Ubuuntu 16.04.7 LTS on x86

**SDK version number**
v1.7.1

**To Reproduce (observed behavior)**
Sorry I cannot provide. As mentioned above, the issue happens randomly.

**Expected behavior**
nullptr should not be accessed.

**Comment by bretambrose** [comment]
Can you upgrade to the latest version and retry?  There have been a lot of stability fixes in the last 10 months.

**Comment by cpp-59487** [comment]
Hi @bretambrose,

I tried to build the upgraded version, but I found I have build issue #258. Could you help take a look?

Thanks.

**Comment by bretambrose** [comment]
The shared libs build issue should be addressed with the latest release.
