### ISSUE TITLE
Does anyone also having problem with setting c++ standard to c++17 to run the example code

### ISSUE THREAD

**Issue by mayurpatelgec** [aws/aws-iot-device-sdk-cpp-v2#262]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Ubuntu 20.04
SDK: v1.10.5
https://github.com/aws/aws-iot-device-sdk-cpp-v2/releases/tag/v1.10.5

**Describe the question**
I wanted to test the example **basic-pub-sub** code which is given here:
https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples/mqtt/basic_pub_sub

I got it working without any problem with AWS connection and with proper certificates and so on, but as soon as i changed the c++ standard from 14 to 17, _the code compiles without any problem but doesn't run and exits/crashes._

I HAVE CHANGED NOTHING ELSE IN THE CODE 

Here is the place where I changed the c++ standard to 17 and set higher CMake version 3.18
https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/main/samples/mqtt/basic_pub_sub/CMakeLists.txt#L12

**output:**
_c++14_
```
Connecting...
Connection completed successfully.Subscribe on topic test on packetId 1 Succeeded
Enter the message you want to publish to topic test and press enter. Enter 'exit' to exit this program.
```

_c++17_
```
Client Configuration initialization failed with error aws-c-common: AWS_ERROR_SUCCESS, Success.
```

What am I doing wrong or missing anything here?
Thank you in advance.

**Comment by jmklix** [comment]
What exact cmake version did you use? 

I tested this with 3.20.2 and ran it successfully.

**Comment by mayurpatelgec** [comment]
Hi,

thank you for the answer. sorry I was lil busy so coudnt answer fast.

I am using CMake version 3.18 as I described in que.

**Comment by jmklix** [comment]
Can you try updating to the latest version of cmake to see if that works?
