### ISSUE TITLE
error for minimum compiler version for release 1.12.5 in cmake

### ISSUE THREAD

**Issue by mayurpatelgec** [aws/aws-iot-device-sdk-cpp-v2#267]
Confirm by changing [ ] to [x] below:
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?

here is my **test setup**.
**SDK** : 1.12.5
**CMake** : 3.16
**g++** : 9.3.0

**Describe the question**
 I want to compile current release V1.12.5 SDK
 I am getting checked error for gcc compiler. 9.3.0.
as per my knowledge it should work with very older versions then this.
![image](https://user-images.githubusercontent.com/26649420/117635333-01db1f80-b180-11eb-99b7-1ef3c18f6615.png)

can anyone confirm if this is still correct as min. requirement?
_Minimum Requirements
C++ 11 or higher
CMake 3.1+
Clang 3.9+ or GCC 4.4+ or MSVC 2015+_

**Comment by bretambrose** [comment]
Personally, I would prefer aws-lc to add the reasoning (visible in CMakeLists.txt) to the output message.

**Comment by samlaf** [comment]
+1 for adding this information to the docs... I wasted a lot of time on this before finding this closed issue...
