### ISSUE TITLE
Allow restricting schannel ciphers with SCH_USE_STRONG_CRYPTO

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#268]
Hi, can you please expose a way to set SCH_USE_STRONG_CRYPTO flag in order to restrict the used schannel ciphers to strong ones? same as curl, see here (at the bottom of the page):
https://curl.se/docs/ssl-ciphers.html

Thanks

**Comment by elad-ep** [comment]
Also, can you please support setting specific ciphers when using mac SecureTransport? (similar to https://curl.se/libcurl/c/CURLOPT_SSL_CIPHER_LIST.html option)

**Comment by elad-ep** [comment]
any update please?

**Comment by bretambrose** [comment]
We are going to enable SCH_USE_STRONG_CRYPTO by default in a near-future PR.  

On the other hand, I don't know of any plans with respect to specific cipher selection.

**Comment by elad-ep** [comment]
is this (SCH_USE_STRONG_CRYPTO by default) already inside the code?

**Comment by bretambrose** [comment]
I think that PR is currently side-lined atm (https://github.com/awslabs/aws-c-io/pull/414/files#diff-deba7570df70a36e386d3408da80adc8ac3cea8da4e405c92cdcdf99c290cf13R1971).  I can look into reviving it, mostly a matter of intersecting the additional tls tests across all platforms

**Comment by elad-ep** [comment]
if you can handle and merge this into next release it will be great... thanks!

**Comment by bretambrose** [comment]
This has been merged into aws-c-io, but I don't have an ETA for the SDK release.  Will depend on feature work.

**Comment by elad-ep** [comment]
is it now in released SDK version 1.15.2?

**Comment by jmklix** [comment]
Yes, this is in version 1.15.2
