### ISSUE TITLE
Could I use the basic subpub sample in this cpp sdk to subscribe a reserved topic?

### ISSUE THREAD

**Issue by YSUN-coder** [aws/aws-iot-device-sdk-cpp-v2#269]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on? Jetson Nano, Ubuntu

**Describe the question**

I am trying to create a IoT secure tunnel between my PC and Jetson Nano as the edge device.
As the instruction in IoT agent snippet(https://docs.aws.amazon.com/iot/latest/developerguide/agent-snippet.html): 

**The IoT agent is used to receive the MQTT message that includes the client access token and start a local proxy on the remote device. You must install and run the IoT agent on the remote device if you want the Secure Tunneling service to deliver the client access token. The IoT agent must subscribe to the following reserved IoT MQTT topic:

'$aws/things/thing-name/tunnels/notify'

(Where thing-name is the name of IoT thing associated with the remote device.)**

Could I use a sample in this repo as the IoT agent? Could the basic subpub could be used for subscribe to the following reserved IoT MQTT topic?

nano@nano2:~/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/samples/mqtt/basic_pub_sub/build$  **/.basic-pub-sub --endpoint........ --topic $aws/things/test_secure_tunnel_IoT/tunnels/notify**
Connecting...
Connection completed successfully.Subscribe on topic /things/test_secure_tunnel_IoT/tunnels/notify on packetId 1 Succeeded
Enter the message you want to publish to topic /things/test_secure_tunnel_IoT/tunnels/notify and press enter. Enter 'exit' to exit this program.

This subscribe seems cannot get notified.

Could you give me some instructions about how to build a simple IoT agent to work with the Secure Tunneling service?

**Comment by jmklix** [comment]
After you start the program can you try publishing to that topic with the aws console? In the left menu on the aws console you will find `MQTT test client`, and then use this to publish to `/things/test_secure_tunnel_IoT/tunnels/notify` to see if you can correctly receive these messages.

**Comment by YSUN-coder** [comment]
> After you start the program can you try publishing to that topic with the aws console? In the left menu on the aws console you will find `MQTT test client`, and then use this to publish to `/things/test_secure_tunnel_IoT/tunnels/notify` to see if you can correctly receive these messages.

Yes, I get messages in subscribed topic: /things/test_secure_tunnel_IoT/tunnels/notify if I send a MQTT message to topic: /things/test_secure_tunnel_IoT/tunnels/notify. But, if I add $aws in sender side, it won't work.

**Comment by YSUN-coder** [comment]
> I think this is just an error in the basic_pub_sub sample. When I removed the user input and instead used a hardcoded message I was able to both subscribe and publish messages to the AWS console.

Do you mean subscribe and publish for the reserved topic with '$aws' at the topic's head? Could you tell me more details about how to using the hardcoded message?

**Comment by jmklix** [comment]
Ignore my previous comment, I think I was using a modified version of the pubsub that I had been testing something else. That being said I downloaded and installed a fresh version of this sdk and have no issues using this full topic `$aws/things/test_secure_tunnel_IoT/tunnels/notify`. 

Can you try running it on something other than your Jetson Nano. Also please include the logging output from you Jetson Nano which can be enabled with: `apiHandle.InitializeLogging(Aws::Crt::LogLevel::Trace, stderr);`
