### ISSUE TITLE
cmake not possible without sudo rights due to libcrypto

### ISSUE THREAD

**Issue by mayurpatelgec** [aws/aws-iot-device-sdk-cpp-v2#277]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Host: Ubuntu:20.04
g++ 8.4
SDK: V1.12.6

**Describe the question**
I am trying to compile aws sdk as per Readme.
but i am not able to compile it without sudo rights because target libcrypto wants to compile and and install its libs diretcly in host system when i call CMAKE command which is i think from my point of view not good. if I give sudo rights than it works and than after complete build folder becomes with sudo rights. after that make command must be also with sudo. Where am I going wrong?

Is it possible to compile complete sdk without sudo permissions and without libcrypto (taking from standard libssl-dev)? it was not the case with old sdk like 1.10.x

![image](https://user-images.githubusercontent.com/26649420/119092761-1e444b00-ba0f-11eb-8655-d72688dfbe07.png)

Thanks in advances.

**Comment by bretambrose** [comment]
add -DCMAKE_INSTALL_PREFIX=<dir> to your command line and aws-lc's libcrypto will go there instead.

**Comment by mayurpatelgec** [comment]
ok. thank you. so with that i am closing this.
