### ISSUE TITLE
AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed from aws-c-io when connecting inside a container

### ISSUE THREAD

**Issue by angrdtsk** [aws/aws-iot-device-sdk-cpp-v2#278]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Debian 9

**Describe the question**
I have written an AWS client program and some tests for it and it all works when I run it under Debian 9. When I try building and running it inside a Docker container based on Ubuntu Bionic, I get the error that is in the topic.

When I try just the connection using mosquitto_pub, it works both outside and inside the container:
mosquitto_pub -h my_endpoint --cert cert.pem --key private.key -t topic1 -m "{}" -i some_id --cafile /etc/ssl/certs/Amazon_Root_CA_1.pem -p 8883 -d
Client some_id sending CONNECT
Client some_id received CONNACK
Client some_id sending PUBLISH (d0, q0, r0, m1, 'topic1', ... (2 bytes))
Client some_id sending DISCONNECT

It seems that the container is causing some trouble, but because mosquitto_pub works inside of it too, I wonder if that problem is somehow related to the SDK or how I am using it.

**Comment by bretambrose** [comment]
Can you enable trace logs and include them?

**Comment by angrdtsk** [comment]
I turned on the logs and got a line saying Certificate is untrusted.

However, I got this solved by changing the base of the container from Ubuntu Bionic to Debian 9. No other changes were needed.

**Comment by jmklix** [comment]
Glad you where able to find a solution. Please let us know if you run into any other issues with this sdk.
