### ISSUE TITLE
aesni-x86.S  Error

### ISSUE THREAD

**Issue by wildwindyevan** [aws/aws-iot-device-sdk-cpp-v2#283]
**Platform/OS/Device**
Toolchain : arm-poky-linux-gnueabi
Platform :NXP  imx6 A9
**Describe the question**
after step: "cmake --build . --target install " ,I got this error : 
/home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build/crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/**aesni-x86.S:2513: Error: junk at end of line, first unrecognized character is `,'**
crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/build.make:88: recipe for target 'crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o' failed

I  attached the log:
root@xxylin-virtual-machine:/home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build# cmake -DCMAKE_INSTALL_PREFIX="/home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/install" -DCMAKE_BUILD_TYPE="Debug" ../aws-iot-device-sdk-cpp-v2
-- AWS CRT C++ v1.0.0-dev
-- CMake 3.15.2
-- Packaging currently only supported on Fedora.
-- Checking for module 'libunwind-generic'
--   No package 'libunwind-generic' found
libunwind not found. Disabling unwind tests.
-- Go not found. Disabling some code generation and using pre-generated code in generated-src/
-- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
-- Test stdalign_check.c passed, enabling AWS_LC_STDALIGN_AVAILABLE
-- Test builtin_swap_check.c passed, enabling AWS_LC_BUILTIN_SWAP_SUPPORTED
-- The ASM compiler identification is GNU
-- Found assembler: /opt/poky/1.7/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
Copying platform assembly files from /home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-lc/generated-src/linux-x86/crypto/ to /home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build/crt/aws-crt-cpp/crt/aws-lc/crypto
-- S2N found target: crypto
-- Using libcrypto from AWS-LC
-- Performing Test AWS_ARM32_CRC
-- Performing Test AWS_ARM32_CRC - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build
root@xxylin-virtual-machine:/home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build# cmake --build . --target install --config "Debug"
Scanning dependencies of target aws-c-common
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator_sba.c.o
..............
[  6%] Linking C static library libaws-c-common.a
[  6%] Built target aws-c-common
Scanning dependencies of target aws-c-compression
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/compression.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman.c.o
[  6%] Linking C static library libaws-c-compression.a
[  6%] Built target aws-c-compression
Scanning dependencies of target global_target
[  6%] Built target global_target
Scanning dependencies of target fipsmodule
[  6%] Building C object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/bcm.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/fips_shared_support.c.o
[  6%] Building ASM object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o
/home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build/crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/aesni-x86.S: Assembler messages:
/home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build/crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/aesni-x86.S:2513: Error: junk at end of line, first unrecognized character is `,'
crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/build.make:88: recipe for target 'crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o' failed
make[2]: *** [crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o] Error 1
CMakeFiles/Makefile2:1146: recipe for target 'crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/all' failed
make[1]: *** [crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
root@xxylin-virtual-machine:/home/wildwindy/NFS/AWSSDK/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build#

**Comment by bretambrose** [comment]
This is an issue with the aws-lc submodule build.  I would bring this issue up on their repo: https://github.com/awslabs/aws-lc

**Comment by wildwindyevan** [comment]
in  https://github.com/awslabs/aws-lc,I did not see the issue there, what did I miss ?

**Comment by bretambrose** [comment]
You need to create the issue.
