### ISSUE TITLE
ubuntu 20.04: s2n.a linking ssl library error

### ISSUE THREAD

**Issue by johnchienbronci** [aws/aws-iot-device-sdk-cpp-v2#284]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**

- [x]  I'm using ATS data type endpoint: the endpoint should look like <prefix>-ats.iot.<region>.amazonaws.com 

**Platform/OS/Device**
Ubuntu 20.04.2 LTS
SDK : 1.12.6
CMake : 3.16
g++/gcc : 10.2
system openssl: 1.1.1f (have found openssl in system)

* build aws-iot-device-sdk-cpp-v2 library scrip:
         cd aws-iot-device-sdk-cpp-v2-build
         cmake -DCMAKE_INSTALL_PREFIX=../libaws/ \\
        -DCMAKE_CXX_STANDARD=17 \\
        -DCMAKE_CXX_STANDARD_REQUIRED=True \\
        -DBUILD_DEPS=ON \\
        -DUSE_OPENSSL=ON \   #Set this if you want to use your system's OpenSSL 1.0.2/1.1.1
        -DCMAKE_BUILD_TYPE=Release \\
        ../aws-iot-device-sdk-cpp-v2
        cmake --build . --target install 
![image](https://user-images.githubusercontent.com/27708347/121111834-293a1080-c842-11eb-9cbe-ec62a8a6efbc.png)
![image](https://user-images.githubusercontent.com/27708347/121112480-0bb97680-c843-11eb-91af-deebb4f5e037.png)

program using s2n.a error 
![image](https://user-images.githubusercontent.com/27708347/121114999-1d9d1880-c847-11eb-972a-1bc8f10e65ce.png)

**Describe the question**
How to build aws-iot-device-cpp-v2 library and link system openssl
   - s2n.a reference old openssl version, because sk_value is old function (openssl old version in aws-lc)

**Comment by albdom** [comment]
I have similar compilation errors for the GreenGrass IPC example that I can't fix it.

Platform/OS/Device
Ubuntu 18.04.5 LTS
SDK : 1.14.1
CMake : 3.21.2
g++/gcc : 7.5.0

![image](https://user-images.githubusercontent.com/9395304/131299513-8198009e-c944-4760-9339-761b9d5d4fb9.png)
![image](https://user-images.githubusercontent.com/9395304/131299940-3abf3165-9c3b-4cdd-83ef-754b52b27d5e.png)

**Comment by jmklix** [comment]
Can you try upgrading your gcc version? I was able to successfully build/run with gcc 10.3.0
