### ISSUE TITLE
Cannot install libraries  on Ubuntu 20.04

### ISSUE THREAD

**Issue by AldoCF96** [aws/aws-iot-device-sdk-cpp-v2#285]
I am having this issue building it:

aldo@aldoXPS:~/git/aws-iot-device-sdk-cpp-v2-build$ cmake -DCMAKE_INSTALL_PREFIX=home/git/aws-libraries -DCMAKE_BUILD_TYPE=Debug ../aws-iot-device-sdk-cpp-v2
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.13.8
-- CMake 3.16.3
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Success
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Looking for pthread_attr_setaffinity_np
-- Looking for pthread_attr_setaffinity_np - found
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Building SIMD base64 decoder
-- Packaging currently only supported on Fedora.
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:45 (message):
  GCC 9.3.0 is not supported.

-- Configuring incomplete, errors occurred!
See also "/home/aldo/git/aws-iot-device-sdk-cpp-v2-build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeOutput.log".
CMake Error at crt/aws-crt-cpp/crt/aws-c-cal/cmake/modules/aws-lc.cmake:25 (message):
  Failed to configure aws-lc
Call Stack (most recent call first):
  crt/aws-crt-cpp/CMakeLists.txt:105 (include)

-- Configuring incomplete, errors occurred!
See also "/home/aldo/git/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeOutput.log".
See also "/home/aldo/git/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeError.log".

**Comment by jmklix** [comment]
I was able to install it when using gcc 10.2.0. Can you try updating that to see if it works for you.

**Comment by rpcme** [comment]
@jmklix the prerequisites clearly state the following compilers are supported.

```Clang 3.9+ or GCC 4.8+ or MSVC 2015+```

Could this be a parsing issue in the cmake file?

**Comment by jmklix** [comment]
It should be working with gcc 9.3.0, but I can confirm that using that version currently doesn't work. Currently looking into resolving this, but if you need it to work updating the gcc version will work.

**Comment by mayurpatelgec** [comment]
have a look at this. aws-lc has explicitly disbled some versions. I had the same error and invested too much time to find this.
hope it helps. as i said in d issue docs must mention this somewhere.

https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/267

**Comment by kokofirstlove** [comment]
> I am having this issue building it:
> 
> aldo@aldoXPS:~/git/aws-iot-device-sdk-cpp-v2-build$ cmake -DCMAKE_INSTALL_PREFIX=home/git/aws-libraries -DCMAKE_BUILD_TYPE=Debug ../aws-iot-device-sdk-cpp-v2 -- The C compiler identification is GNU 9.3.0 -- The CXX compiler identification is GNU 9.3.0 -- Check for working C compiler: /usr/bin/cc -- Check for working C compiler: /usr/bin/cc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Detecting C compile features -- Detecting C compile features - done -- Check for working CXX compiler: /usr/bin/c++ -- Check for working CXX compiler: /usr/bin/c++ -- works -- Detecting CXX compiler ABI info -- Detecting CXX compiler ABI info - done -- Detecting CXX compile features -- Detecting CXX compile features - done -- AWS CRT C++ v0.13.8 -- CMake 3.16.3 -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS -- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success -- Performing Test AWS_HAVE_MSVC_MULX -- Performing Test AWS_HAVE_MSVC_MULX - Failed -- Performing Test AWS_HAVE_WINAPI_DESKTOP -- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed -- Performing Test AWS_ARCH_INTEL -- Performing Test AWS_ARCH_INTEL - Success -- Performing Test AWS_ARCH_ARM64 -- Performing Test AWS_ARCH_ARM64 - Failed -- Performing Test AWS_ARCH_ARM32 -- Performing Test AWS_ARCH_ARM32 - Failed -- Performing Test AWS_HAVE_GCC_INLINE_ASM -- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success -- Performing Test AWS_HAVE_AUXV -- Performing Test AWS_HAVE_AUXV - Success -- Performing Test AWS_HAVE_EXECINFO -- Performing Test AWS_HAVE_EXECINFO - Success -- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW -- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW - Success -- Performing Test HAVE_M_AVX2_FLAG -- Performing Test HAVE_M_AVX2_FLAG - Success -- Performing Test HAVE_AVX2_INTRINSICS -- Performing Test HAVE_AVX2_INTRINSICS - Success -- Performing Test HAVE_MM256_EXTRACT_EPI64 -- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success -- Looking for pthread.h -- Looking for pthread.h - found -- Performing Test CMAKE_HAVE_LIBC_PTHREAD -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed -- Check if compiler accepts -pthread -- Check if compiler accepts -pthread - yes -- Found Threads: TRUE -- Performing Test HAS_MOUTLINE_ATOMICS -- Performing Test HAS_MOUTLINE_ATOMICS - Failed -- Looking for stdint.h -- Looking for stdint.h - found -- Looking for stdbool.h -- Looking for stdbool.h - found -- Performing Test HAS_WGNU -- Performing Test HAS_WGNU - Failed -- Performing Test HAVE_SYSCONF -- Performing Test HAVE_SYSCONF - Success -- Looking for pthread_attr_setaffinity_np -- Looking for pthread_attr_setaffinity_np - found -- Performing Test HAS_SANITIZERS -- Performing Test HAS_SANITIZERS - Failed -- Building SIMD base64 decoder -- Packaging currently only supported on Fedora. -- The C compiler identification is GNU 9.3.0 -- Check for working C compiler: /usr/bin/cc -- Check for working C compiler: /usr/bin/cc -- works -- Detecting C compiler ABI info -- Detecting C compiler ABI info - done -- Detecting C compile features -- Detecting C compile features - done CMake Error at CMakeLists.txt:45 (message): GCC 9.3.0 is not supported.
> 
> -- Configuring incomplete, errors occurred! See also "/home/aldo/git/aws-iot-device-sdk-cpp-v2-build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeOutput.log". CMake Error at crt/aws-crt-cpp/crt/aws-c-cal/cmake/modules/aws-lc.cmake:25 (message): Failed to configure aws-lc Call Stack (most recent call first): crt/aws-crt-cpp/CMakeLists.txt:105 (include)
> 
> -- Configuring incomplete, errors occurred! See also "/home/aldo/git/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeOutput.log". See also "/home/aldo/git/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeError.log".

**Comment by bretambrose** [comment]
aws-lc has relaxed their compiler constraints and this is no longer an issue
