### ISSUE TITLE
Greengrass discovery sample doesn't use message argument

### ISSUE THREAD

**Issue by FThompsonAWS** [aws/aws-iot-device-sdk-cpp-v2#286]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
The Greengrass discovery sample provides a command line argument, `message`, that it doesn't use. Instead, the sample asks for command line input at runtime for the message to send.

**Platform/OS/Device**
What are you running the sdk on?
Amazon Linux 2 (EC2)

**SDK version number**
v1.12.6

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

Run the discovery sample. The command line arguments (and expectations) differ from the behavior.

**Expected behavior**
The sample sends the message that you specify with the `message` argument, or the sample doesn't ask for a `message` argument.

For comparison with the other device SDKs, the discovery samples in Python and JavaScript SDKs ask for a message and publish it 10 times. The discovery sample in the Java SDK asks for command line input (similar to the sample in the C++ SDK).

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
ApiHandle::InitializeLogging(...)
```

**Additional context**

**Comment by jmklix** [comment]
Thanks for pointing this out. This is a documentation issue that needs to be fixed.

**Comment by kokofirstlove** [comment]
> Confirm by changing [ ] to [x] below to ensure that it's a bug:
> 
> * [x]  I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution
> 
> **Known Issue**
> 
> * [x]  I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
> 
> **Describe the bug** The Greengrass discovery sample provides a command line argument, `message`, that it doesn't use. Instead, the sample asks for command line input at runtime for the message to send.
> 
> **Platform/OS/Device** What are you running the sdk on? Amazon Linux 2 (EC2)
> 
> **SDK version number** v1.12.6
> 
> **To Reproduce (observed behavior)** Steps to reproduce the behavior (please share code)
> 
> Run the discovery sample. The command line arguments (and expectations) differ from the behavior.
> 
> **Expected behavior** The sample sends the message that you specify with the `message` argument, or the sample doesn't ask for a `message` argument.
> 
> For comparison with the other device SDKs, the discovery samples in Python and JavaScript SDKs ask for a message and publish it 10 times. The discovery sample in the Java SDK asks for command line input (similar to the sample in the C++ SDK).
> 
> **Logs/output** If applicable, add logs or error output.
> 
> _REMEMBER TO SANITIZE YOUR PERSONAL INFO_
> 
> ```
> ApiHandle::InitializeLogging(...)
> ```
> 
> **Additional context** Add any other context about the problem here.

**Comment by TwistedTwigleg** [comment]
This has been fixed in #432! Now if the `message` argument is passed, it will send the message 10 times (similar to Java), but if no message is set, then it will ask for a message (similar to Python and Javascript).
