### ISSUE TITLE
cross compile sdk   with arm64 toolchain about cmTC_faac0 error

### ISSUE THREAD

**Issue by dukezuoHZ** [aws/aws-iot-device-sdk-cpp-v2#288]
I have add some define in cmakelist for tool chain of arm64 ,when i run cmake,show error as below:

-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
-- Check for working C compiler: /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- broken
CMake Error at /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_faac0/fast"
    /usr/bin/make -f CMakeFiles/cmTC_faac0.dir/build.make CMakeFiles/cmTC_faac0.dir/build
    make[1]: Entering directory '/mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_faac0.dir/testCCompiler.c.o
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc   -O2 -pipe -g -feliminate-unused-debug-types   -fPIE   -o CMakeFiles/cmTC_faac0.dir/testCCompiler.c.o   -c /mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_faac0
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_faac0.dir/link.txt --verbose=1
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc  -O2 -pipe -g -feliminate-unused-debug-types    -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -rdynamic CMakeFiles/cmTC_faac0.dir/testCCompiler.c.o  -o cmTC_faac0 
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crt1.o: No such file or directory
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crti.o: No such file or directory
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crtbegin.o: No such file or directory
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc_s
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lc
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc_s
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crtend.o: No such file or directory
    /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crtn.o: No such file or directory
    collect2: error: ld returned 1 exit status
    CMakeFiles/cmTC_faac0.dir/build.make:97: recipe for target 'cmTC_faac0' failed
    make[1]: *** [cmTC_faac0] Error 1
    make[1]: Leaving directory '/mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_faac0/fast' failed
    make: *** [cmTC_faac0/fast] Error 2

**Comment by rpcme** [comment]
hello @anglely168 we do cover this sdk for Yocto Project in the meta-aws project https://github.com/aws/meta-aws.  However, it doesn't look like we have put it back to sumo likely due to the YP sumo release being maintained.

Do you think it would help if we tried to back port it to sumo?

**Comment by anglely168** [comment]
> hello @anglely168 we do cover this sdk for Yocto Project in the meta-aws project https://github.com/aws/meta-aws. However, it doesn't look like we have put it back to sumo likely due to the YP sumo release being maintained.
> 
> Do you think it would help if we tried to back port it to sumo?

Thinks rpcme,I rebuild the sdk and example in another arm64 platform native,and run the example basic-pub-sub ok,but when i go back imx8mm platform, it output :
Connecting...
Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed
。。。。。。
I am confused.I used the same bin file,why show different result?

**Comment by JonathanHenson** [comment]
My educated guess is the trust store wasn’t found on that distro. If you know the location of the ca location, we can make sure it loads for you in a future release. In the meantime, you can test this theory by overriding the CA with the AmazonRootCA1.PEM directly.

**Comment by anglely168** [comment]
> My educated guess is the trust store wasn’t found on that distro. If you know the location of the ca location, we can make sure it loads for you in a future release. In the meantime, you can test this theory by overriding the CA with the AmazonRootCA1.PEM directly.

I used the same certs on arm64 platform,but i get different output,I double libssl is different,but I used ldd comand to check to relaition lib,no find this lib and i change the name of libssl.so to a bak name,the a bin file can run too,so it seemed no relation to libss.

**Comment by anglely168** [comment]
I have resolved this issue,because the new board of imx8mm have no rtc,so i it handshake with aws lot server error,I have set date time manually and it works. thanks all!

**Comment by rpcme** [comment]
@anglely168 yes on these types of systems, to be effective, we need to have ntpd on the system,  For example, in the greengrass recipe ntpd is a hard prerequisite.  I'm glad you got it figured out.  If you need support on sumo please let us know over at the meta-aws project repo ok?

**Comment by anglely168** [comment]
thanks rpcme.I have compiled directly another arm64  device which have install gcc and can been run on imx8mm,I think you'd better write a instruction for someone who used others arm platform with hisself toolchian.I did't find doc about how to crosscompiler the sdk  in the internet.some arm platform did't used Yocto Project.

**Comment by rpcme** [comment]
Hi @anglely168 I agree there should be documentation. I assumed you were using YP since you were using the Poky SDK toolchain.

@justinboswell who do you think is the right person to write this up?  I can do it based on my experience in meta-aws (in which case you can assign this issue to me) or other?

**Comment by justinboswell** [comment]
> @justinboswell who do you think is the right person to write this up? I can do it based on my experience in meta-aws (in which case you can assign this issue to me) or other?

Yeah, @rpcme I think your experience will be most helpful in framing what we need. I'm happy to review and contribute on top of what you have.

**Comment by kokofirstlove** [comment]
> I have add some define in cmakelist for tool chain of arm64 ,when i run cmake,show error as below:
> 
> -- The C compiler identification is GNU 7.3.0 -- Check for working C compiler: /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- Check for working C compiler: /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- broken CMake Error at /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.10/Modules/CMakeTestCCompiler.cmake:52 (message): The C compiler
> 
> ```
> "/opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc"
> ```
> 
> is not able to compile a simple test program.
> 
> It fails with the following output:
> 
> ```
> Change Dir: /mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp
> 
> Run Build Command:"/usr/bin/make" "cmTC_faac0/fast"
> /usr/bin/make -f CMakeFiles/cmTC_faac0.dir/build.make CMakeFiles/cmTC_faac0.dir/build
> make[1]: Entering directory '/mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp'
> Building C object CMakeFiles/cmTC_faac0.dir/testCCompiler.c.o
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc   -O2 -pipe -g -feliminate-unused-debug-types   -fPIE   -o CMakeFiles/cmTC_faac0.dir/testCCompiler.c.o   -c /mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp/testCCompiler.c
> Linking C executable cmTC_faac0
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_faac0.dir/link.txt --verbose=1
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc  -O2 -pipe -g -feliminate-unused-debug-types    -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -rdynamic CMakeFiles/cmTC_faac0.dir/testCCompiler.c.o  -o cmTC_faac0 
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crt1.o: No such file or directory
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crti.o: No such file or directory
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crtbegin.o: No such file or directory
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc_s
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lc
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find -lgcc_s
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crtend.o: No such file or directory
> /opt/fsl-imx-xwayland/4.14-sumo/sysroots/x86_64-pokysdk-linux/usr/libexec/aarch64-poky-linux/gcc/aarch64-poky-linux/7.3.0/real-ld: cannot find crtn.o: No such file or directory
> collect2: error: ld returned 1 exit status
> CMakeFiles/cmTC_faac0.dir/build.make:97: recipe for target 'cmTC_faac0' failed
> make[1]: *** [cmTC_faac0] Error 1
> make[1]: Leaving directory '/mnt/hgfs/eyecloud/scouter/Luna-Gen1-IoT-Device/src/aws-iot-device-sdk-cpp-v2/build/crt/aws-crt-cpp/aws-lc/CMakeFiles/CMakeTmp'
> Makefile:126: recipe for target 'cmTC_faac0/fast' failed
> make: *** [cmTC_faac0/fast] Error 2
> ```

**Comment by Hadatko** [comment]
I have similar issue with building on Linux laptop. See comment under main post here : https://github.com/aws/s2n-tls/issues/3495

**Comment by jmklix** [comment]
Please check out the [meta-aws](https://github.com/aws4embeddedlinux/meta-aws) for more documentation/questions relating to this specific use case
