### ISSUE TITLE
Connection Failure to AWS IoT Core

### ISSUE THREAD

**Issue by MarcoCapozzoKebula** [aws/aws-iot-device-sdk-cpp-v2#291]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
I compiled the sample "mqtt/basic-pub-sub", but when I try to run the executable, I get the error "AWS_ERROR_MQTT_INVALID_RESERVED_BITS", raised by "libaws-c-mqtt" library.
I was trying to run this sample because the software that I coded raised the same error.
![Bug](https://user-images.githubusercontent.com/83069698/123978558-3faa3680-d9c0-11eb-8b58-c71b10955669.png)

**Platform/OS/Device**
Microsoft Windows 10 (64 bit)

**SDK version number**
v0.14.1

**Comment by bretambrose** [comment]
Your best bet here is to step through the code and work backwards to figure out why it's being raised.  That error is when an mqtt packet is received that has bits set that shouldn't be.  I don't expect IoT Core to ever actually send an mqtt packet with those properties so its a likely indicator that there's a mismatch between the internal state of the client connection and the data stream coming in.

Trace level sdk logs and even a wireshark packet capture may also help diagnose this.  I've only seen something like this back when debugging issues with double tls connections and garbage data was getting passed to the mqtt layer.

**Comment by MarcoCapozzoKebula** [comment]
I undestand the problem but how can I fix it? The mqtt packet is created by the Mqtt Client itself.

**Comment by bretambrose** [comment]
In 4 out of the 5 cases where that error is raised, it is not created by the client itself, it is raised in a decode of the byte stream from the remote peer, hence the need for more information/context.

**Comment by MarcoCapozzoKebula** [comment]
I try to capture the packet with Wireshark, but it does not appear. I imagine that is cause by the fact that maybe the packet is never sent, because it's not well-formatted.

**Comment by bretambrose** [comment]
Can you give a call stack (of the point where the error is being raised) and trace level logs?

**Comment by bretambrose** [comment]
Also, with respect to wireshark, no mqtt logic will be executed until the tls handshake is complete.  If you're not seeing anything in a packet trace then it's likely that your capture/config is incorrect somehow.

**Comment by MarcoCapozzoKebula** [comment]
I find out the error! The endpoint set was incorrect. 
If I can give an advice, try to organize well the documentation, it's really hard to get started with the services offered. 
Anyway thank you for the support!
