### ISSUE TITLE
Not able to crosscompile for armv7l

### ISSUE THREAD

**Issue by josecgon** [aws/aws-iot-device-sdk-cpp-v2#293]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on? armv7l

**Describe the question**

Hello!

I'm trying to crosscompile the code (main branch) for an armv7l

To start, I was following the instructions, and with the following script I compiled ir for x86_64 with no problems:

```
#!/bin/sh

WORKSPACE=/home/jose/repos/sdk-cpp-workspace
BUILD_TYPE="Debug"

cmake -DCMAKE_INSTALL_PREFIX=$WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_DEPS=ON ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install --config $BUILD_TYPE
```

So then, I created a new script to crosscompile using a toolchain that I'm already using to crosscompile another projects:

```
#!/bin/sh

WORKSPACE=/home/jose/repos/sdk-cpp-workspace
BUILD_TYPE="Debug"

. /opt/poky/2.2.2/environment-setup-cortexa7hf-neon-vfpv4-poky-linux-gnueabi
cmake -DCMAKE_PREFIX_PATH=$WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_TOOLCHAIN_FILE=TRUE -DDISCARD_USER_INCLUDE=TRUE ../aws-iot-device-sdk-cpp-v2 
cmake --build . --target install
```

And I get the next output:

```
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
-- Check for working C compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++
-- Check for working CXX compiler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.14.1
-- CMake 3.16.3
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Success
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW
-- Performing Test AWS_SHOULD_DISABLE_STRINGOP_OVERFLOW - Failed
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT - Failed
-- Performing Test HAS_64BIT_FILE_OFFSET_VIA_DEFINES
-- Performing Test HAS_64BIT_FILE_OFFSET_VIA_DEFINES - Success
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Looking for pthread_attr_setaffinity_np
-- Looking for pthread_attr_setaffinity_np - found
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Checking for module 'libunwind-generic'
--   No package 'libunwind-generic' found
libunwind not found. Disabling unwind tests.
-- Go not found. Disabling some code generation and using pre-generated code in generated-src/
-- Perl not found. Disabling some code generation and using pre-generated code in generated-src/
-- Test stdalign_check.c passed, enabling AWS_LC_STDALIGN_AVAILABLE
-- Test builtin_swap_check.c passed, enabling AWS_LC_BUILTIN_SWAP_SUPPORTED
-- The ASM compiler identification is GNU
-- Found assembler: /opt/poky/2.2.2/sysroots/x86_64-pokysdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
Copying platform assembly files from /home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-lc/generated-src/linux-x86/crypto/ to /home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build/crt/aws-crt-cpp/crt/aws-lc/crypto
-- S2N found target: crypto
-- Using libcrypto from AWS-LC
-- Performing Test AWS_ARM32_CRC
-- Performing Test AWS_ARM32_CRC - Failed
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    DISCARD_USER_INCLUDE
    USE_TOOLCHAIN_FILE


-- Build files have been written to: /home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build
Scanning dependencies of target aws-c-common
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/allocator_sba.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/arch/arm/asm/cpuid.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/array_list.c.o
[  0%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/assert.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/byte_buf.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/cache.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/codegen.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/command_line_parser.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/common.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/condition_variable.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/date_time.c.o
[  1%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/device_random.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/encoding.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/error.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/fifo_cache.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/hash_table.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/lifo_cache.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/linked_hash_table.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_channel.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_formatter.c.o
[  2%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/log_writer.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/logging.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/lru_cache.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/math.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/memtrace.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/clock.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/condition_variable.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/device_random.c.o
[  3%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/environment.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/file.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/mutex.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/process.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/rw_lock.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/system_info.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/thread.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/posix/time.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/priority_queue.c.o
[  4%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/process_common.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/promise.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/ref_count.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/resource_name.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/ring_buffer.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/statistics.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/string.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/task_scheduler.c.o
[  5%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/thread_scheduler.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/thread_shared.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/uuid.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-common/CMakeFiles/aws-c-common.dir/source/xml_parser.c.o
[  6%] Linking C static library libaws-c-common.a
[  6%] Built target aws-c-common
Scanning dependencies of target aws-c-compression
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/compression.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman_testing.c.o
[  6%] Linking C static library libaws-c-compression.a
[  6%] Built target aws-c-compression
Scanning dependencies of target global_target
[  6%] Built target global_target
Scanning dependencies of target fipsmodule
[  6%] Building C object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/bcm.c.o
[  6%] Building C object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/fips_shared_support.c.o
[  6%] Building ASM object crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o
/home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build/crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/aesni-x86.S: Assembler messages:
/home/jose/repos/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-cross-build/crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/aesni-x86.S:2513: Error: junk at end of line, first unrecognized character is `,'
make[2]: *** [crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/build.make:89: crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/aesni-x86.S.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1621: crt/aws-crt-cpp/crt/aws-lc/crypto/fipsmodule/CMakeFiles/fipsmodule.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

Am I doing something wrong to crosscompile it? Or there is any bug in this process?

Thank you very much!

**Comment by bretambrose** [comment]
It looks like your error comes from the aws-lc submodule where it's trying to compile an x86 assembly file.  So either something about the target architecture isn't being pushed through to the aws-lc build or aws-lc itself has an issue building for arm.  I would open an issue on their repository: https://github.com/awslabs/aws-lc

**Comment by josecgon** [comment]
Ok, thank you very much, I already opened an issue in their repository

**Comment by machadothi** [comment]
Helo all.
I'm trying to cross compile the SDK for ARMv8 64bits for days with no success. I did compile it for my host machine though.
I'm running Ubuntu 20 on my host, my target is a custom linux distro with 4 ARM A53 cores.
Couldn't find anywhere instructions to successfully compile the SDK and sample project for embedded linux devices.
Could you guys please share some instructions to make it work?
Already tryed:

- cmake -DCMAKE_INSTALL_PREFIX="/home/machado/git/sdk-cpp-workspace/" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_CXX_STANDARD="aarch64-linux-gnu-g++" ../aws-iot-device-sdk-cpp-v2

Thanks in advance!

**Comment by josecgon** [comment]
Hello Machadothi.

I was finally able to crosscompile it using poky, at the end what I did was and script executing those lines:

```
. /opt/poky/2.2.2/environment-setup-cortexa7hf-neon-vfpv4-poky-linux-gnueabi
cmake -DCMAKE_INSTALL_PREFIX="/opt/poky/2.2.2/sysroots/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/usr" -DUSE_TOOLCHAIN_FILE=TRUE -DCMAKE_BUILD_TYPE="Release" ../
sudo cmake --build . --target install
```

In this environment file I set up the CXX to use the arm compiler

It is quite important the `CMAKE_INSTALL_PREFIX` variable, when compiling the library it will create a `lib`, an `include` and a `bin` folder, and it must be pointing where your crosscompiler will look to search for them (in my case in the poky folder)

I hope it will help you

**Comment by rpcme** [comment]
@josecgon if you are using Yocto Project you can use this layer.

https://github.com/aws/meta-aws

**Comment by machadothi** [comment]
Hello @josecgon, appreciate your sugestion!
Here is my build-script:
`. /opt/fsl-imx-xwayland/5.4-zeus/environment-setup-aarch64-poky-linux
cmake -DCMAKE_INSTALL_PREFIX="/opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr" -DUSE_TOOLCHAIN_FILE=TRUE -DCMAKE_BUILD_TYPE="Release" -DBUILD_SAMPLES=ON ../aws-iot-device-sdk-cpp-v2
sudo cmake --build . --target install
`
Unfortunately I still wasn't able to make it work. Here is the script output:
`
-- Toolchain file defaulted to '/opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake/OEToolchainConfig.cmake'
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc
-- Check for working C compiler: /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++
-- Check for working CXX compiler: /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/bin/aarch64-poky-linux/aarch64-poky-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.14.4
-- CMake 3.15.3
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Failed
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Success
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Failed
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Failed
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test HAS_FPIC_FLAG
-- Performing Test HAS_FPIC_FLAG - Success
-- Performing Test HAS_MOUTLINE_ATOMICS
-- Performing Test HAS_MOUTLINE_ATOMICS - Failed
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT - Success
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Looking for pthread_attr_setaffinity_np
-- Looking for pthread_attr_setaffinity_np - found
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Packaging currently only supported on Fedora.
-- Performing Test HAS_WNO_STRINGOP_OVERFLOW
-- Performing Test HAS_WNO_STRINGOP_OVERFLOW - Success
-- Performing Test HAS_WNO_ARRAY_PARAMETER
-- Performing Test HAS_WNO_ARRAY_PARAMETER - Success
CMake Error at crt/aws-crt-cpp/crt/aws-lc/CMakeLists.txt:45 (message):
  GCC 9.2.0 is not supported.


-- Configuring incomplete, errors occurred!
See also "/home/machado/git/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeOutput.log".
See also "/home/machado/git/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'install'.  Stop.
(reverse-i-search)`ln': ^C -s ~/build-aws-64 

`

**Comment by bretambrose** [comment]
Can you try updating the aws-lc submodule to the tip of main and see if you are able to proceed farther?

```
cd crt/aws-lc
git fetch
git checkout main
git pull origin main
```

The current aws-lc submodule snapshot will refuse to compile for certain versions of gcc.  The latest aws-lc performs a more exhaustive/accurate check on the compiler and rather than refusing, instead just issues a warning.

In the meantime, we'll look into updating aws-lc in aws-crt-cpp/sdk-v2 to make this lenience official.

**Comment by machadothi** [comment]
@bretambrose many thanks. Now I was able to compile the SDK, but now, trying to compile a sample project, I get the error:

AIN_FILE=TRUE -DCMAKE_BUILD_TYPE="Release" -DBUILD_SAMPLES=ON ..
CMake Error at /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.15/Modules/FindThreads.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr/lib64/s2n/cmake/s2n-config.cmake:5 (find_package)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr/lib64/aws-c-io/cmake/aws-c-io-config.cmake:4 (find_dependency)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr/lib64/aws-c-http/cmake/aws-c-http-config.cmake:3 (find_dependency)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/x86_64-pokysdk-linux/usr/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr/lib64/aws-crt-cpp/cmake/aws-crt-cpp-config.cmake:3 (find_dependency)
  CMakeLists.txt:21 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/machado/git/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/samples/mqtt/basic_pub_sub/CMakeFiles/CMakeOutput.log".
See also "/home/machado/git/sdk-cpp-workspace/aws-iot-device-sdk-cpp-v2/samples/mqtt/basic_pub_sub/CMakeFiles/CMakeError.log".

To compile a sample project, I followed the below stes:
1 - go to a sample project directory
2 - make a directory "build" (mkdir build)
3 - inside that folder: 

- 3.1)  . /opt/fsl-imx-xwayland/5.4-zeus/environment-setup-aarch64-poky-linux 
- 3.2) cmake -DCMAKE_INSTALL_PREFIX="/opt/fsl-imx-xwayland/5.4-zeus/sysroots/aarch64-poky-linux/usr" -DUSE_TOOLCHAIN_FILE=TRUE -DCMAKE_BUILD_TYPE="Release" -DBUILD_SAMPLES=ON ..

**Comment by bretambrose** [comment]
You'll need to set CMAKE_PREFIX_PATH to wherever you installed the SDK build.
