### ISSUE TITLE
Keeping MQTT connection live forever and getting callback on internet unavailability

### ISSUE THREAD

**Issue by niranjankk12** [aws/aws-iot-device-sdk-cpp-v2#311]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Windows 10

**Describe the question**
We want to keep the mqtt connection live with AWS IoT core as soon as device comes online to get notifications whenever a new shadow gets created, Also want to ensure if device is disconnected for a while it should get shadows created before connecting again to IoT core. I have tried using different values of keepAliveTimeSecs(5s, 30s, 1200s). i do get a callback on `OnConnectionInterrupted ` and `OnConnectionResumed`. Does this mean the connection is dropped say every 5s and SDK reconnects it, if `keepAliveTimeSecs` value is 5s? Also if i switch off the internet i don't get `OnConnectionInterrupted` is this expected behavior? how can we get a callback if connection is dropped because of internet unavailability?

To get new shadow created during device is offline we are planning to use HTTP ListNamThingShadow API, but we don't want to call the HTTP API very often and want to get notifications through live mqtt connection as long as device is online.

**Comment by bretambrose** [comment]
The SDK's view of a connection is completely at the mercy of the OS and the OS itself will not have an accurate view outside of well-ordered shutdowns (locally-initiated close, or receive a FIN or tls alert from the remote peer).  If the OS does not shutdown the socket then the SDK remains oblivious and to be honest it doesn't surprise me that a potentially-transient next-hop issue (shut off the internet by... disconnecting your router, etc...) doesn't immediately cause all sockets to be torn down -- connection health remains the domain of well-understood,simple aspects of the protocol (tcp, mqtt, etc...) and not additional heuristics layered on top.

You have both mqtt keep alive as well as tcp keep alive (https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/io/SocketOptions.h#L44) available to you.  There's a natural tendency to immediately jump to "let's make the keep alives really small so I can detect an outage much quicker" and that can end up working for you, but when you recast it mentally, what you're really doing is making your application much more sensitive to intermediate network issues, both long-term and transient, and that can have some real unexpected consequences that end up costing more than staying oblivious (tls handshakes are neither quick nor cheap on low-spec devices).

Ideally, if it's possible, the application architecture should be built around the tenets of both "network connections are unreliable" and "the local view of a network connection's health is unreliable"
