### ISSUE TITLE
ALPN support in MacOSX

### ISSUE THREAD

**Issue by aparnaJo** [aws/aws-iot-device-sdk-cpp-v2#318]
We are using SDK's method "IsAlpnSupported()" to know whether Mac supports ALPN or not however it returns false(0). 

It gives the same result in High Sierra, Mojave, Catalina, BigSur and Apple M1 Mac systems.

Does that mean Mac do not support ALPN or am i doing anything wrong?

**Comment by bretambrose** [comment]
The actual check is implemented here: https://github.com/awslabs/aws-c-io/blob/41ece56077f1a09eba7a00d0f9f69cf064790c22/source/darwin/secure_transport_tls_channel_handler.c#L45

Scanning it, it appears to require:
* Binary built on a OsX machine with a minimum version (depending on flavor).  I am unsure why this additional check is needed over just checking the result of dlsym.
* The SDK needs to be initialized (instantiate an ApiHandle object should do that).  This is what calls aws_tls_init_static_state().
* A successful dlsym of SSLSetALPNProtocols

It may be worth doing a verbose/instrumented (add message output to cmake) cmake build to output the os version and do a sanity check of the preprocessor logic.
