### ISSUE TITLE
Does "aws-iot-device-sdk-cpp-v2" support MQTT with Amazon Cognito authetication?

### ISSUE THREAD

**Issue by owang-invn** [aws/aws-iot-device-sdk-cpp-v2#319]
Hello! I just want to know if "aws-iot-device-sdk-cpp-v2" support MQTT with Amazon Cognito authetication?
We need to implement MQTT communication to the Amazon cloud with Amazon Cognito authetication to the identity pool on Linux. From the amazon website it seems to me that Amazon Cognito mobile SDK is only available for Android/iOS/Javascript, but not for C/C++ on Linux. Then I found this repo with MQTT support to the Amazon IoT cloud, but it seems no Amazon Cognito is supported. So I just want to double check if it's the case, and if it's not supported, do you know any C/C++ SDK to support MQTT+Amazon Cognito to the Amazon cloud? thanks a lot!

**Comment by jmklix** [comment]
It is possible to use Cognito with this sdk as discussed in this [issue](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/142). But as mentioned in that issue you will need to implement your own credentials provider wrapper for cognito, as we have not implemented it yet. Please let us know if you have any questions.

**Comment by owang-invn** [comment]
Thanks a lot for your quick reply and the info! @jmklix 
I'll have a look at this and let you know if there is any question. 
BTW, is there any plan or schedule when it will be officially implemented? Thanks!

**Comment by jmklix** [comment]
Bindings for Cognito have been added in this [PR](https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/483).
