### ISSUE TITLE
Create .dylib file for MacOs

### ISSUE THREAD

**Issue by Swapnali-Kulkarni** [aws/aws-iot-device-sdk-cpp-v2#320]
Hi, 

I want to create a dylib of the sdk to integrate in my macOS project. 
for that I have used following command.

- cmake -G Xcode -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="build_dir" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" ../aws-iot-device-sdk-cpp-v2

- xcodebuild -project aws-iot-device-sdk-cpp-v2.xcodeproj -target "aws-crt-cpp" -UseModernBuildSystem=YES

- cmake --build . --target install

however I am not able to add those in my Xcode project.
it shows me error -

dyld: Library not loaded: @rpath/libaws-crt-cpp.dylib
  Referenced from: /Users/swapnali/Library/Developer/Xcode/DerivedData/IOT_POC-efcuhuiwtydmsffcglzmoaxsmxbu/Build/Products/Debug/libIOT_POC
  Reason: image not found

is this a correct way to build .dylib files ? if yes then why I am unable to integrate it in my project ?

Thanks.

**Comment by jmklix** [comment]
Can you make sure to clone recursively:
`git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git` 

because it says that you are missing libaws-crt-cpp

**Comment by Swapnali-Kulkarni** [comment]
Hi

Yes I have clone repo with same command.

**Comment by jmklix** [comment]
Sorry, but I'm not familiar with xcode. How are you trying to add the sdk to your Xcode project? 

And just to make sure we're on the same page I don't get any errors when following the build commands you have listed above.
