### ISSUE TITLE
in disconnect lifecycle event the reason of disconnect is not correct.

### ISSUE THREAD

**Issue by niranjankk12** [aws/aws-iot-device-sdk-cpp-v2#325]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?

**Describe the question**
We have kept keepAliveTimeSecs to 30 seconds and its working as expected most of the devices but on one device we are getting interrupt and resume callbacks very frequently even though internet connection is stable. We check the activity log on AWS IoT core console but the reason for disconnection seems to contradictory and its not clear what is the reason for disconnection.

{
  "clientId": "ChnbZ1lQYJuJOzwRiNZ3167YjTGPs7t63ZxXq1iEUOQ",
  "timestamp": 1632753356761,
  "eventType": "disconnected",
  **"clientInitiatedDisconnect": false,**
  "sessionIdentifier": "28566f95-8c26-4de2-8654-7366830ab280",
  "principalIdentifier": "AROAWKPZISOKG6DDC5E5F:ChnbZ1lQYJuJOzwRiNZ3167YjTGPs7t63ZxXq1iEUOQ",
  **"disconnectReason": "CLIENT_INITIATED_DISCONNECT",**
  "versionNumber": 120
}

**Comment by jmklix** [comment]
What devices are you using? and is all of the software up to date or at least the same across all of them?

Can you also check the [CloudWatch logs](https://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html) to see what it says is causing the disconnect.
