### ISSUE TITLE
Upon network disconnect the reconnect attempts occurs in the busy loop taking 100% CPU

### ISSUE THREAD

**Issue by anatolyaliev** [aws/aws-iot-device-sdk-cpp-v2#331]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
We are using AWS SDK with custom credentials provider. When we disconnect the network - the AWS SDK goes into busy loop retrying the connection. It takes 100% CPU

**Platform/OS/Device**
MacOS 11.3

**SDK version number**
1.14.3

**To Reproduce (observed behavior)**
Disconnect the internet

**Expected behavior**
I expect the reconnect attempts with some significant timeout

**Logs/output**
Here is the recurring AWS SDK logging:

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

``
[awssdk_retrybusyloop.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/7331433/awssdk_retrybusyloop.log)
`
ApiHandle::InitializeLogging(...)
```

**Additional context**
Add any other context about the problem here.

**Comment by anatolyaliev** [comment]
Unfortunately I do not have a reliable reproduction. I happens after some time the network is disconnected, and it is quite complicated to catch.
(1) Attach logs from the beginning (if not too large,otherwise attach a snippet that starts from before the reconnect loop kicks in) See attached.
[awssdk1.log](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/7335658/awssdk1.log)

(2) What credentials provider are you using? - I'm not quite sure. We are sending http request to our backend component located on AWS cloud. Here is a getCredentials and destroy callbacks provided to the AWS SDK

static int getCredentials(
    aws_credentials_provider* aProvider,
    aws_on_get_credentials_callback_fn aCallback,
    void* aUserData)
{

      
    AWS* aws = (AWS*)aProvider->impl;

    APICredentials apiCredentials;
    if (aws->getUpdatedAPICredentials(apiCredentials) != 0)
    {
        logError( "Failed getting updated credentials for IoT");
        aCallback(nullptr, AWS_ERROR_UNKNOWN, aUserData);
        return AWS_OP_SUCCESS;
    }

    aws_credentials* credentials = aws_credentials_new(
        aProvider->allocator, 
        aws_byte_cursor_from_c_str(apiCredentials.mAPIAccessKey.c_str()), 
        aws_byte_cursor_from_c_str(apiCredentials.mAPISecretKey.c_str()),
        aws_byte_cursor_from_c_str(apiCredentials.mSessionToken.c_str()),
        apiCredentials.mExpiration);
    
    if (!credentials)
    {
        logError( "Failed creating aws_credentials");
        return AWS_OP_ERR;
    }

    logDebug( "Fetched updated credentials for IoT");

    aCallback(credentials, AWS_ERROR_SUCCESS, aUserData);
    aws_credentials_release(credentials);

    return AWS_OP_SUCCESS;
}

static void destroy(aws_credentials_provider* aProvider)
{
    aws_credentials_provider_invoke_shutdown_callback(aProvider);
    aws_mem_release(aProvider->allocator, aProvider);
}

(3) Set a breakpoint at https://github.com/awslabs/aws-c-auth/blob/main/source/signing.c#L104 and paste the callstack when you hit that location. - not possible.

(4) How are you disconnecting the network? - Just unplugging the LAN cable.

**Comment by anatolyaliev** [comment]
Hi, 
Are there any updates?

**Comment by jmklix** [comment]
@anatolyaliev has anything changed and have you been able to reliably reproduce this? That would greatly facilitate our ability to fix any problems caused by the sdk.
