### ISSUE TITLE
How to build libs2n.so properly?

### ISSUE THREAD

**Issue by zhaokai3000** [aws/aws-iot-device-sdk-cpp-v2#343]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
aarch64 GNU/linux development board.

**Describe the question**
I have a arm64 linux development board which I wan't to port aws iot sdk to it.
The whole build system use buildroot to build all packages.
There is a libopenssl package (openssl1.1.1) originally. By building this package, it would generate /usr/lib/libcrypto.so.1.1 and /usr/lib/libssl.so.1.1 into target directory and create symlink /usr/lib/libcrypto.so and /usr/lib/libssl.so which points to them. There're some other packages which depends on these two libraries to build.

If I build the aws iot device sdk after building the libopenssl package，it will generate new libcrypto.so and libssl.so and install to /usr/lib directory, which would cause build failure for other packages which depends on the original so files.

If I remove the new libcrypto.so created by aws iot device sdk build process, the application using libs2n.so will encounter build failure for missing some apis which the original libcrypto.so doesn't have.

So it seems that libs2n.so needs some api from aws iot libcrypto.so which the orignal libcrypto.so.1.1 doesn't have, and other packages needs some api from the orignal libcrypto.so.1.1 which the aws iot libcrypto.so doesn't have..

What's the proper way to deal with this?

I wonder if I could configure the aws iot sdk to build libcrypto and libssl statically and build the other libraries shared?

**Comment by zhaokai3000** [comment]
Here's my buildroot makefile for aws iot sdk:
AWS_IOT_DEVICE_SDK_CPP_V2_VERSION = v1.14.3
AWS_IOT_DEVICE_SDK_CPP_V2_SITE = $(TOPDIR)/package/lenovo/aws-iot-device-sdk-cpp-v2/src
AWS_IOT_DEVICE_SDK_CPP_V2_SITE_METHOD = local
AWS_IOT_DEVICE_SDK_CPP_V2_LICENSE = Apache-2.0
AWS_IOT_DEVICE_SDK_CPP_V2_LICENSE_FILES = LICENSE
AWS_IOT_DEVICE_SDK_CPP_V2_INSTALL_STAGING = YES
AWS_IOT_DEVICE_SDK_CPP_V2_INSTALL_TARGET = YES

AWS_IOT_DEVICE_SDK_CPP_V2_DEPENDENCIES = libcurl libopenssl

AWS_IOT_DEVICE_SDK_CPP_V2_SUPPORTS_IN_SOURCE_BUILD = NO

AWS_IOT_DEVICE_SDK_CPP_V2_PRE_CONFIGURE_HOOKS += AWS_IOT_DEVICE_SDK_CPP_V2_CMAKE_MOVE_HOOK

#define AWS_IOT_DEVICE_SDK_CPP_V2_CMAKE_MOVE_HOOK
#	mkdir $(@D)/build
#endef

$(eval $(cmake-package))

**Comment by zhaokai3000** [comment]
I tried to modify the CMakeLists.txt of aws iot sdk crypto and ssl library like the following and it seems to work.
--- a/aws-iot-device-sdk-cpp-v2/src/crt/aws-crt-cpp/crt/aws-lc/crypto/CMakeLists.txt
+++ b/aws-iot-device-sdk-cpp-v2/src/crt/aws-crt-cpp/crt/aws-lc/crypto/CMakeLists.txt
@@ -218,6 +218,8 @@ endif()
 add_library(
   crypto
 
+  STATIC
+
   asn1/a_bitstr.c
   asn1/a_bool.c
   asn1/a_d2i_fp.c
@@ -494,7 +496,7 @@ endif()
 if(USE_CUSTOM_LIBCXX)
   install(TARGETS libcxx libcxxabi
           EXPORT crypto-targets
-          ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
+          ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/static/
           LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
   )
   target_link_libraries(crypto libcxx)

--- a/aws-iot-device-sdk-cpp-v2/src/crt/aws-crt-cpp/crt/aws-lc/ssl/CMakeLists.txt
+++ b/aws-iot-device-sdk-cpp-v2/src/crt/aws-crt-cpp/crt/aws-lc/ssl/CMakeLists.txt
@@ -3,6 +3,8 @@ include_directories(../include)
 add_library(
   ssl
 
+  STATIC
+
   bio_ssl.cc
   d1_both.cc
   d1_lib.cc
@@ -73,7 +75,7 @@ endif()
 
 install(TARGETS ssl
         EXPORT ssl-targets
-        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
+        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}/static/
         LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
 )

**Comment by jmklix** [comment]
Is everything working properly for you with the changes you have made to the CMake files?

**Comment by zhaokai3000** [comment]
Yes, it seems ok now. Closing the issue.

**Comment by zhaokai3000** [comment]
After building libcrypto and libssl statically, the build seems good but I didn't check if the program functions is ok.
When I run the program, the program got an segmentation fault while calling something in libs2n.
```
(gdb) bt
#0  0x0000007f9d2565e4 in raise () from /lib/libc.so.6
#1  0x0000007f9d244a0c in abort () from /lib/libc.so.6
#2  0x0000007f9d28ef6c in ?? () from /lib/libc.so.6
#3  0x0000007f9d29556c in ?? () from /lib/libc.so.6
#4  0x0000007f9d2964c4 in ?? () from /lib/libc.so.6
#5  0x0000007f9cdb0408 in s2n_cert_chain_and_key_load_cns ()
   from /usr/lib/libs2n.so
#6  0x0000007f9cdb0664 in s2n_cert_chain_and_key_load ()
   from /usr/lib/libs2n.so
#7  0x0000007f9cdb0700 in s2n_cert_chain_and_key_load_pem ()
   from /usr/lib/libs2n.so
#8  0x0000007f9cde7e00 in s2n_config_add_cert_chain_and_key ()
   from /usr/lib/libs2n.so
#9  0x0000007f9cf9c10c in ?? () from /usr/lib/libaws-c-io.so.1.0.0
#10 0x0000007f9d9a2d94 in Aws::Crt::Io::TlsContext::TlsContext(Aws::Crt::Io::TlsContextOptions&, Aws::Crt::Io::TlsMode, aws_allocator*) ()
   from /usr/lib/libaws-crt-cpp.so
#11 0x0000007f9d9a41e0 in Aws::Iot::MqttClientConnectionConfigBuilder::Build()
    () from /usr/lib/libaws-crt-cpp.so
```

When I changed it back, the program is all ok..

So, can I build libs2n without building the crypto and ssl library include in the aws iot sdk source?
Are there any configuration options that could enable us to build it with customer libcrypto.so and libssl.so?

**Comment by zhaokai3000** [comment]
I read the makefiles in the sdk and finally found the following configure options does what I wanted:

AWS_IOT_DEVICE_SDK_CPP_V2_CONF_OPTS +=  \
        -DCMAKE_INSTALL_PREFIX=/usr/    \
        -DCMAKE_PREFIX_PATH=$(TARGET_DIR)/usr   \
        **-DSEARCH_LIBCRYPTO=ON   \
        -DBYO_CRYPTO=ON \
        -DUSE_OPENSSL=ON**
