### ISSUE TITLE
Keep one or more SubscribeToTopicOperation instances opened outside the function scope

### ISSUE THREAD

**Issue by OnlyOneMoreGeek** [aws/aws-iot-device-sdk-cpp-v2#345]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?

Linux x86

**Describe the question**

I have implemented an IPC wrapper class that handles pub/sub operations on the IPC. This wrapper has a function `subscribe_to_ipc(const char * ptr_c_topic)`  that creates a request, a handler and an operation.

The problem is that, when reaching the end of the function scope, the operation instance is destroyed and, therefore, the subscription is closed. I can't extend the scope to make a raw or smart pointer of a SubscribeToTopicOperations because is implemented as a non-copyable class. I also want to avoid making this function block the thread or create a thread for each subscription.

Which would be the correct way to keep an IPC SubscribeToTopicOperation opened in this case?

**Comment by bretambrose** [comment]
The base class is movable so we could probably add move support for the generated model shapes as well.

**Comment by OnlyOneMoreGeek** [comment]
> The base class is movable so we could probably add move support for the generated model shapes as well.

Thanks for the answer. It would be nice to point in the documentation that, for now, subscribing to an IPC topic is a blocking operation.

**Comment by bretambrose** [comment]
This should be addressed by https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/369 and release v1.15.2
