### ISSUE TITLE
Having Trouble Deserializing Job Document

### ISSUE THREAD

**Issue by suggestedfixes** [aws/aws-iot-device-sdk-cpp-v2#346]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on? Ubuntu 20.04 LTS x86_64

**Describe the question**
We were trying the samples/jobs/describe_job_execution/main.cpp sample, in addition, we would like to deserialize the job document in the response->Execution object close to line 235, we wonder if there is a method to print the job document?

**Comment by jmklix** [comment]
No, there is not method to print the job document built into the sdk. Is the json that you are getting in the improper format? What is causing you trouble when trying to deserialize the Job Document?

**Comment by suggestedfixes** [comment]
We have looked into converting the pointer to JsonView and converting it to a string by calling AsString(), but we had no luck on it.
http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_utils_1_1_json_1_1_json_view.html

**Comment by suggestedfixes** [comment]
We tried the following and it worked. Thanks, can be closed!
```
auto document = response->Execution->JobDocument;
auto documentView = document->View().WriteCompact(true);
fprintf(stdout, "Document: %s\n", documentView.c_str());
```
