### ISSUE TITLE
basic-pub-sub compare incoming message from subscribed stream

### ISSUE THREAD

**Issue by LimeLava** [aws/aws-iot-device-sdk-cpp-v2#354]
Confirm by changing [ ] to [x] below:
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Windows 10

**Describe the question**
I am working off the framework of the basic-pub-sub example and want to check incoming subscribed messages to any string. After looking through the documentation I can not figure out where the incoming message is stored before it output to the console displayed. Thanks ahead of time.

**Comment by wildwindyevan** [comment]
auto onMessage = [&](Mqtt::MqttConnection &,
                                        const String &topic,
                                        const ByteBuf &payload,
                                        bool /*dup*/,
                                        Mqtt::QOS /*qos*/,
                                        bool /*retain*/)

**Comment by LimeLava** [comment]
Do I need to compare the whole onMessage variable with the string I am comparing it against because when I compare the payload part it doesn't work for me? Below is the comparison I am making. 
```
auto onMessage = [&](Mqtt::MqttConnection&, const String& topic, const ByteBuf& byteBuf, bool /*dup*/, Mqtt::QOS /*qos*/, bool /*retain*/) {
            {
                std::lock_guard<std::mutex> lock(receiveMutex);
                ++receivedCount;
                fprintf(stdout, "Publish #%d received on topic %s\n", receivedCount, topic.c_str());
                fprintf(stdout, "Message: ");
                if (byteBuf.buffer == (const uint8_t *)"test"){

                    fwrite(byteBuf.buffer, 1, byteBuf.len, stdout);
                    
                }
                fprintf(stdout, "\n");
            }

            receiveSignal.notify_all();
        };
```

**Comment by wildwindyevan** [comment]
member "buffer"  in  aws_byte_buf   is type of uint8_t * .
You can not simply  operate "=="  to compare.

**Comment by LimeLava** [comment]
That helped me narrow down what I was looking for, thanks for the assistance. For future reference, this is what I ended up implementing.
```
auto onMessage = [&](Mqtt::MqttConnection&, const String& topic, const ByteBuf& byteBuf, bool /*dup*/, Mqtt::QOS /*qos*/, bool /*retain*/) {
            {
                std::lock_guard<std::mutex> lock(receiveMutex);
                ++receivedCount;
                fprintf(stdout, "Publish #%d received on topic %s\n", receivedCount, topic.c_str());
                fprintf(stdout, "Message: ");
                if (strncmp((const char*)byteBuf.buffer, "test", 4) == 0) {
                    fwrite(byteBuf.buffer, 1, byteBuf.len, stdout);
                }
                fprintf(stdout, "\n");
            }

            receiveSignal.notify_all();
        };
```
