### ISSUE TITLE
Offline buffering of messages for resilience

### ISSUE THREAD

**Issue by angrdtsk** [aws/aws-iot-device-sdk-cpp-v2#362]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Yocto Thud

**Describe the question**
I am thinking about the resilience of the program I am working on.

If I connect to the cloud with QoS set to "at least once", what is done outside my own code to ensure that messages sent by my own code eventually really get sent to the broker despite of temporary network problems? I mean, there is probably some buffering taking place, but what is the size of the buffer and can I affect it? Also, is the buffer only in memory and gets lost if my program terminates or it is or could it be backed on flash.

The data sent by my program to the cloud is not generated by the program itself. It receives it from other programs and just takes care of sending it to the cloud (publishing it using MQTT). It wouldn't be too difficult to implement a feature that my program would store all that data into a database (SQLite, for example) and keep it there until the cloud has acked it. I just wonder if that is necessary. What kind of buffering is already happening?

**Comment by jmklix** [comment]
QoS 1 - at least once guarantees that a message is delivered at least one time to the receiver. You can read more about the MQTT specs [here](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/)

The max queue size if UINT16_MAX (65,535) and can be found in the c code [here](https://github.com/awslabs/aws-c-mqtt/blob/0a70bf814845e487b7e4862af7ad9e4a1199b5f4/source/client_channel_handler.c#L825-L862). The buffer is only in memory and would get lost if the program terminates. Depending on your use case using a local database could be a good solution to avoiding any data loss. Does this answer all of your questions?

**Comment by angrdtsk** [comment]
> QoS 1 - at least once guarantees that a message is delivered at least one time to the receiver. You can read more about the MQTT specs [here](https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/)
> 
> The max queue size if UINT16_MAX (65,535) and can be found in the c code [here](https://github.com/awslabs/aws-c-mqtt/blob/0a70bf814845e487b7e4862af7ad9e4a1199b5f4/source/client_channel_handler.c#L825-L862). The buffer is only in memory and would get lost if the program terminates. Depending on your use case using a local database could be a good solution to avoiding any data loss. Does this answer all of your questions?

This answered all questions I have at this point. Thanks!
