### ISSUE TITLE
Changing the log level

### ISSUE THREAD

**Issue by David-Di-Lorenzo** [aws/aws-iot-device-sdk-cpp-v2#363]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
amd64/Ubuntu Linux/laptop

**Describe the question**
I am struggling to find a way to set the log level to trace, to debug a possible greengrass connection issue, and I could not find any help in the documentation:
the Aws::SDKOptions type, which was available in v1, is no longer there. By browsing through the code I saw that defining AWS_STATIC_LOG_LEVEL as AWS_LOG_LEVEL_TRACE could do the trick. However I tried both setting this on my user code, as well as supplying such an option to CMAKE_CXX_FLAGS when building the library, but I do not get any log from the application either way (I checked both standard output, working directory, and the /greengrass/v2/logs folder).
What is the correct procedure?

Thank you very much

**Comment by jmklix** [comment]
Try this:
```c++
apiHandle.InitializeLogging(Aws::Crt::LogLevel::Trace, stdout);
```

**Comment by David-Di-Lorenzo** [comment]
That worked, thank you
