### ISSUE TITLE
Digest proxy with required authentication does not work with proxystrategy with MQTT client

### ISSUE THREAD

**Issue by Amaracs** [aws/aws-iot-device-sdk-cpp-v2#365]
Hi,

I am trying to create an MQTT connection to a proxy server using the ProxyStrategy with configured Digest proxy with client authentication, but I always get the following error: `AWS_ERROR_HTTP_PROXY_CONNECT_FAILED`.  For my first try I tried to use the code from the sample from [here](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/main/samples/secure_tunneling/secure_tunnel/main.cpp). 

```c++
Aws::Crt::Http::HttpProxyStrategyBasicAuthConfig basicAuthConfig;
basicAuthConfig.ConnectionType = Aws::Crt::Http::AwsHttpProxyConnectionType::Tunneling;
basicAuthConfig.Username = proxyUserName.c_str();
basicAuthConfig.Password = proxyPassword.c_str();
proxyOptions.ProxyStrategy =
                Aws::Crt::Http::HttpProxyStrategy::CreateBasicHttpProxyStrategy(basicAuthConfig, Aws::Crt::g_allocator);
proxyOptions.AuthType = Aws::Crt::Http::AwsHttpProxyAuthenticationType::Basic;
```

Because as opposed to `HttpProxyStrategyAdaptiveConfig` it has username and password members, so it can be set. On the other hand I tried to use the `HttpProxyStrategyAdaptiveConfig` too, but I do not know how to set the proxy username and password and unfortunately I did not find anything useful to figure it out. I have the same issue with NTLM proxy too where authentication is necessary, but I do not have any idea how can I pass them. I welcome any hint or help here, thanks in advance.

**Comment by Amaracs** [comment]
I am still puzzled by this issue because I do not see any example, or even a test file which is calling the CreateAdaptiveHttpProxyStrategy function. Can I get a confirmation that these proxy types are even supported?

- Basic Auth 
- Digest Auth
- Forward
- NOIP
- NTLM/Negotiate (Kerberos)
- Socks
- SSL Inspection Proxy
- WPAD

Thanks in advance.

**Comment by bretambrose** [comment]
The v2 SDK supports http proxies either with no auth or basic auth.  Kerberos/NTLM support is possible, but we do not have examples or non-mocked integration tests for it.

**Comment by Amaracs** [comment]
Is there any hint or some documentation about how should I override these lambdas in the HttpProxyStrategy.h, because I have an NTLM/Kerberos auth proxy set up,  but I do not know how should I pass the username and password for the authentication to these functions. 

```
            struct AWS_CRT_CPP_API HttpProxyStrategyAdaptiveConfig
            {
                HttpProxyStrategyAdaptiveConfig() : KerberosGetToken(), NtlmGetCredential(), NtlmGetToken() {}

                KerberosGetTokenFunction KerberosGetToken;

                KerberosGetTokenFunction NtlmGetCredential;

                NtlmGetTokenFunction NtlmGetToken;
            };
```


Thank you for your time and your help in advance.

**Comment by Amaracs** [comment]
I tried to set the proxystrategy's basicauthpassword and basicauthusername, but I get errorCode: 3

This is what I tried:
`        Http::HttpClientConnectionProxyOptions proxyStrategy;
        Http::HttpProxyStrategyAdaptiveConfig adaptiveConfig;
        adaptiveConfig.KerberosGetToken = [](String& tmp) {
            return true;
        };
        adaptiveConfig.NtlmGetCredential = [](String& tmp) {
            return true;
        };
        adaptiveConfig.NtlmGetToken = [](const String& tmp, String& tmp1) {
            return true;
        };
        
        proxyStrategy.HostName =_proxyAuthenticator->hostName();
        proxyStrategy.Port = _proxyAuthenticator->port();

        proxyStrategy.ProxyStrategy = Http::HttpProxyStrategy::CreateAdaptiveHttpProxyStrategy(adaptiveConfig);
        proxyStrategy.BasicAuthPassword = "testpw";
        proxyStrategy.BasicAuthUsername = "test";

        configBuilder.WithHttpProxyOptions(proxyStrategy);`

Thanks again.

**Comment by bretambrose** [comment]
If you want to use basic auth, just use HttpProxyStrategy::CreateBasicHttpProxyStrategy()

**Comment by Amaracs** [comment]
Yes thank you, the basic auth proxy is working fine, but I am trying to find out the limitations of the proxy support with other auth proxies.

**Comment by jmklix** [comment]
As @bretambrose said we only support http proxies either with no auth or basic auth. You can look [here](https://docs.aws.amazon.com/iot/latest/developerguide/configure-local-proxy-web-proxy.html) for more documentation about proxies with AWS IoT. If you would like support for a specific proxy please create a feature request.
