### ISSUE TITLE
Connection failed with error aws-c-io: AWS_IO_SOCKET_TIMEOUT, socket operation timed out

### ISSUE THREAD

**Issue by vermaasingh** [aws/aws-iot-device-sdk-cpp-v2#366]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution]

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
My MQTT client device was connected to IOTCore and data was getting published continuously, but after around an hour I started receiving this error and my mqtt client could not connect back to the IOTcore anymore.

**Platform/OS/Device**
What are you running the sdk on?
Debian linux platform

**SDK version number**
Example: aws-iot-device-sdk-cpp-v2 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)
1. establish connect from mqtt client to AWS.
2. Keep publishing data continuously.
3. Connection disconnects with socket operation timed out error, and does not connect again.

**Expected behavior**
Once mqtt connection is established then there should not be a timeout based disconnection. There should not be a timeout for the existing connection. 

**Logs/output**
If applicable, add logs or error output.
Connection failed with error aws-c-io: AWS_IO_SOCKET_TIMEOUT, socket operation timed out

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

```
ApiHandle::InitializeLogging(...)
```

**Additional context**

**Comment by jmklix** [comment]
Are you just running the pubsub example? Does this consistently happen after an hour-ish?

Can you also attach logs from when you are getting the AWS_IO_SOCKET_TIMEOUT?

**Comment by vanarova** [comment]
> npm run tsc


> pub-sub@1.0.0 tsc
> tsc


added 19 packages, and audited 21 packages in 30s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Running pub/sub sample application...
Failed to connect: aws-c-io: AWS_IO_SOCKET_TIMEOUT, socket operation timed out.
PS C:\Users\Administrator\Downloads\connect_device_package (1)> .\start.ps1

**Comment by vanarova** [comment]
I have same issue..

**Comment by jmklix** [comment]
If you are still running into this connection failure error (or something similar) please open a new issue on this repo. Please provide a minimum reproducible sample, logs, and any other detailed information that could help diagnose this issue.
