### ISSUE TITLE
compile sdk in vs 2019 and 2022

### ISSUE THREAD

**Issue by asafgolombek** [aws/aws-iot-device-sdk-cpp-v2#372]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

i want to compile the sdk in vs 2022 but i get an error 'Traits': template parameter name cannot be redeclared.
can you help me?

**Comment by jmklix** [comment]
What steps are you taking to compile this and can you include the full error?

**Comment by shogunlab** [comment]
Hi there, I was having the same issue and managed to successfully compile by doing the following:

- In project properties, set "C/C++ > Language > Conformance mode" to `No (/permissive)`.

I'm unsure of how this addresses the issue described above, but it's something you can try out as it worked for me. Hope this helps.

**Comment by jmklix** [comment]
This is also happening on the not IoT C++ sdk. There is some compatibility issues with C++20, so for now please use C++17. We are working on a fix and will update here once that is out.

**Comment by jmklix** [comment]
We have added some tests for building with the latest version of visual studio and I can't reproduce this error anymore. Can you update to the latest version of this sdk and see if you still have any problems compiling?

**Comment by asafgolombek** [comment]
@jmklix i tried and everything is working, no errors - thanks!
