### ISSUE TITLE
protocolOperationTimeoutMs parameter from the MQTT Connect function is not working for IOT Jobs  

### ISSUE THREAD

**Issue by madhu-korada** [aws/aws-iot-device-sdk-cpp-v2#375]
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
I am using the IoT Jobs module in my application and using the `https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/main/samples/jobs/describe_job_execution/main.cpp` source. But in my case, I am using `DescribeJobExecution` as well as `UpdateJobExecution`. I am using the same MQTT client for publishing my msgs and for IoT Jobs. I needed a timeout functionality in the publishing so that when the internet was not connected, publishing would not get stuck. I achieved it by using `protocolOperationTimeoutMs`. But in the case of IoT Jobs, the same doesn't seem to work. When my internet is disconnecting my program is stopping because there is no such timeout functionality.

**SDK version number**
Not Sure (Installed it few months back)

**Comment by jmklix** [comment]
What is happening when your program stops working? Can you please include logs, a minimal code sample and what you have `protocolOperationTimeoutMs` set to.
