### ISSUE TITLE
Sample basic mqtt pub sub does not work.

### ISSUE THREAD

**Issue by chsajjwal** [aws/aws-iot-device-sdk-cpp-v2#376]
I ran the following command:

1.	mkdir sdk-cpp-workspace
2.	cd sdk-cpp-workspace
3.	git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
4.	mkdir aws-iot-device-sdk-cpp-v2-build
5.	cd aws-iot-device-sdk-cpp-v2-build
6.	cmake -DCMAKE_INSTALL_PREFIX=/home/user/Documents/AWS/sdk-cpp-workspace -DCMAKE_BUILD_TYPE="Debug"  ../aws-iot-device-sdk-cpp-v2
7.	cmake --build . --target install

I have also ran cmake with following command:
cmake -DCMAKE_BUILD_TYPE="Debug"  ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install

and yes also giving it administrator privilege

Then ran this following script:
1.	cd aws-iot-device-sdk-cpp-v2/samples/mqtt/basic_pub_sub/
2.	mkdir build
3.	cd build
4.	cmake -DCMAKE_PREFIX_PATH=/home/user/Documents/AWS/sdk-cpp-workspace -DCMAKE_BUILD_TYPE="<Release|RelWithDebInfo|Debug>" ..
5.	cmake --build . 

I have also tried without passing DCMAKE_PREFIX_PATH if I did not provide DCMAKE_INSTALL_PREFIX, I get the same error for both
Error: 
target pattern contains no '%' 

build.make error:
basic-pub-sub: AWS::aws-crt-cpp-NOTFOUND

**Platform/OS/Device**
Ubuntu 18.04, Raspbian 8 and 10
cmake version: 3.13.4, 3.16.6

I have been trying to just build the sample provided, but not it does not work at all.

**Comment by jmklix** [comment]
Where exactly are you getting each of the errors? and what is the error output related to each one?


You look like you're doing everything correctly except possibly # 4 and # 5 from your script:

4. make sure you use only one DCMAKE_BUILD_TYPE
``` sh
cmake -DCMAKE_PREFIX_PATH=/home/user/Documents/AWS/sdk-cpp-workspace -DCMAKE_BUILD_TYPE="Debug" ..
```
5. add config
``` sh
cmake --build . --config "Debug"
```

**Comment by chsajjwal** [comment]
I figured out the problem. When I ran this below everything worked. 
cmake -DCMAKE_INSTALL_PREFIX="home/user/Documents/AWS/cloud-client/AWS" -DBUILD_DEPS=ON -DCMAKE_BUILD_TYPE="Debug" ../aws-iot-device-sdk-cpp-v2
