### ISSUE TITLE
is S3 Bucket download/upload feature available??

### ISSUE THREAD

**Issue by mayurpatelgec** [aws/aws-iot-device-sdk-cpp-v2#387]
Confirm by changing [ ] to [x] below:
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Ubuntu:20.04

**Describe the question**
I am already using this SDK. Now, we need a S3-Bucket download/upload feature 
I just want to know if that feature is available in this SDK or do i have to go for other SDK like below? 
https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/cpp/example_code/transfer-manager
https://github.com/awslabs/aws-c-s3/tree/main/samples/s3

**Comment by jmklix** [comment]
No, this sdk won't be able to download and upload* things to an s3 bucket. You will need the [aws-sdk-cpp](https://github.com/aws/aws-sdk-cpp) for that.

*You can use IoT Rules to save everything published to a specific topic to an s3 bucket. Read more about how to do that [here](https://docs.aws.amazon.com/iot/latest/developerguide/s3-rule-action.html).
