### ISSUE TITLE
Does someone tried to build and run samples pub_sub with qt? Can't build it.

### ISSUE THREAD

**Issue by Lextan276** [aws/aws-iot-device-sdk-cpp-v2#389]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Ubuntu 20.04

**Describe the question**
Can't build sample basic_pub_sub using qt creator 5.15.2. Have hundreds of error.

My qmake .pro file look like this:
QT -= gui
CONFIG += c++11
CONFIG -= app_bundle
TEMPLATE = app
TARGET = aws-sdk-client
DEFINES += QT_DEPRECATED_WARNINGS
INCLUDEPATH += \
               $$PWD/include
LIBS += -L$$PWD/lib -laws-c-auth -laws-c-io -laws-c-iot -laws-c-mqtt -laws-crt-cpp
SOURCES += \
        main.cpp
HEADERS += \
        include/aws/crt/Api.h \
        include/aws/crt/StlAllocator.h \
        include/aws/crt/auth/Credentials.h \
        include/aws/crt/io/TlsOptions.h \
        include/aws/iot/MqttClient.h \
        include/aws/crt/UUID.h

Maybe someone have an experience of using aws-sdk and QT? I'll be very thankful if you sharing it.

**Comment by qwoprocks** [comment]
@Lextan276 were you able to solve this? I have the same issue
