### ISSUE TITLE
Are there examples of building the SDK as a dynamic library?

### ISSUE THREAD

**Issue by robert-hut** [aws/aws-iot-device-sdk-cpp-v2#390]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Platform/OS/Device**
Currently building the SDK and executables on Rasp Pi 3B (raspbian bullseye)

**Describe the question**
I have searched the docs, forums, and previous issues to see if there are examples / instructions on building the SDK as both static and dynamic libraries (primarily interested in the latter), and how to manage linking the library from app executables. Do such examples or docs exist?

I assume that both are possible (based on reading some previous issues, e.g. https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/35), but would appreciate any info to help speed up our development.

**Comment by jmklix** [comment]
All you need to do is add `BUILD_SHARED_LIBS` to the cmake command when you are building the sdk. It should look something like this: 
```sh
cmake -DCMAKE_INSTALL_PREFIX=$filepath -DCMAKE_BUILD_TYPE="Debug" -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2
```
