### ISSUE TITLE
Could not find a package configuration file provided by "EventstreamRpc-cpp" when setting BUILD_DEPS="OFF"

### ISSUE THREAD

**Issue by Otto45** [aws/aws-iot-device-sdk-cpp-v2#393]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`
  
**Describe the bug**
When running cmake to configure the build without the SDK's dependencies, I am getting the following error:
```
CMake Error at /home/otto/cmake-projects-installation/lib/cmake/AwsFindPackage.cmake:19 (find_package):
  By not providing "FindEventstreamRpc-cpp.cmake" in CMAKE_MODULE_PATH this 
  project has asked CMake to find a package configuration file provided by
  "EventstreamRpc-cpp", but CMake did not find one.
```

To provide some background, I am trying to build both this SDK and the main AWS C++ SDK (S3 portion specifically) for use on a device. I am building the aws-crt-cpp library manually, to be used by both SDKs. Because BYO_CRYPTO is not fully supported yet by this SDK, I am building and installing the main SDK and CRT using AWS' crypto libraries.

**Platform/OS/Device**
Ubuntu 18.04 and cmake version 3.12.4

**SDK version number**
v1.15.5

**To Reproduce (observed behavior)**
Installing aws-crt-cpp:
```
mkdir aws-crt-cpp-workspace
cd aws-crt-cpp-workspace
git clone https://github.com/awslabs/aws-crt-cpp.git
cd aws-crt-cpp
git checkout v0.17.17
git submodule update --init --recursive
cd ..
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="/home/otto/cmake-projects-installation" \
      -DCMAKE_BUILD_TYPE="Debug" \
      -DUSE_OPENSSL="OFF" \
      -DBYO_CRYPTO="OFF" \
      ../aws-crt-cpp
cmake --build . --target install --config "Debug"
```

Installing aws-sdk-cpp:
```
mkdir aws-sdk-cpp-workspace
cd aws-sdk-cpp-workspace
git clone https://github.com/aws/aws-sdk-cpp.git
cd aws-sdk-cpp
git checkout 1.9.201
git submodule update --init --recursive
cd ..
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="/home/otto/cmake-projects-installation" \
      -DCMAKE_PREFIX_PATH="/home/otto/cmake-projects-installation" \
      -DCMAKE_BUILD_TYPE="Debug" \
      -DBUILD_SHARED_LIBS="OFF" \
      -DFORCE_SHARED_CRT="OFF" \
      -DUSE_OPENSSL="OFF" \
      -DBYO_CRYPTO="OFF" \
      -DENABLE_TESTING="OFF" \
      -DBUILD_ONLY="s3" \
      -DBUILD_DEPS="OFF" \
      ../aws-sdk-cpp
cmake --build . --target install --config "Debug"
```

Installing aws-iot-c (not included in the AWS CRT, but needed by this SDK):
```
mkdir aws-c-iot-workspace
cd aws-c-iot-workspace
git clone https://github.com/awslabs/aws-c-iot.git
cd aws-c-iot
git checkout v0.1.2
cd ..
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="/home/otto/cmake-projects-installation" \
      -DCMAKE_PREFIX_PATH="/home/otto/cmake-projects-installation" \
      -DCMAKE_BUILD_TYPE="Debug" \
      -DBUILD_SHARED_LIBS="OFF" \
      -DBYO_CRYPTO="OFF" \
      -DBUILD_TESTING="OFF" \
      ../aws-c-iot
cmake --build . --target install --config "Debug"
```

The error occurs here when running cmake for this SDK:
```
mkdir aws-device-sdk-cpp-workspace
cd aws-device-sdk-cpp-workspace
git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
cd aws-iot-device-sdk-cpp-v2
git checkout v1.15.5
git submodule update --init --recursive
cd ..
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX="/home/otto/cmake-projects-installation" \
      -DCMAKE_PREFIX_PATH="/home/otto/cmake-projects-installation" \
      -DCMAKE_BUILD_TYPE="Debug" \
      -DBUILD_SHARED_LIBS="OFF" \
      -DBYO_CRYPTO="OFF" \
      -DBUILD_DEPS="OFF" \
      ../aws-iot-device-sdk-cpp-v2
```

**Expected behavior**
I expect cmake to complete successfully so I can make and install this SDK.

**Logs/output**
Full error output:
```
CMake Error at /home/otto/cmake-projects-installation/lib/cmake/AwsFindPackage.cmake:19 (find_package):
  By not providing "FindEventstreamRpc-cpp.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "EventstreamRpc-cpp", but CMake did not find one.

  Could not find a package configuration file provided by
  "EventstreamRpc-cpp" with any of the following names:

    EventstreamRpc-cppConfig.cmake
    eventstreamrpc-cpp-config.cmake

  Add the installation prefix of "EventstreamRpc-cpp" to CMAKE_PREFIX_PATH or
  set "EventstreamRpc-cpp_DIR" to a directory containing one of the above
  files.  If "EventstreamRpc-cpp" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  eventstream_rpc/tests/CMakeLists.txt:44 (aws_use_package)


-- Configuring incomplete, errors occurred!
See also "/home/otto/aws-device-sdk-cpp-workspace/build/CMakeFiles/CMakeOutput.log".
See also "/home/otto/aws-device-sdk-cpp-workspace/build/CMakeFiles/CMakeError.log".
```

**Comment by Otto45** [comment]
Update: I am now able to get around this issue and accomplish my goal of building and installing both this SDK and the main AWS C++ SDK by building and installing them separately with dependencies, but ensuring that I choose the versions of each where they share the same version of the aws-crt-cpp library dependency. This may not necessarily be a hack because I am matching the dependency versions correctly, but I would assume that it should be possible to build the CRT library independently, so that it can be built and installed once. After all, both this SDK and the main AWS SDK both provide the `BUILD_DEPS` configuration option.

**Comment by jmklix** [comment]
I'm glad you were able to get this to work. As you noticed you currently need to build both sdk's independently because you can't share some of the dependencies. This is something that we would like to fix, but I'm not sure when it will happen. I'm leaving this issue open so we can update you when it is resolved.

**Comment by bretambrose** [comment]
Should be addressed by https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/584
