### ISSUE TITLE
BYO_CRYPTO option with TLS Handler enabled

### ISSUE THREAD

**Issue by lcycoding** [aws/aws-iot-device-sdk-cpp-v2#394]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Custom ARM computing board

**Describe the question**
Hi AWS developers,
Me and my team are using fleet provision in sdk, but currently suffering from the size of built binary (libs2n takes around 1.2MB).
After some investigations, we discovered that libs2n and the ssl tls related library stand for most of the library size.
If we want to **cut down on the binary size**, we **need to enable BYO_CRYPTO and USE_OPENSSL option here**.
So is there a working example of the self-made tls handler here? If not, is there any similar example to follow?
Any advice or answer is appreciated, thanks!

**Comment by jmklix** [comment]
We don't have any examples for how to use BYO_CRYPTO and this is not a trivial thing to implement. As noted in the PR, "This is an experimental feature. At this time, turning on BYO_CRYPTO completely disables several portions of the SDK (Device Defender, Secure Tunneling, MqttClientConnectionConfigBuilder)". I am asking around and will try to get you some good suggestions for reducing the binary size next week.

**Comment by jmklix** [comment]
You can include `-DUSE_OPENSSL=ON` when building the sdk to use the installed openssl. Other than that their aren't any reasonable options to reduce the binary size.

**Comment by lcycoding** [comment]
Hi @jmklix, 
Thanks for your prompt reply. We already set the USE_OPENSSL on, but still libs2n takes too much sizes.
I think we'll try another option: transfer to embedded C sdk :(

**Comment by jmklix** [comment]
Sorry this sdk couldn't be more useful for you. I'm going to close this issue, but if you want can you still reply with how much smaller you would like this sdk to be.

**Comment by lcycoding** [comment]
Hi @jmklix ,
Thanks for your kind reply!
On our side, we want to use the default crypto things in openssl, in that case we could exclude the binary size of libs2n.
Current built binary after stripping took around 2.5MB, if we could exclude the 1.2MB part from libs2n, that would be really great.
Best,
