### ISSUE TITLE
ConnectionLifecycleHandler shows no error on ipc being brought down

### ISSUE THREAD

**Issue by clogwog** [aws/aws-iot-device-sdk-cpp-v2#395]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
aarch64/ubuntu/nvidia nano

**Describe the question**
I'm subscribing to a local greengrass topic and that is working alright. 
I've specified a ConnectionLifecycleHandler that prints out some details when i receive data, but also if there is an error:

```
class InserClientLifecycleHandler : public ConnectionLifecycleHandler
{
  void OnConnectCallback() override
  {
    GST_WARNING("Meta Inject plugin: Connect callback");
  }
  void OnDisconnectCallback(RpcError error) override
  {
    GST_WARNING("Meta Inject plugin: Disconnected from IPC service");
  }
  bool OnErrorCallback(RpcError error) override
  {
    GST_WARNING("Meta Inject plugin: Error from IPC service");
    return true;
  }
  void OnPingCallback(const Crt::List<EventStreamHeader> &headers, const Crt::Optional<Crt::ByteBuf> &payload) override
  {
    GST_WARNING("Meta Inject plugin: OnPingCallback");
  }
};
```

and i connect to ipc with a modified ConnectionConfig: 

```
ConnectionConfig *connectionConfig = new DefaultConnectionConfig();
 connectionConfig->GetSocketOptions()->SetKeepAlive(true);
 connectionConfig->GetSocketOptions()->SetKeepAliveIntervalSec(20);

Aws::Eventstreamrpc::RpcError connectionStatus = self->ipcClient->Connect(*ipcLifecycleHandler, *connectionConfig).get();


```

this works, however i never see a message for **OnPingCallback** and when i stop greengrass ( `sudo systemctr stop greengrass`)  it never detect an **OnErrorCallback** or **OnDisconnectCallback**

what else is needed so I know when i need to try to re-connect ?

**Comment by clogwog** [comment]
is OnPingCallback the method on how the sdk determines if it is still connected to the greengrass IPC ?

**Comment by jmklix** [comment]
After you connect successfully the first time the sdk will handle reconnecting with exponential back-off. It looks like you are artificially disconnecting it, but have you had this happen with normal use?

**Comment by clogwog** [comment]
I haven't seen any of the events  (OnPingCallback, OnErrorCallback and OnDisconnectCallback) happen at all. not during normal operation and not after stopping the greengrass service. 

The actual ipc works in normal mode (i receive subscription events, etc) so it is connected, I just want it to re-connect and re-subscribe automatically after (for example) greengrass restarts. 

I think when this happens i will need to re-subscribe to the topics (i'm thinking this because i don't receive any subscription events after a greengrass restart). which is the reason i want to detect an IPC disconnection.. is this possible, or is this supposed to work transparently ?

**Comment by jmklix** [comment]
Are you not receiving any messages that you are subscribed to after greengrass restarts?

**Comment by clogwog** [comment]
- no no messages received after a greengrass restart. 
- how is the OnPingCallback used ? should it trigger in the IPC client ConnectionLifecycleHandler class when I set the 

` connectionConfig->GetSocketOptions()->SetKeepAlive(true);
 connectionConfig->GetSocketOptions()->SetKeepAliveIntervalSec(20);`
 
  can you please tell me how this is supposed to work ? Is keep alive used to detect IPC connections ? Or do i need to set more socket options to get this to work ?

**Comment by clogwog** [comment]
does anyone know how the IPC connection and keep alive messages are supposed to work ?

**Comment by jmklix** [comment]
I have found some answers for you. Greengrass IPC is not MQTT so it doesn't use keepalive. Everything is abstracted away so you won't have to handle reconnecting. That being said your component should restart when greengrass restarts. 

It is possible that your recipe is incorrectly configured. You can take a look [here](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recipe-format) to look at how to format it. If you are still running into problems can you reply with the recipe that you are using?

**Comment by clogwog** [comment]
@jmklix thank you for finding those answers. 

Yes i find the component restarts after a greengrass restart, so i guess it is not a good example to test if a loss of IPC is handled. 

I will try to find a different reproducible and re-open a new issue if I have it.
I'll remove the code that sets the KeepAlive settings if it doesn't get used.

Thank you for your effort.
