### ISSUE TITLE
CA certificates for server authentication for Windows

### ISSUE THREAD

**Issue by niranjankk12** [aws/aws-iot-device-sdk-cpp-v2#397]
Confirm by changing [ ] to [x] below:
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [X] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?
Windows 10 Enterprise.

**Describe the question**

We are using aws iot cpp SDK on windows, In-order to create HTTP connection we need to call **ctxOptions.OverrideDefaultTrustStore(caString);** with the CA certificate, we tried i adding same CA certificate in windows trust certificate store and skip calling this API, but it seems SDK is not checking this against windows trust store. 

Also for some customer connection is failing even after calling this API, this is because some customer uses the SSL Inspecting tools which is replacing the Amazon Root CA with tool's root CA certificate and even that certificate is trusted by windows trust store our connection is failing with error "AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL), ErroCode: 1029"  

Is there any way to use windows trust store for CA certificate validation instead of overriding and passing the Amazon CA explicitly?

**Comment by jmklix** [comment]
If you don't specify the root CA it will default to the windows trust store, and that should work by default. How are you trying to go about adding the root CA? Also can you confirm that is does work when you explicitly use the Amazon Root CA?

**Comment by niranjankk12** [comment]
First issue is resolved, i was missing **tlsConnectionOptions.SetServerName(serverName)** , its working as expected with or without specifying root CA as it defaults to windows trust store. 

However we are still facing second issue, in this case some customers has SSL Inspection/Decryption enabled using some 3rd party tools like Netskope, ESET endpoint security, I am able to reproduce same issue using fiddler by enabling Decrypt HTTPS traffic option, when this option is on i am getting error "AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL), ErroCode: 1029". It seems these there issue with the client authentication mentioned in this thread: [https://www.telerik.com/forums/fiddler-stripped-out-client-auth-cert-during-modern-auth-testing]

Is this known issue when using client certificate authentication or is there any workaround for this?

**Comment by jmklix** [comment]
For your second issue that seams to be a problem with fiddler not this sdk. Sorry, but I don't know of any workaround for this.
