### ISSUE TITLE
Disconnect and  Free Memory

### ISSUE THREAD

**Issue by wildwindyevan** [aws/aws-iot-device-sdk-cpp-v2#398]
Confirm by changing [ ] to [x] below:
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [ ] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
What are you running the sdk on?

**Describe the question**
I created a class of that sdk  for connecting to AWS iot ,and moved that clase instance to one thread.
In thread ,I created a timer to monitor the status of connections  and  try to connect  every 30sec.
the first question :Was it a right method?
the second question : if fail to connect  ,how to free the memory used in   "eventLoopGroup, bootstrap,clientConfig,mqttClient... "

**Comment by jmklix** [comment]
You don't need monitor the connection status and attempt to reconnect. On the first attempt to connect with this sdk it will try only once and you will need to retry if it fails the first connection attempt. After that the sdk will reconnect for you using exponential back-off. Are you experiencing disconnections that are not behaving like this?

**Comment by wildwindyevan** [comment]
Thanks for reply . I do monitor the connection   if the SDK fails every time( the first time fails)  for some reasons :  internet not good ,  local time not right....
and a long time later ,the memory leaks , thread crashs.
I tried  to perform  disconnect  action ,but  useless.

**Comment by jmklix** [comment]
Can you give more background/details of 
>a long time later ,the memory leaks , thread crashs.
I tried to perform disconnect action ,but useless.

and possible a code sample of how you are trying to do this. If you haven't looked already the [basic_pub_sub](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/main/samples/mqtt/basic_pub_sub/main.cpp) shows you how to connect and disconnect with this sdk

**Comment by wildwindyevan** [comment]
void awsinterfacev2::timer_connecting()
{
    qDebug()<<"touch  one  in connect";
    is_starting_connection = true;
}
void awsinterfacev2::try_connection( QString mac)
{
        this->mac = mac;
        printf("mac in  thread %s ",mac.toStdString().c_str());
     //    emit  s_makeonlie(false);
        ApiHandle apiHandle;
        endpoint ="a2goczw1pq3jeo-ats.iot.us-west-2.amazonaws.com";

        keyPath ="/etc/.certs/private.pem.key";

        certificatePath = "/etc/.certs/certificate.pem.crt";

        caFile = "/etc/.certs/AmazonRootCA1.crt";
        clientId = mac.toStdString().c_str();// "001EC0DD7489E286";//  getMac();


        /********************** Now Setup an Mqtt Client ******************/
          /*
           * You need an event loop group to process IO events.
           * If you only have a few connections, 1 thread is ideal
           */
          Io::EventLoopGroup eventLoopGroup(1);
          if (!eventLoopGroup)
          {
              fprintf(
                  stderr, "Event Loop Group Creation failed with error %s\n", ErrorDebugString(eventLoopGroup.LastError()));
            #ifdef  FORCE_GO
              return;
            #else
              exit(-1);
            #endif
          }

          Aws::Crt::Io::DefaultHostResolver defaultHostResolver(eventLoopGroup, 2, 30);
          Io::ClientBootstrap bootstrap(eventLoopGroup, defaultHostResolver);

          if (!bootstrap)
          {
              fprintf(stderr, "ClientBootstrap failed with error %s\n", ErrorDebugString(bootstrap.LastError()));
            #ifdef  FORCE_GO
              return;
            #else
              exit(-1);
            #endif
          }

          auto clientConfigBuilder = Aws::Iot::MqttClientConnectionConfigBuilder(certificatePath.c_str(), keyPath.c_str());

          clientConfigBuilder.WithEndpoint(endpoint.c_str());
          if (!caFile.empty())
          {
              clientConfigBuilder.WithCertificateAuthority(caFile.c_str());
          }
        clientConfigBuilder.WithTcpKeepAlive();
        clientConfigBuilder.WithTcpKeepAliveTimeout(30*1000);
        clientConfigBuilder.WithPortOverride(8883);
          auto clientConfig = clientConfigBuilder.Build();

          if (!clientConfig)
          {
              fprintf(
                  stderr,
                  "Client Configuration initialization failed with error %s\n",
                  ErrorDebugString(clientConfig.LastError()));
            #ifdef  FORCE_GO
              return;
            #else
              exit(-1);
            #endif
          }
          Aws::Iot::MqttClient mqttClient(bootstrap);

          /*
           * Since no exceptions are used, always check the bool operator
           * when an error could have occurred.
           */
          if (!mqttClient)
          {
              fprintf(stderr, "MQTT Client Creation failed with error %s\n", ErrorDebugString(mqttClient.LastError()));
                #ifdef  FORCE_GO
                return;
                #else
                exit(-1);
                #endif
          }


          /*
           * Now create a connection object. Note: This type is move only
           * and its underlying memory is managed by the client.
           */
          connection = mqttClient.NewConnection(clientConfig);

          if (!connection)
          {
              fprintf(stderr, "MQTT Connection Creation failed with error %s\n", ErrorDebugString(mqttClient.LastError()));
                #ifdef  FORCE_GO
                return;
                #else
                exit(-1);
                #endif
          }
          //set will
            String will_message_ = "{\"state\":{\"reported\":{\"connected\":\"false\",\"mac\":\"";
            will_message_.append(clientId);
            will_message_.append("\"}}}");
            ByteBuf b_will_message_ =  ByteBufFromArray((const uint8_t *)will_message_.data(), will_message_.length());
            connection->SetWill(AWS_WILL_TOPIC,AWS_MQTT_QOS_AT_LEAST_ONCE,false, b_will_message_ );
          /*
           * In a real world application you probably don't want to enforce synchronous behavior
           * but this is a sample console application, so we'll just do that with a condition variable.
           */


          /*
           * This will execute when an mqtt connect has completed or failed.
           */
          auto onConnectionCompleted = [&](Mqtt::MqttConnection &, int errorCode, Mqtt::ReturnCode returnCode, bool) {
              if (errorCode)
              {
                  fprintf(stdout, "Connection failed with error %s\n", ErrorDebugString(errorCode));
                 // connectionCompletedPromise.set_value(false);
                //  emit  s_makeonlie(false);

              }
              else
              {
                  if (returnCode != AWS_MQTT_CONNECT_ACCEPTED)
                  {
                      fprintf(stdout, "Connection failed with mqtt return code %d\n", (int)returnCode);
                  //    connectionCompletedPromise.set_value(false);
                  //   emit  s_makeonlie(false);

                  }
                  else
                  {
                      fprintf(stdout, "Connection completed successfully.");
                  //    connectionCompletedPromise.set_value(true);
                    //  afterConnected();
                   //   emit  s_makeonlie(true);
                     emit s_mqttconnected();
                  }
              }
          };

          auto onInterrupted = [&](Mqtt::MqttConnection &, int error) {
               fprintf(stdout, "Connection interrupted with error %s\n", ErrorDebugString(error));
               emit   s_runningonlie(false);
          };

          auto onResumed = [&](Mqtt::MqttConnection &, Mqtt::ReturnCode, bool) {
              fprintf(stdout, "Connection resumed\n");
              emit  s_runningonlie(true);
          };

          /*
           * Invoked when a disconnect message has completed.
           */
          auto onDisconnect = [&](Mqtt::MqttConnection &) {
              {
                  fprintf(stdout, "Disconnect completed\n");
                  connectionClosedPromise.set_value();
                  emit  s_makeonlie(false);
              }
          };

          connection->OnConnectionCompleted = std::move(onConnectionCompleted);
          connection->OnDisconnect = std::move(onDisconnect);
          connection->OnConnectionInterrupted = std::move(onInterrupted);
          connection->OnConnectionResumed = std::move(onResumed);

        /*
             * Actually perform the connect dance.
             * This will use default ping behavior of 1 hour and 3 second timeouts.
             * If you want different behavior, those arguments go into slots 3 & 4.
             */
            if (!connection)
            {
                fprintf(stderr, "MQTT Connection Creation failed with error %s\n", ErrorDebugString(connection->LastError()));
            #ifdef  FORCE_GO
            return;
            #else
            exit(-1);
            #endif
            }

            fprintf(stdout, "Connecting...\n");
            is_starting_connection = false;
            if (!connection->Connect(clientId.c_str(), false, 60))
            {
                fprintf(stderr, "MQTT Connection failed with error %s\n", ErrorDebugString(connection->LastError()));
                #ifdef  FORCE_GO
                return;
                #else
                exit(-1);
                #endif
            }
         while (true) {
                     if(is_starting_connection)
                     {
                         is_starting_connection = false;
                             if (!connection->Connect(clientId.c_str(), false, 60))
                             {
                                 fprintf(stderr, "MQTT Connection failed with error %s\n", ErrorDebugString(connection->LastError()));
                             }
                       }
                  QThread::msleep(1);
                  QApplication::processEvents(QEventLoop::AllEvents);
              }

}
=================
my point is create a circle  like  “ while (true) {...} " . to  wait for the singnal  that failed to connected or not.
the flag  "is_starting_connection"  will turn  true every 30s  in  the condition of  unconnected  ,and turn false immediately when begin to connect .

**Comment by wildwindyevan** [comment]
The memory  leaks when  that error comes out 
"Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed"
onConnectionCompleted failed

**Comment by jmklix** [comment]
Can you try using this:
```cpp
     /*
     * Actually perform the connect dance.
     * This will use default ping behavior of 1 hour and 3 second timeouts.
     * If you want different behavior, those arguments go into slots 3 & 4.
     */
    fprintf(stdout, "Connecting...\n");
    bool successful_connection = false;
    while (!successful_connection) {
        std::promise<bool> connectionCompletedPromise;
        auto onConnectionCompleted = [&](Mqtt::MqttConnection &, int errorCode, Mqtt::ReturnCode returnCode, bool) {
            if (errorCode)
            {
                fprintf(stdout, "Connection failed with error %s\n", ErrorDebugString(errorCode));
                connectionCompletedPromise.set_value(false);
            }
            else
            {
                if (returnCode != AWS_MQTT_CONNECT_ACCEPTED)
                {
                    fprintf(stdout, "Connection failed with mqtt return code %d\n", (int)returnCode);
                    connectionCompletedPromise.set_value(false);
                }
                else
                {
                    fprintf(stdout, "Connection completed successfully.");
                    connectionCompletedPromise.set_value(true);
                }
            }
        };

        connection->OnConnectionCompleted = std::move(onConnectionCompleted);

        if (!connection->Connect(clientId.c_str(), false, 1000))
        {
            fprintf(stderr, "MQTT Connection failed with error %s\n", ErrorDebugString(connection->LastError()));
            std::this_thread::sleep_for(std::chrono::milliseconds(1000));
            continue;
        }

        if (connectionCompletedPromise.get_future().get()) {
            successful_connection = true;
        }
    }
```

And if that doesn't work can you provide a minimal code sample without other things in it (ex qt)

**Comment by wildwindyevan** [comment]
thx  ,I am trying now

**Comment by wildwindyevan** [comment]
how about other 3 brothers ?  (onDisconnect ,onInterrupted ,onResumed)

**Comment by wildwindyevan** [comment]
it does not work . In fact ,  it wasted  maybe 30KB memory  every times after connecting 

"if (!connection->Connect(clientId.c_str(), false, 1000))"  //  <<===30KB

I found out the problem that  when the system time is far away from now (ex 2021)   iot connected will end  for "TLS (SSL) negotiation failed". So is it necessary to check current time ?

**Comment by jmklix** [comment]
```cpp
    auto onInterrupted = [&](Mqtt::MqttConnection &, int error) {
        fprintf(stdout, "Connection interrupted with error %s\n", ErrorDebugString(error));
    };

    auto onResumed = [&](Mqtt::MqttConnection &, Mqtt::ReturnCode, bool) { fprintf(stdout, "Connection resumed\n"); };

    /*
     * Invoked when a disconnect message has completed.
     */
    auto onDisconnect = [&](Mqtt::MqttConnection &) {
        {
            fprintf(stdout, "Disconnect completed\n");
            connectionClosedPromise.set_value();
        }
    };

    connection->OnDisconnect = std::move(onDisconnect);
    connection->OnConnectionInterrupted = std::move(onInterrupted);
    connection->OnConnectionResumed = std::move(onResumed);
```

Time is important when doing anything with certs so having correct time can't hurt

**Comment by wildwindyevan** [comment]
I am  very sure  iot C sdk  for embedded  could connect successfully  without correct time. because we are producting so many device  with C sdk every month.

**Comment by jmklix** [comment]
It's possible that the embedded C sdk isn't checking the system time verse the cert time. But, as you noticed if the system time does not fall within a certificates active period then the TLS negotiation will fail. 

Is the 30KB of wasted memory only happening when you have an invalid system time?
