### ISSUE TITLE
Linking errors when using the sdk in an external project

### ISSUE THREAD

**Issue by chaarirami** [aws/aws-iot-device-sdk-cpp-v2#406]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/) and didn't find any solution

**Known Issue**
- [x] I'm using ATS data type endpoint: the endpoint should look like `<prefix>-ats.iot.<region>.amazonaws.com`

**Platform/OS/Device**
Windows

**Describe the question**
I'm receiving linker errors such as:
```
c:/mingw/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\OTA.dir/objects.a(main.cpp.obj):C:/OTA/main.cpp:116: undefined reference to `Aws::Crt::ErrorDebugString(int)'
```
I followed the steps mentioned in the installation part in the readme file. These are the commands I used for installing the sdk:
```
mkdir sdk-cpp-workspace
cd sdk-cpp-workspace
git clone --recursive https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
mkdir aws-iot-device-sdk-cpp-v2-build
cd aws-iot-device-sdk-cpp-v2-build
cmake -DCMAKE_INSTALL_PREFIX="C:\dev\iotsdk\sdk-cpp-workspace" -DCMAKE_PREFIX_PATH="C:\dev\iotsdk\sdk-cpp-workspace" -DBUILD_DEPS=ON ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install
```
This is my cmake file:
```
cmake_minimum_required(VERSION 3.21)
project(OTA)
add_executable(OTA
        main.cpp)
set_target_properties(${PROJECT_NAME} PROPERTIES
        CXX_STANDARD 14)
list(APPEND CMAKE_PREFIX_PATH "C://dev//iotsdk//sdk-cpp-workspace")
#set warnings
if (MSVC)
    target_compile_options(${PROJECT_NAME} PRIVATE /W4 /WX)
else ()
    target_compile_options(${PROJECT_NAME} PRIVATE -Wall -Wno-long-long -pedantic -Werror)
endif ()

install(TARGETS ${PROJECT_NAME} DESTINATION bin)

find_package(aws-crt-cpp REQUIRED)
find_package(IotJobs-cpp REQUIRED)
target_link_libraries(OTA PRIVATE AWS::aws-crt-cpp AWS::IotJobs-cpp)
```
I already looked through the other issues, however, I'm unable to successfully install the sdk. I also added the
`list(APPEND CMAKE_PREFIX_PATH "C://dev//iotsdk//sdk-cpp-workspace")` to the cmake in order to find both the packages. Please help me resolve this issue.

**Comment by jmklix** [comment]
Are you having problems installing this sdk? or compiling your c++ program? 

[This](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/main/CMakeLists.txt) CMakeLists.txt file is for building the sdk. You will build the sdk using the commands you listed above and shouldn't need to modify that CMakeLists.txt

[This](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/main/samples/mqtt/basic_pub_sub/CMakeLists.txt) CMakeLists.txt file is for building the basic_pub_sub sample (this looks similar to your file). Then you will need to compile your program with [these](https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples#build-samples) commands:
```sh
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH="<absolute path sdk-cpp-workspace dir>" -DCMAKE_BUILD_TYPE="<Release|RelWithDebInfo|Debug>" ..
cmake --build . --config "<Release|RelWithDebInfo|Debug>"
```

**Comment by chaarirami** [comment]
Thank you for the quick response.

Installing the sdk works fine. However, linking against it in my CMakeLists.txt ( `target_link_libraries(OTA PRIVATE AWS::aws-crt-cpp AWS::IotJobs-cpp`) causes undefined references errors.

I did not change the CMakeLists.txt file that is used for building the sdk.

I'll try out the commands you mentioned and update you if that fixed the linking errors.

**Comment by chaarirami** [comment]
The problem was due to using two different build tools. 

Thank you for the help.
