### ISSUE TITLE
AWS_ERROR_MQTT_UNEXPECTED_HANGUP every 2 seconds

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#416]
### Describe the bug

Hi, one of the machines in our production environment generates lots of error logs in the AWS cloud side. the error is:
"HTTP Client Disconnect MESSAGE:Disconnect Status: CLIENT_ERROR Failure reason:DUPLICATE_CLIENT_ID"
(looks like this happens when a machine disconnects and reconnects to IoT).

we managed to track the problematic machine, and in the endpoint logs we can see that we get Connection Interrupted notification from the SDK (with error AWS_ERROR_MQTT_UNEXPECTED_HANGUP) and then Connection Resumed notification. this happens every 2 seconds. I'm not sure why all those disconnections-reconnections. can you please look at the SDK log and tell me if you have an assumption?

log sent to: jkl@amazon.com

Thanks

### Expected Behavior

disconnections-reconnections

### Current Behavior

disconnection-reconnection every 2 seconds

### Reproduction Steps

see above

### SDK version used

1.15.2

### Environment details (OS name and version, etc.)

Windows 10

**Comment by jmklix** [comment]
Are you trying to run multiple clients with the same CLIENT_ID? It's possible the when your client is trying to connect for the first time it is failing because of a duplicate client id and then it got stuck trying to reconnect. Can you provide a minimal code sample so we can better diagnose this.

**Comment by elad-ep** [comment]
your explanation looks correct - we saw same id coming from two different IPs. after checking, apparently this is a cloned VM which explains the issue. thanks...

**Comment by abhiram43** [comment]
hey im also facing the same issue how to solve this problem
