### ISSUE TITLE
pkg-config Support

### ISSUE THREAD

**Issue by tlammi** [aws/aws-iot-device-sdk-cpp-v2#425]
### Describe the feature

Export pkg-config from the project during installation.

### Use Case

pkg-config integrates a lot better with tools like the Yocto project and Meson. I had to spend considerable amount of time to get both of those projects to work with CMake configuration scripts.

### Proposed Solution

I don't have knowledge of built in support for pkg-config in CMake so this would require writing some kind of pkg-config template and then populating that template during installation.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

1.14.1

### Environment details (OS name and version, etc.)

Linux

**Comment by jmklix** [comment]
This is not something that we have seen a lot of requests for and it is not something we plan on adding support for anytime soon. This does not mean that it will never be supported, so please upvote this feature request if you would pkg-config support with this sdk.
