### ISSUE TITLE
Link to API Documentation is down(short issue description)

### ISSUE THREAD

**Issue by jeffmachyo** [aws/aws-iot-device-sdk-cpp-v2#433]
### Describe the issue

I would like to read more about the APIs but when I click the link it points to a page that is no longer there. Any redirection to get some API documentation would be greatly appreciated.

### Links

https://aws.github.io/aws-iot-device-sdk-cpp-v2/html/index.html

**Comment by jmklix** [comment]
Thanks for pointing this out. I will get out a fix for this.

**Comment by bretambrose** [comment]
Where are you finding that particular link?  The link in the readme is different and appears to be correct: [API Docs](https://aws.github.io/aws-iot-device-sdk-cpp-v2/)

**Comment by bretambrose** [comment]
I would report the broken link via the Provide Feedback link at the bottom.

**Comment by jeffmachyo** [comment]
Oh okay, thanks..

**Comment by jmklix** [comment]
Fix merged, closing this issue
