### ISSUE TITLE
aws device cpp api v2 reference link  broken

### ISSUE THREAD

**Issue by senthilnow** [aws/aws-iot-device-sdk-cpp-v2#442]
### Describe the issue

aws device cpp api v2 reference link  broken

Not able to reach the link
https://aws.github.io/aws-iot-device-sdk-cpp-v2/html/index.html

### Links

https://aws.github.io/aws-iot-device-sdk-cpp-v2/html/index.html

**Comment by senthilnow** [comment]
as in browser or my geographic location?

**Comment by senthilnow** [comment]
Got the link from here
https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html

look for  section "AWS IoT Device SDKs" in c++ tab, then look for "AWS IoT Device SDK C++ v2 API documentation" link

**Comment by jmklix** [comment]
Thanks for pointing this out. This has already been brought up and I have a [PR](https://github.com/awsdocs/aws-iot-docs/pull/73) to fix it. Closing this issue because it's a duplicate.
