### ISSUE TITLE
Support for other type of proxies

### ISSUE THREAD

**Issue by Amaracs** [aws/aws-iot-device-sdk-cpp-v2#444]
### Describe the feature

Currently the sdk supports only http proxies either with no auth or basic auth, but there are several different commonly used proxy types, so it would be useful to provide support for them, especially because it is a valid commonly used usecase for IoT devices to be behind proxies.

Other proxy types which should be supported:

- Digest Auth
- Forward
- NOIP
- NTLM/Negotiate (Kerberos)
- Socks
- SSL Inspection Proxy
- WPAD

Relevant thread:
https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/365

### Use Case

IoT devices are commonly placed behind proxies and without proxy support they can not be reached.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

Version 1.14.8

### Environment details (OS name and version, etc.)

Windows/macOS

**Comment by jmklix** [comment]
Thanks for taking the time to make a feature request, but this is not something that we are considering adding at this time. This might change in the future so please continue to upvote and list a specific type of proxy that you want support for.
