### ISSUE TITLE
Connection request failed

### ISSUE THREAD

**Issue by Amaracs** [aws/aws-iot-device-sdk-cpp-v2#464]
### Describe the bug

Sporadically we encounter an issue where the IoT device is trying to connect but gets back an AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, which does not really useful. 

```
[ 2022-07-29 07:33:20.824 ][ 1816 ][        Main        ][ Info    ][ Unattended ][          AwsLog         ] - mqtt-client: id=04022968: using ping timeout of 8000000000 ns
[ 2022-07-29 07:33:20.824 ][ 1816 ][        Main        ][ Info    ][ Unattended ][          AwsLog         ] - thread: id=033CBEB8: cpu affinity of cpu_id 0 was specified, attempting to honor the value.
[ 2022-07-29 07:33:20.872 ][ 1816 ][   0x00002916   ][ Error   ][ Unattended ][          AwsLog         ] - socket: id=0402D7A8 handle=00000AE4: connect completion triggered with error -1073741305
[ 2022-07-29 07:33:20.872 ][ 1816 ][   0x00002916   ][ Error   ][ Unattended ][          AwsLog         ] - socket: id=0402D7A8 handle=00000AE4: connection error with code 1055
[ 2022-07-29 07:33:20.872 ][ 1816 ][   0x00002916   ][ Info    ][ Unattended ][          AwsLog         ] - dns: id=00FAD3A0: recording failure for record 2406:da00:ff00::1715:9b0f for <URL>, moving to bad list
[ 2022-07-29 07:33:21.114 ][ 1816 ][   0x00002916   ][ Error   ][ Unattended ][          AwsLog         ] - tls-handler: id=040DF620: Error during negotiation. SECURITY_STATUS is -2146893016
[ 2022-07-29 07:33:21.115 ][ 1816 ][   0x00002916   ][ Error   ][ Unattended ][      MqttConnection     ] - Connection failed with error aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed and lastError: aws-c-io: AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE, TLS (SSL) negotiation failed - 1029
```

Is there a useful advice how could we analyze such issues successfully, because this TLS negotiation failure error code is not really helpful. The provisioning was successful, the connection was established several times successfully, but after some time this kind of issue happens and it is hard to analyze. I am not looking for a solution here per se, but an advice how to analyze connectivity issues.

### Expected Behavior

Successful connection

### Current Behavior

Failed connection request

### Reproduction Steps

The connection flow was implemented based on the example in the repo and most of the time it is successful, but once of a blue moon it fails.

### Possible Solution

More detailed error handling

### SDK version used

Version 1.9

### Environment details (OS name and version, etc.)

Windows 10

**Comment by jmklix** [comment]
I would recommend enabling CloudWatch logs, and then look there when you see `AWS_IO_TLS_ERROR_NEGOTIATION_FAILURE`. You can read about how to enable CloudWatch logs for IoT [here](https://docs.aws.amazon.com/iot/latest/developerguide/cloud-watch-logs.html). Please let me know if you have any more questions about this.

**Comment by Amaracs** [comment]
@jmklix Thank you for your answer. I am closing the ticket, but if you are planning to add more detailed logs to the client side too I am all in for it. It would make the analyzation process much easier if its possible.
