### ISSUE TITLE
delete broken tag refs/tags/v1.20.1^{}

### ISSUE THREAD

**Issue by thomas-roos** [aws/aws-iot-device-sdk-cpp-v2#519]
### Describe the bug

f49d0f2a26a1b24cc62570970e5fc876413099e4	refs/tags/v1.20.1^{}
is causing issues on our meta-aws auto upgrade mechanism (yes, we can filter that...)
this tag should be deleted?

### Expected Behavior

no such bogus tag

### Current Behavior

tag is there

### Reproduction Steps

git clone https://github.com/aws/aws-iot-device-sdk-cpp-v2.git
cd aws-iot-device-sdk-cpp-v2/
git ls-remote 

### SDK version used

f49d0f2a26a1b24cc62570970e5fc876413099e4

### Environment details (OS name and version, etc.)

Ubuntu 20.04

**Comment by TwistedTwigleg** [comment]
Thank you for making this issue!

This issue should now be fixed. Running `git ls-remote` shows that there are no `<tag name>^{}` tags present anymore.  PRs have also been made to fix this issue moving forward.

Closing this issue...
