### ISSUE TITLE
provide a way (CMakefile) to build all samples at once

### ISSUE THREAD

**Issue by thomas-roos** [aws/aws-iot-device-sdk-cpp-v2#521]
### Describe the feature

this is discussed here:
https://github.com/aws4embeddedlinux/meta-aws/discussions/2153

### Use Case

do not need a yocto recipe for each sample, because currently they are separated cmake projects

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### SDK version used

f49d0f2a26a1b24cc62570970e5fc876413099e4

### Environment details (OS name and version, etc.)

yocto

**Comment by jmklix** [comment]
Is this something that you would be able to add by merging the existing CMakefiles?

**Comment by thomas-roos** [comment]
You mean if this should be added to the existing lib CMakefile?

https://github.com/scooter1556 suggested this here: https://github.com/aws4embeddedlinux/meta-aws/discussions/2153#discussioncomment-4706144

So create a new CMakefile here: https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples to build all samples

**Comment by jmklix** [comment]
>So create a new CMakefile here: https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples to build all samples

Yes to this

**Comment by thomas-roos** [comment]
ok, agree, but I can not do this. Might you want to put this into your backlog?

**Comment by TwistedTwigleg** [comment]
Thank you for making this issue! A CMAKE file was added for building all of the V2 SDK samples at once, as well as instructions on the README how to use it.

**Comment by thomas-roos** [comment]
thank you - will check this the next days
