### ISSUE TITLE
Issue with sample project build command due to -B option in cmake version

### ISSUE THREAD

**Issue by Kta-M** [aws/aws-iot-device-sdk-cpp-v2#551]
### Describe the issue

In the README.md file, it is mentioned that cmake version 3.1+ is required for building the project. While building the main project, there were no issues. However, I encountered a problem while trying to build the sample project.

The issue seems to be with the -B option in the cmake command used for building the sample project. This option was introduced in cmake version 3.13, which is not compatible with the stated version requirement of cmake 3.1+.

### Links

https://cmake.org/cmake/help/latest/manual/cmake.1.html#generate-a-project-buildsystem

**Comment by TwistedTwigleg** [comment]
Thanks for reporting this issue. The sample README now includes instructions on how to build the samples without the use of the `-B` command, which should work for CMake 3.1+.

Thanks again!
