### ISSUE TITLE
After Some Time Socket Getting Closed

### ISSUE THREAD

**Issue by rana94302** [aws/aws-iot-device-sdk-cpp-v2#555]
### Describe the bug

```
[DEBUG] [2023-03-30T11:50:27Z] [00007f25b18af700] [mqtt5-client] - id=0x7f25ac07ab70: Received PUBACK packet
[DEBUG] [2023-03-30T11:50:27Z] [00007f25b18af700] [mqtt5-general] - id=0x7f25b18ae2d0: aws_mqtt5_packet_puback_view packet id set to 3
[DEBUG] [2023-03-30T11:50:27Z] [00007f25b18af700] [mqtt5-general] - id=0x7f25b18ae2d0: puback 0 reason code: Success
[INFO] [2023-03-30T11:50:27Z] [00007f25b18af700] [mqtt5-client] - Publish completion callback triggered.
[DEBUG] [2023-03-30T11:50:27Z] [00007f25b18af700] [task-scheduler] - id=0x7f25ac07aba0: Running Mqtt5Service task with status
[DEBUG] [2023-03-30T11:50:27Z] [00007f25b18af700] [task-scheduler] - id=0x7f25ac07aba0: Scheduling Mqtt5Service task for future execution at time 121574941865786
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [task-scheduler] - id=0x7f25ac07aba0: Running Mqtt5Service task with status
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [mqtt5-client] - id=0x7f25ac07ab70: next PINGREQ scheduled for time 122774964312793
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [mqtt5-client] - id=0x7f25ac07ab70: queuing PINGREQ
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [mqtt5-client] - id=0x7f25ac07ab70: enqueuing PINGREQ operation to front
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [mqtt5-client] - id=0x7f25ac07ab70: setting up encode for a PINGREQ packet
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [mqtt5-client] - id=0x7f25ac07ab70: finished encoding current operation
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [task-scheduler] - id=0x7f2590002460: Scheduling socket_written_task task for immediate execution
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [task-scheduler] - id=0x7f25ac07aba0: Scheduling Mqtt5Service task for future execution at time 121604964385447
[DEBUG] [2023-03-30T12:06:47Z] [00007f25b18af700] [task-scheduler] - id=0x7f2590002460: Running socket_written_task task with status
[INFO] [2023-03-30T12:07:11Z] [00007f25b18af700] [socket] - id=0x7f25900022c0 fd=21: socket is closed.
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [task-scheduler] - id=0x7f2590003910: Scheduling channel_shutdown task for immediate execution
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [channel] - id=0x7f2590003710: Channel shutdown is already pending, not scheduling another.
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [task-scheduler] - id=0x7f2590003910: Running channel_shutdown task with status
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [channel] - id=0x7f2590003710: beginning shutdown process
Mqtt5 Client disconnection with reason: aws-c-io: AWS_IO_SOCKET_CLOSED, socket is closed..
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [channel] - id=0x7f2590003710: handler 0x7f2590014560 shutdown in read dir completed.
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [tls-handler] - id=0x7f2590014690: Shutting down read direction with error code 1051
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [channel] - id=0x7f2590003710: handler 0x7f2590014690 shutdown in read dir completed.
[DEBUG] [2023-03-30T12:07:11Z] [00007f25b18af700] [channel] - id=0x7f2590003710: handler 0x7f25ac07ac38 shutdown in read dir completed.
Segmentation fault
```

### Expected Behavior

This should be continuously connected whether mqtt is in idle state or not.

### Current Behavior

After some time MQTT is getting disconnected and Socket getting closed.

### Reproduction Steps

Step to reproduce:

1. Establish the connection
2. publish some data, which working fine.
3. receive some data which subscribed.
4. leave for some time more than 10 minutes in idle state
5. then automatically socket get closed and MQTT get disconnected.

### SDK version used

aws-iot-device-sdk-cpp-v2

### Environment details (OS name and version, etc.)

Ubuntu 18.04

**Comment by jmklix** [comment]
Does this happen every time? Are you running into this when running the mqtt5 pubsub sample?

At the bottom I see it's seg faulting. Are there any more logs/stack trace from that?

**Comment by jmklix** [comment]
I see that you opened another issue on the [js repo](https://github.com/aws/aws-iot-device-sdk-js-v2/issues/346) with the exact same into. Can you post the full logs?

**Comment by rana94302** [comment]
Below latest log after did fresh installation of library:

[DEBUG] [2023-03-31T07:12:27Z] [00007f35c5ffb700] [task-scheduler] - id=0x7f35c800e5d0: Running Mqtt5Service task with <Running> status
[DEBUG] [2023-03-31T07:12:27Z] [00007f35c5ffb700] [mqtt5-client] - id=0x7f35c800e5a0: connected sufficiently long that reconnect backoff delay has been reset back to minimum value
[DEBUG] [2023-03-31T07:12:27Z] [00007f35c5ffb700] [task-scheduler] - id=0x7f35c800e5d0: Scheduling Mqtt5Service task for future execution at time 191487050725700
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [task-scheduler] - id=0x7f35c800e5d0: Running Mqtt5Service task with <Running> status
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [mqtt5-client] - id=0x7f35c800e5a0: next PINGREQ scheduled for time 192687154358894
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [mqtt5-client] - id=0x7f35c800e5a0: queuing PINGREQ
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [mqtt5-client] - id=0x7f35c800e5a0: enqueuing PINGREQ operation to front
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [mqtt5-client] - id=0x7f35c800e5a0: setting up encode for a PINGREQ packet
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [mqtt5-client] - id=0x7f35c800e5a0: finished encoding current operation
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [task-scheduler] - id=0x7f35b4001150: Scheduling socket_written_task task for immediate execution
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [task-scheduler] - id=0x7f35c800e5d0: Scheduling Mqtt5Service task for future execution at time 191517154431753
[DEBUG] [2023-03-31T07:31:57Z] [00007f35c5ffb700] [task-scheduler] - id=0x7f35b4001150: Running socket_written_task task with <Running> status
Mqtt5 Client disconnection with reason: libaws-c-mqtt: AWS_ERROR_MQTT5_PING_RESPONSE_TIMEOUT, Remote endpoint did not respond to a PINGREQ before timeout exceeded.
[DEBUG] [2023-03-31T07:32:27Z] [00007f35c5ffb700] [task-scheduler] - id=0x7f35c800e5d0: Running Mqtt5Service task with <Running> status
[INFO] [2023-03-31T07:32:27Z] [00007f35c5ffb700] [mqtt5-client] - id=0x7f35c800e5a0: emitting disconnection lifecycle event with error code 5152(libaws-c-mqtt: AWS_ERROR_MQTT5_PING_RESPONSE_TIMEOUT, Remote endpoint did not respond to a PINGREQ before timeout exceeded)
[INFO] [2023-03-31T07:32:27Z] [00007f35c5ffb700] [mqtt5-client] -   Error Code: 5152(libaws-c-mqtt: AWS_ERROR_MQTT5_PING_RESPONSE_TIMEOUT, Remote endpoint did not respond to a PINGREQ before timeout exceeded)

Thread 7 "AwsEventLoop 5" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f35c5ffb700 (LWP 18620)]
__GI___pthread_once (once_control=0x1f83d9ab5be0cd31, init_routine=0x7f35ce9e33f0 <__once_proxy>) at pthread_once.c:139
139	pthread_once.c: No such file or directory.

**Comment by rana94302** [comment]
why is it emitting disconnection lifecycle event after 15 min of Idle state once connection established ? is there any time out ?
How can we make for infinite time ?

**Comment by rana94302** [comment]
Below backtrace log:
#0  __GI___pthread_once (once_control=0x1f83d9ab5be0cd31, init_routine=0x7f35ce9e33f0 <__once_proxy>) at pthread_once.c:139
#1  0x00007f35cf520d0a in __gthread_once(int*, void (*)()) () from /home/PPCloud_WorkSpace/PPBuild/lib/libMqttClienLib.so
#2  0x00007f35cf527add in void std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) () from /home/PPCloud_WorkSpace/PPBuild/lib/libMqttClienLib.so
#3  0x00007f35cf526296 in std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) ()
   from /home/PPCloud_WorkSpace/PPBuild/lib/libMqttClienLib.so
#4  0x00007f35cf5267a7 in std::promise<void>::set_value() () from /home/PPCloud_WorkSpace/PPBuild/lib/libMqttClienLib.so
#5  0x00007f35cf521885 in connectionparam(void*)::{lambda(Aws::Crt::Mqtt5::Mqtt5Client&, Aws::Crt::Mqtt5::OnDisconnectionEventData const&)#5}::operator()(Aws::Crt::Mqtt5::Mqtt5Client&, Aws::Crt::Mqtt5::OnDisconnectionEventData const&) const () from /home/PPCloud_WorkSpace/PPBuild/lib/libMqttClienLib.so
#6  0x00007f35cf524a2a in std::_Function_handler<void (Aws::Crt::Mqtt5::Mqtt5Client&, Aws::Crt::Mqtt5::OnDisconnectionEventData const&), connectionparam(void*)::{lambda(Aws::Crt::Mqtt5::Mqtt5Client&, Aws::Crt::Mqtt5::OnDisconnectionEventData const&)#5}>::_M_invoke(std::_Any_data const&, Aws::Crt::Mqtt5::Mqtt5Client&, Aws::Crt::Mqtt5::OnDisconnectionEventData const&) ()
   from /home/PPCloud_WorkSpace/PPBuild/lib/libMqttClienLib.so
#7  0x0000563cc28fb471 in std::function<void (Aws::Crt::Mqtt5::Mqtt5Client&, Aws::Crt::Mqtt5::OnDisconnectionEventData const&)>::operator()(Aws::Crt::Mqtt5::Mqtt5Client&, Aws::Crt::Mqtt5::OnDisconnectionEventData const&) const (__args#1=..., __args#0=..., this=0x7f35c800e488) at /usr/include/c++/7/bits/std_function.h:706
#8  Aws::Crt::Mqtt5::Mqtt5Client::s_lifeCycleEventCallback (event=0x7f35c5ffa6c0) at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/source/mqtt/Mqtt5Client.cpp:137
#9  0x0000563cc2916b01 in s_aws_mqtt5_client_emit_final_lifecycle_event (client=client@entry=0x7f35c800e5a0, error_code=error_code@entry=5152, connack_view=connack_view@entry=0x0, 
    disconnect_view=disconnect_view@entry=0x0) at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/v5/mqtt5_client.c:419
#10 0x0000563cc291b9da in s_service_state_connected (now=191517197718120, client=0x7f35c800e5a0)
    at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/v5/mqtt5_client.c:1497
#11 s_mqtt5_service_task_fn (task=<optimized out>, arg=0x7f35c800e5a0, status=<optimized out>)
    at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-mqtt/source/v5/mqtt5_client.c:1605
#12 0x0000563cc2b0b7c6 in s_run_all (scheduler=scheduler@entry=0x7f35c8002e30, current_time=191517197620585, status=status@entry=AWS_TASK_STATUS_RUN_READY)
    at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-common/source/task_scheduler.c:249
#13 0x0000563cc2b0bd3c in aws_task_scheduler_run_all (scheduler=scheduler@entry=0x7f35c8002e30, current_time=<optimized out>)
    at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-common/source/task_scheduler.c:188
#14 0x0000563cc297bc1a in aws_event_loop_thread (args=0x7f35c8002a80) at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-io/source/linux/epoll_event_loop.c:650
#15 0x0000563cc2b0acea in thread_fn (arg=0x7f35c8003020) at /home/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-c-common/source/posix/thread.c:173
#16 0x00007f35ce1426db in start_thread (arg=0x7f35c5ffb700) at pthread_create.c:463
#17 0x00007f35cde6b61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by bretambrose** [comment]
The crash is in your disconnect callback; that's something you'll need to debug yourself.

Beyond that, the reason for disconnect is at the bottom of the logs:

`AWS_ERROR_MQTT5_PING_RESPONSE_TIMEOUT, Remote endpoint did not respond to a PINGREQ before timeout exceeded`

Per the spec (https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Keep_Alive_1):

`If a Client does not receive a PINGRESP packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server.`

There could be many reasons why that's happening, but if it's reliably repeatable for you, my first guess would be an overly restrictive gateway/router/firewall/packet-filter that "forgets" about the connection after a relatively short period of time (there's a 16+ minute gap between client-side writes in your logs).  In that case, the firewall may just eat the PINGREQ.  If this was the case, experimenting with a lower keep alive value (IoT Core supports down to 30 seconds) might keep that mapping alive.

**Comment by rana94302** [comment]
ThanksHow can we do  lower keep alive value (IoT Core supports down to 30 seconds), is there any thing which can do or set from code side. do you have any reference point ?

**Comment by xiazhvera** [comment]
Keep alive is a connection option. You can set it in the ConnectPacket. Here is an example:
```
// Create a Client using Mqtt5ClientBuilder
Aws::Iot::Mqtt5ClientBuilder *builder = Aws::Iot::Mqtt5ClientBuilder::NewMqtt5ClientBuilderWithMtlsFromPath(<path to credentials>);

std::shared_ptr<Mqtt5::ConnectPacket> packetConnect = std::make_shared<Mqtt5::ConnectPacket>(allocator);
packetConnect->withKeepAliveIntervalSec(30)

//... Setup other builder and connect options.

builder->withConnectOptions(connectOptions);

// Create Mqtt5Client
std::shared_ptr<Aws::Crt::Mqtt5::Mqtt5Client> client = builder->Build();

```

You can find more information in the API Doc: https://aws.github.io/aws-iot-device-sdk-cpp-v2/class_aws_1_1_crt_1_1_mqtt5_1_1_connect_packet.html#ae907cffaa9ba8460e5dd6faea21c1a2e
