### ISSUE TITLE
Unable to access the target device on the browser through a secure tunnel

### ISSUE THREAD

**Issue by zhangzz0413** [aws/aws-iot-device-sdk-cpp-v2#601]
### Describe the bug

Unable to access the target device from the browser through sample tunnel-notification, click the connect button and keep rotating.

### Expected Behavior

Correctly connect to the target device through  browser.

### Current Behavior

I click the connect button and keep rotating, cannot connect the target device.

### Reproduction Steps

My steps as follows:

1. Create a thing (name: secure_tunnel_demo) and download rootca, certification and private key;
2. run the tunnel-notification sample:
    $ ./tunnel-notification --endpoint avat5bq0m42tf-ats.iot.us-east-1.amazonaws.com --cert cert.crt --key private.key --thing_name secure_tunnel_demo
3. Click on the thing name and click to create a secure tunnel, and used quickly set it. 
    I can see that the destination connection status is connected, and then click the connection button.;
4. It is always rotating in circles and cannot be connected;

### SDK version used

1.24.3

### Environment details (OS name and version, etc.)

Ubuntu 18.04

**Comment by zhangzz0413** [comment]
How should I use the securetunnel feature? Does this sample feel unusable?

**Comment by jmklix** [comment]
You can find out more info about how/why to use a secure tunnel [here](https://docs.aws.amazon.com/iot/latest/developerguide/secure-tunneling.html). Are you running into any problems with the sample? You closed the above issue without any comments. If you are still having problems understanding/running the sample feel free to reopen this issue.

**Comment by zhangzz0413** [comment]
> You can find out more info about how/why to use a secure tunnel [here](https://docs.aws.amazon.com/iot/latest/developerguide/secure-tunneling.html). Are you running into any problems with the sample? You closed the above issue without any comments. Are you still running into the same issue that you opened this ticket for?

Hi, jmklix

Thank you for your reply. 
I am currently unable to run through the secure tunnel function using the sample in the C++SDK. Can you take a look at the steps I mentioned above to run the sample? Am I missing any steps?

**Comment by jmklix** [comment]
Are you getting any console output after you create the secure tunnel? Can you also enable logging? I'm able to run the sample and successfully connect.
