### ISSUE TITLE
MQTT connection without TLS

### ISSUE THREAD

**Issue by karthikkumarb** [aws/aws-iot-device-sdk-cpp-v2#612]
### Describe the feature

I am looking for a sample code to connect to MQTT broker without TLS, Similar to plaintext sample code in aws-iot-device-sdk-embedded-C and a command line if any to connect to the broker.

### Use Case

In our project, we need to support both TLS and non TLS connections.

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### SDK version used

v1.27.0

### Environment details (OS name and version, etc.)

Linux

**Comment by bretambrose** [comment]
If you're not using TLS you can't use the builder interface for connection creation and instead need to directly use the types in the CRT.  MQTT over plaintext just means you don't specify any TLS context.

If you're using MQTT311, use the API that does not take a TLS context: https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/mqtt/MqttClient.h#L616-L631

If you're using MQTT5, don't set any tls configuration when building the client configuration: https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/mqtt/Mqtt5Client.h#L441-L448

**Comment by karthikkumarb** [comment]
Hi @bretambrose, Can you please share a sample code if you have any? That will be useful for my reference.

**Comment by bretambrose** [comment]
There are no complete samples, but the integration tests in aws-crt-cpp contain example: https://github.com/awslabs/aws-crt-cpp/blob/main/tests/MqttClientTest.cpp

**Comment by karthikkumarb** [comment]
Hi @bretambrose, Does this has any examples to connect to the broker using JWT?

**Comment by bretambrose** [comment]
No.  There is no support for anything JWT related.

**Comment by sbSteveK** [comment]
This issue appears to be resolved. Please feel free to comment and reopen if there are any further questions. Please open a new discussion or issue if further questions do not have to do with MQTT connection without TLS.

**Comment by DOO-Phil** [comment]
> Hi [@bretambrose](https://github.com/bretambrose), Can you please share a sample code if you have any? That will be useful for my reference.

I also had to use an AWS MQTT Client without TLS context. Here is is sample code of how I did it for anyone have the same question.

```
#include <aws/crt/mqtt/MqttClient.h>

Aws::Crt::Io::SocketOptions socketOptions;
socketOptions.SetKeepAlive(true);
socketOptions.SetConnectTimeoutMs(5000);
socketOptions.SetKeepAliveTimeoutSec(5);
socketOptions.SetKeepAliveIntervalSec(5);
socketOptions.SetKeepAliveMaxFailedProbes(5);

Aws::Crt::Mqtt::MqttClient client;
std::shared_ptr<Aws::Crt::Mqtt::MqttConnection> connection = client.NewConnection("<BROKER_ADDRESS>", 1883, socketOptions, false);```
