### ISSUE TITLE
Segfault when try to use Aws::Crt::MqttClient::Publish

### ISSUE THREAD

**Issue by brunogriep** [aws/aws-iot-device-sdk-cpp-v2#625]
### Describe the bug

I'm trying to send data to AWS Cloud through a MQTT client, I used one of the samples to write the following method:

```
auto awsPublish(const std::string &topic, const json &messagePayload) -> bool
{
  auto dataToSend = messagePayload.dump();

  auto messagePayloadString = Aws::Crt::String(dataToSend.c_str());
  Aws::Crt::ByteBuf payload =
      ByteBufFromArray((const uint8_t *)messagePayloadString.data(), messagePayloadString.length());

  m_awsMessageSent = false;

  auto onPublishComplete = [&](Aws::Crt::Mqtt::MqttConnection &, uint16_t, int) { m_awsMessageSent = true; };
  auto ret = m_awsMqttClient->Publish(topic.c_str(), AWS_MQTT_QOS_AT_LEAST_ONCE, false, payload, onPublishComplete);

  return ret == 0 ? true : false;
}
```

- messagePayload is an object of  `nlohmann::json`, which I'm converting to a string before any operation.
- m_awsMqttClient is a ptr to `Aws::Crt::Mqtt::MqttConnection`
- Aws Connection was established before and it is working

I used GDB to get the point where the segmentation fault happened, here is the log:
```
(gdb) info stack
#0  Aws::Crt::Mqtt::MqttConnection::Publish(char const*, aws_mqtt_qos, bool, aws_byte_buf const&, std::function<void (Aws::Crt::Mqtt::MqttConnection&, unsigned short, int)>&&) (this=0x0, topic=0x7ffc23bc20d8 "aws-data", qos=qos@entry=AWS_MQTT_QOS_AT_LEAST_ONCE, retain=retain@entry=false, payload=..., onOpComplete=...)
    at /sdk-workspace/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/source/mqtt/MqttClient.cpp:760
#1  0x000055e74cd297c8 in aeler::AwsCloud::awsPublish (this=this@entry=0x7fa2a83ce030, topic=..., messagePayload=...)
``` 
In aws-crt-cpp/source/mqtt/MqttClient.cpp line 760  we have:
` auto opCompleteCallbackData = Crt::New<OpCompleteCallbackData>(m_allocator); ` 
 https://github.com/awslabs/aws-crt-cpp/blob/363d09e8a3509f663327d6e8414d0b2e052c815d/source/mqtt/MqttClient.cpp#L760

Does anyone know why it is breaking here??

### Expected Behavior

Publish method should return an integer with packet id

### Current Behavior

When Publish method is being called a Segmentation fault occur.

### Reproduction Steps

Similar to basic_pub_sub sample, but instead of using a string as payload, need to use nlohmann::json object and invoke dump method to convert the json to a string (https://json.nlohmann.me/api/basic_json/dump/)

### SDK version used

11855fc2601df396cbf1a36b1ae208b1b0ed8154

### Environment details (OS name and version, etc.)

Alpine Linux v3.17

**Comment by bretambrose** [comment]
`this=0x0,` in the gdb call stack seems like your connection is null.  If you're running a release build though, that's no longer a reliable indicator and in that case, consider making a debug build and checking.
