### ISSUE TITLE
device going off/online on interaction

### ISSUE THREAD

**Issue by certabitmh** [aws/aws-iot-device-sdk-cpp-v2#637]
### Describe the bug

Device seems to be online, but when sending i.e. a change in desired shadow section it goes offline and goes back online approx. 2mins afterwards. 
Does not happen on every shadow change, only 1-2 times a day. I've attached a log of the things going on.
(focus on lines with "{"log":"[DEBUG] [2023-09-......" --> from sdk )

Do you see any possible cause ?

[goingoff_and_onlineagain.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/12749544/goingoff_and_onlineagain.txt)

### Expected Behavior

shadow delta callback to be called

### Current Behavior

connection brakes

### Reproduction Steps

- device online, shadow in sync (no delta)
- change desired state

### SDK version used

1.28

### Environment details (OS name and version, etc.)

linux on arm

**Comment by bretambrose** [comment]
There isn't a way of telling for sure, but the most likely scenario is that the remote host dropped the connection some time between the first ping and the second ping (in the attached log).  When the second ping is received by the remote host, with no associated connection, it sends a TCP RST signalling the connection is broken/non-existent.

Trace logs or a packet capture would help confirm/disprove that hypothesis.

**Comment by certabitmh** [comment]
but why does this drop occur only when interaction with the device? if idle it stays online for days..

anyway, I'll try to provide trace logs...can take some days to collect

**Comment by bretambrose** [comment]
Streaming protocols are an illusion built on top of peer-to-peer forwarding.  Oftentimes, the only way to determine if the end-to-end "circuit/pipe/stream" is alive is to try and use it.

Beyond that, I would disagree with your first statement.

The log you provided shows a connection drop during idle time.  You weren't doing anything and the protocol's pingreq/pingresp behavior detected the broken connection, which is exactly what it (the ping behavior required by the MQTT spec) is designed to do.

If your definition of "interacted with" refers to the socket itself, then "idle for days" isn't accurate because the client is interacting with the socket every 20 minutes to do a pingreq/pingresp cycle even if your application isn't doing anything.

**Comment by certabitmh** [comment]
ok let's put it in other words / from customer perspective:

1. no interaction (= app usage ->  which reads/writes device shadow) from my customer for a few hours, device is reported as online (based on shadow parameter "isConnected" which uses LWT mechanism on going offline)
2. customer  wants to switch the product on (from standby)
    2a. my customer opens our app,  checks online state of his/her device -> it's online 
    2b. customer presses button, App writes to desired shadow state: "mode": "on"
3. then "nothing" happens for 2min (until log stuff from above has been performed -> offline, online again,....)  -> my customer gets angry

--> the shadow delta callback is not issued, instead the stuff from logs provided happens.

So this is very unsatisfying for us and our customers -> I need a solution for this!

Can I tweak on parameters / timeouts whatever?

**Comment by bretambrose** [comment]
There are a number of timeouts you can mess with but they're not a magic solution.  The caveat with timeouts is that setting them too stringently can lead to unstable connectivity.  For example, certain browsers throttle background tab Javascript execution so unpredictably that a low MQTT keep alive can result in completely spurious disconnects.  Not a concern here in C++, but similar situations can potentially crop up (packet loss + TCP retry for example).  

* [MQTT Keep Alive](https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/mqtt/MqttConnection.h#L245) - IoT Core supports as low as 30 seconds, which implies an associated 15 second ping timeout.
* [TCP Keep Alive](https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/io/SocketOptions.h#L90-L140) - Off by default.  Cheaper (bandwidth wise) than MQTT Keep Alive.  There are some hypothetical, extreme scenarios where TCP keep alive may not detect a disconnection but I've never seen it happen in practice.
* [Operation Timeout](https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/mqtt/MqttConnection.h#L247) - Maximum allowed interval between a {Subscribe, Unsubscribe, Qos1 Publish} and its associated ack packet.  If breached, the operation is failed and you are notified of the fact.

For reactivity, I think a low operation timeout, performing all of your publishes with QoS 1 (QoS 0 publishes will not trigger operation timeouts) might be a promising approach.  If a shadow update times out, you'll need to handle that fact.

Beyond that, I suggest looking into the "2 minutes."  The log you attached showed an instant reconnection, so figuring out where the long delay comes from would be your best bet.

**Comment by certabitmh** [comment]
ok thanks, will have a look at at those parameters and reopen in case...
