### ISSUE TITLE
DNS IO QUERY FAILED 

### ISSUE THREAD

**Issue by rana94302** [aws/aws-iot-device-sdk-cpp-v2#668]
### Describe the bug

I am using aws sdk library in machine where internet is working but not able to connect to end point getting below error:
Mqtt5 Client attempting connection...
[ERROR] [2019-01-30T02:41:07Z] [0000007f47fff120] [dns] - static: getaddrinfo failed with error_code -3: Temporary failure in name resolution
[ERROR] [2019-01-30T02:41:07Z] [0000007f47fff120] [channel-bootstrap] - id=0x7f54001f90: dns resolution failed, or all socket connections to the endpoint failed.
Mqtt5 Client connection failed with error: aws-c-io: AWS_IO_DNS_QUERY_FAILED, A query to dns failed to resolve..

### Expected Behavior

Mqtt Connection should be established.

### Current Behavior

In Simulation working fine in My personal computer where i am using ubuntu 18.04 but not able to connect in target in machine where have build arm.

### Reproduction Steps

Execute the program and start getting the AWS_IO_DNS_QUERY_FAILED error.

### SDK version used

aws-iot-device-sdk-cpp-v2

### Environment details (OS name and version, etc.)

arm

**Comment by bretambrose** [comment]
A successful connection requires successful DNS resolution; DNS resolution falls under host/network configuration/status and not anything the SDK has any control over.  If you have evidence that the SDK is misbehaving somehow then we can take a look, otherwise it's in your hands.
