### ISSUE TITLE
Can't compile on Ubuntu (libcrypto-config.cmake is missing)

### ISSUE THREAD

**Issue by dbmoderro** [aws/aws-iot-device-sdk-cpp-v2#69]
Hi. I'm trying to build the v2 version with the commands provided in the README files:

```
git clone --branch v0.5.3 https://github.com/awslabs/aws-crt-cpp.git
git clone https://github.com/awslabs/aws-iot-device-sdk-cpp-v2.git

rm -rf aws-crt-cpp-build
mkdir aws-crt-cpp-build
cd aws-crt-cpp-build

cmake -DCMAKE_INSTALL_PREFIX="/usr" -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON ../aws-crt-cpp
cmake --build . --target install
cd ..

rm -rf aws-iot-device-sdk-cpp-v2-build
mkdir aws-iot-device-sdk-cpp-v2-build
cd aws-iot-device-sdk-cpp-v2-build

cmake -DCMAKE_INSTALL_PREFIX="/usr" -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install
```

It fails with the following error:

> 
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
>   By not providing "FindLibCrypto.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "LibCrypto", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "LibCrypto" with
>   any of the following names:
> 
>     LibCryptoConfig.cmake
>     libcrypto-config.cmake
> 
>   Add the installation prefix of "LibCrypto" to CMAKE_PREFIX_PATH or set
>   "LibCrypto_DIR" to a directory containing one of the above files.  If
>   "LibCrypto" provides a separate development package or SDK, be sure it has
>   been installed.
> Call Stack (most recent call first):
>   /usr/lib/x86_64-linux-gnu/s2n/cmake/s2n-config.cmake:8 (find_dependency)
>   /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
>   /usr/lib/x86_64-linux-gnu/aws-c-io/cmake/aws-c-io-config.cmake:4 (find_dependency)
>   /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
>   /usr/lib/x86_64-linux-gnu/aws-c-http/cmake/aws-c-http-config.cmake:3 (find_dependency)
>   /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package)
>   /usr/lib/aws-crt-cpp/cmake/aws-crt-cpp-config.cmake:3 (find_dependency)
>   CMakeLists.txt:93 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/rob/src/aws-v2/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeOutput.log".
> See also "/home/rob/src/aws-v2/aws-iot-device-sdk-cpp-v2-build/CMakeFiles/CMakeError.log".
> 

My system is Ubuntu 18.04. libssl-dev (version 1.1.1-1ubuntu2.1~18.04.4) is installed. http://packages.ubuntu.com cannot find any package with LibCryptoConfig.cmake or libcrypto-config.cmake inside.

Am I missing something?

**Comment by JonathanHenson** [comment]
Did you build your own openssl compatible libcrypto (openssl, boringssl, libressl)? If so where did you install it?

If not, have you installed the header files from apt?

**Comment by dbmoderro** [comment]
@JonathanHenson I didn't build openssl or libcrypto. Could you please point me out which header files need to be installed? libssl-dev 1.1.1 is already installed.

**Comment by bretambrose** [comment]
You need to set CMAKE_PREFIX_PATH to where the crt's artifacts were installed (/usr here).

**Comment by dbmoderro** [comment]
@bretambrose Thanks! This helped much. However, now I see another error :)

```
/home/rob/src/aws-v2/aws-iot-device-sdk-cpp-v2/discovery/source/DiscoveryClient.cpp:155:53: error: ‘aws_http_header_block’ has not been declared
                         [](Crt::Http::HttpStream &, aws_http_header_block, const Crt::Http::HttpHeader *, std::size_t) {
                                                     ^~~~~~~~~~~~~~~~~~~~~
```

I cannot find the declaration of `aws_http_header_block` anywhere.

**Comment by bretambrose** [comment]
That's a fairly recent addition to the http API.  I would guess either
  (1) You have a too-old snapshot of aws-cpp-crt or
  (2) Our versioning links between the v2 SDK and the CRT are out of sync.

Looking at your original steps, I would try getting the v0.5.4 of the cpp-crt.  I think our README is still listing v0.5.3 which is where the confusion got introduced.

**Comment by dbmoderro** [comment]
@bretambrose Thanks! I've tried v0.5.4. Still no luck though. New errors appeared: 

> 
> HEAD is now at eefe2a6 Fixed mixed shared/static build closures. (#22)
> [ 42%] No patch step for 'AwsCCompression'
> [ 43%] No update step for 'AwsCCompression'
> [ 45%] Performing configure step for 'AwsCCompression'
> -- The C compiler identification is GNU 7.4.0
> -- Check for working C compiler: /usr/lib/ccache/cc
> -- Check for working C compiler: /usr/lib/ccache/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stdbool.h
> -- Looking for stdbool.h - found
> -- Performing Test HAS_WGNU
> -- Performing Test HAS_WGNU - Failed
> -- Performing Test HAVE_SYSCONF
> -- Performing Test HAVE_SYSCONF - Success
> -- Performing Test HAS_SANITIZERS
> -- Performing Test HAS_SANITIZERS - Failed
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Found Threads: TRUE  
> CMake Error at /tmp/xxx/B/lib/aws-c-common/cmake/aws-c-common-config.cmake:7 (include):
>   include could not find load file:
> 
>     /tmp/xxx/B/lib/aws-c-common/cmake/static/aws-c-common-targets.cmake
> Call Stack (most recent call first):
>   CMakeLists.txt:74 (find_package)

It tries to include the `.../static/...` cmake file while the build type is shared.

**Comment by bretambrose** [comment]
Can you list the current set of steps you are executing (from a fresh install)?

**Comment by JonathanHenson** [comment]
Sorry cmake caching is hopelessly broken.... can you wiipe out the old build and try again? I think it’s in deps_build in your build directory.

**Comment by dbmoderro** [comment]
@bretambrose @JonathanHenson I do a clean build inside a temporary empty directory with the following commands:

```
git clone --branch v0.5.4 https://github.com/awslabs/aws-crt-cpp.git
git clone https://github.com/awslabs/aws-iot-device-sdk-cpp-v2.git

# installation directory
B="$PWD/B"

mkdir aws-crt-cpp-build
cd aws-crt-cpp-build

cmake -DCMAKE_INSTALL_PREFIX="$B" -DCMAKE_PREFIX_PATH="$B" -DBUILD_SHARED_LIBS=ON -DBUILD_DEPS=ON ../aws-crt-cpp
cmake --build . --target install
cd ..

mkdir aws-iot-device-sdk-cpp-v2-build
cd aws-iot-device-sdk-cpp-v2-build

cmake -DCMAKE_INSTALL_PREFIX="$B" -DCMAKE_PREFIX_PATH="$B" -DBUILD_SHARED_LIBS=ON ../aws-iot-device-sdk-cpp-v2
cmake --build . --target install
```

Still no luck, it fails with the error mentioned above:

>  include could not find load file:
>
>    /tmp/xxx/B/lib/aws-c-common/cmake/static/aws-c-common-targets.cmake

**Comment by bretambrose** [comment]
Sorry, it's v0.5.5 you'll want.  It fixed a static/dynamic library mismatch with compression.

**Comment by dbmoderro** [comment]
@bretambrose Thanks! 0.5.5 did the job. I guess it would be great to update the README file.

Are there any examples how to use `aws-crt-cpp` or `aws-iot-device-sdk-cpp-v2` to publish an MQTT message in C++ in particular. I'm trying to compile the following code:

```
    Io::EventLoopGroup eventLoopGroup(2);
    Io::DefaultHostResolver defaultHostResolver(eventLoopGroup, 1, 5);
    Io::ClientBootstrap bootstrap(eventLoopGroup, defaultHostResolver);

    MqttClientConnectionConfig config =
            MqttClientConnectionConfigBuilder("", "")
            .WithEndpoint("")
            .WithPortOverride(1)
            .WithCertificateAuthority("")
            .Build();
```

I link against `-laws-crt-cpp`, however it says

>/usr/bin/ld: main.o: undefined reference to symbol 'aws_mem_release'
>//opt/aws-v2/lib/libaws-c-common.so.0unstable: error adding symbols: DSO missing from command line

**Comment by bretambrose** [comment]
Basic pub/sub to an mqtt server can be seen in the CRT samples:

https://github.com/awslabs/aws-crt-cpp/blob/master/samples/mqtt_pub_sub/main.cpp

The Iot SDK is an additional layer on top of the CRT for AWS Iot specific services like Jobs, Shadows, Greengrass, etc...

**Comment by JonathanHenson** [comment]
Hmmm.... cmake should be handling that for you... it’s not intentional. We need to get to the bottom of that and fix it.

**Comment by bretambrose** [comment]
One last question: are you using cmake and find-package (on the aws crt) when building your own executable or are you building in a different manner?  Like Jonathan said, if you use cmake idiomatically (if such a thing could be said to exist) the linking setup should only require the crt and not the tree of aws-c-* dependencies underneath it.

**Comment by dbmoderro** [comment]
@bretambrose I use qmake with Qt. Hence no cmake features :) . It would be great to have a note about that in the README. E.g. how to link against `aws-crt` in cmake-based projects, and how to link w/o using cmake. Thanks anyways.

**Comment by JonathanHenson** [comment]
Ah.... that makes sense, we didn’t realize you weren’t using cmake all the way up. We can add a sample link line to the readme if that would help:

**Comment by glaubitz** [comment]
> You need to set CMAKE_PREFIX_PATH to where the crt's artifacts were installed (/usr here).

The main problem is that almost all AWS packages use non-standard CMake paths. In openSUSE/SLE, I always have to patch all CMakeLists.txt of every AWS package we ship.

The correct folder for the cmake files is ```$LIBDIR/cmake/$PACKAGE```, not ```${LIBRARY_DIRECTORY}/${PROJECT_NAME}/cmake/```.

When you use proper cmake paths, you can also this part in each ```CMakeLists.txt```:

```
# This is required in order to append /lib/cmake to each element in CMAKE_PREFIX_PATH
set(AWS_MODULE_DIR "/${CMAKE_INSTALL_LIBDIR}/cmake")
string(REPLACE ";" "${AWS_MODULE_DIR};" AWS_MODULE_PATH "${CMAKE_PREFIX_PATH}${AWS_MODULE_DIR}")
# Append that generated list to the module search path
list(APPEND CMAKE_MODULE_PATH ${AWS_MODULE_PATH})
```
