### ISSUE TITLE
CommandLineUtils causes MqttClient to be instantiated due to m_internal_client

### ISSUE THREAD

**Issue by sparrowt** [aws/aws-iot-device-sdk-cpp-v2#725]
### Describe the bug

While running `samples/pub_sub/basic_pub_sub` I noticed that [very early on](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/eaea86362123ba6762d1e9fad58cd232f8805655/samples/pub_sub/basic_pub_sub/main.cpp#L35) when it calls `Utils::parseSampleInputPubSub(...)` -> `CommandLineUtils()` is causing an `MqttClient` to be created which causes the default event loop group to be made resulting in 8 new `AwsEventLoop` threads:
![image](https://github.com/aws/aws-iot-device-sdk-cpp-v2/assets/793763/61d3f277-0858-448a-bee5-2b6eeb0a1af6)

This all seems a bit unnecessary just in order to parse the command line args?

I wonder if this is caused by `m_internal_client` [here in CommandLineUtils.h](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/bd27a4d56240066048701f3ef4ee16b8928adf18/samples/utils/CommandLineUtils.h#L197).

I'm not sure what that is for and [searching for it](https://github.com/search?q=repo%3Aaws%2Faws-iot-device-sdk-cpp-v2%20m_internal_client&type=code) shows no usages, just the single header occurrence.

Commenting out that line and rebuilding resolves the issue - the event loop threads aren't created until later on when `Aws::Iot::MqttClient()` is [explicitly created](https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/eaea86362123ba6762d1e9fad58cd232f8805655/samples/pub_sub/basic_pub_sub/main.cpp#L69).

Is `m_internal_client` meant to be there?

### Expected Behavior

No MqttClient or event loop created until explicitly requested.

### Current Behavior

MqttClient & event loop threads created during CommandLineUtils construction.

### Reproduction Steps

Build & run `samples/pub_sub/basic_pub_sub`

### Possible Solution

Remove `m_internal_client` assuming it is indeed unused?

### SDK version used

39e497d

### Environment details (OS name and version, etc.)

Windows 11 23H2 (unlikely to be relevant)

**Comment by jmklix** [comment]
Thanks for pointing this out. This might have been used in the samples at some point, but it looks unused as of now. Testing before merging this PR: https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/726
