### ISSUE TITLE
Using this library alongside aws-cpp-sdk-iot

### ISSUE THREAD

**Issue by jeffledin** [aws/aws-iot-device-sdk-cpp-v2#75]
I'd like to be able to self-provision a device with IoT Core using the [aws-cpp-sdk-iot](https://github.com/aws/aws-sdk-cpp/tree/master/aws-cpp-sdk-iot) library (with the help of the register-thing API). However, it appears that aws-cpp-sdk-iot uses different AWS library versions than aws-iot-device-sdk-cpp-v2.

I can build the two separate libraries without any trouble. When it comes to linking them in my own application, it looks like havoc ensues as there are duplicate libraries with different versions shared among the two.

Is there a recommended path forward for using these two IoT libraries from the same device without linker issues?

**Comment by JonathanHenson** [comment]
A couple questions?

What's conflicting? The only thing I can imagine is libcrypto? Is there anything else?

Also, may I ask which features are missing that would cause you to need to do this?
