### ISSUE TITLE
subscriptions broken - how to detect?

### ISSUE THREAD

**Issue by certabitmh** [aws/aws-iot-device-sdk-cpp-v2#753]
Device is connected, but it seems subscription for shadow changes or job notifications are broken.
Only debug output on device I can see are pings/responses for it.

Is there a way to check if subscriptions are broken or to get notified?

_Originally posted by @certabitmh in https://github.com/aws/aws-iot-device-sdk-cpp-v2/discussions/744#discussioncomment-10829015_

**Comment by bretambrose** [comment]
What's in the logs is what was on the wire.  If you're not getting the publishes you expect then the most likely explanation is that you're just not subscribed at all.

Do you have a log showing a successful subscription followed by a disconnect/reconnect that successfully rejoined the session?

**Comment by certabitmh** [comment]
No unfortunately no full logs but device has definitely been subscribed to topics, otherwise my state machine won't go any step further.

So is there any api I can check status of subscription with?
________________________________
Von: Bret Ambrose ***@***.***>
Gesendet: Thursday, October 3, 2024 3:55:45 PM
An: aws/aws-iot-device-sdk-cpp-v2 ***@***.***>
Cc: Markus Hammer | CertaBit Engineering ***@***.***>; Author ***@***.***>
Betreff: Re: [aws/aws-iot-device-sdk-cpp-v2] subscriptions broken - how to detect? (Issue #753)


What's in the logs is what was on the wire. If you're not getting the publishes you expect then the most likely explanation is that you're just not subscribed at all.

Do you have a log showing a successful subscription followed by a disconnect/reconnect that successfully rejoined the session?

**Comment by bretambrose** [comment]
No.

**Comment by jmklix** [comment]
> In that case I've to disconnect and reconnect to wifi using wpa tools on linux. Then device connects normally again

After disconnecting and reconnecting you can resubscribe to any topics that you were previously subscribed to. This is make sure that you are still receiving any shadow changes that you want

**Comment by certabitmh** [comment]
Sure, just wanted to point out that something gets blocked one layer below iot sdk probably.
________________________________
Von: Joseph Klix ***@***.***>
Gesendet: Thursday, October 3, 2024 11:48:07 PM
An: aws/aws-iot-device-sdk-cpp-v2 ***@***.***>
Cc: Markus Hammer | CertaBit Engineering ***@***.***>; Author ***@***.***>
Betreff: Re: [aws/aws-iot-device-sdk-cpp-v2] subscriptions broken - how to detect? (Issue #753)


In that case I've to disconnect and reconnect to wifi using wpa tools on linux. Then device connects normally again

After disconnecting and reconnecting you can resubscribe to any topics that you were previously subscribed to. This is make sure that you are still receiving any shadow changes that you want

**Comment by jmklix** [comment]
Thanks! Did you have any other questions/concerns about this sdk?
