### ISSUE TITLE
Host assembly file used when cross-compiling for aarch64

### ISSUE THREAD

**Issue by zeenix** [aws/aws-iot-device-sdk-cpp-v2#761]
### Describe the bug

While trying to cross-compile for aarch64 on an x86-64 Linux machine, it seems that wrong assembly files get copied over and compilation fails with a huge amount of errors:

```
Copying platform assembly files from /home/zeenix/checkout/jucr-io/greengrass-sdk-rs/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-lc/generated-src/linux-x86_64/crypto/ to /target/aarch64-unknown-linux-gnu/debug/build/greengrass-sdk-rs-1bdae08b7f817854/out/build/deps/AWSLC/crypto
  /home/zeenix/checkout/jucr-io/greengrass-sdk-rs/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S: Assembler messages:
  /home/zeenix/checkout/jucr-io/greengrass-sdk-rs/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-lc/crypto/hrss/asm/poly_rq_mul.S:302: Error: unknown pseudo-op: `.att_syntax'
  /home/zeenix/checkout/jucr-io/greengrass-sdk-rs/aws-iot-device-sdk-cpp-v2/crt/aws-crt-cpp/crt/aws-
...
```

The cmake command is:

```
cmake "/home/zeenix/checkout/jucr-io/greengrass-sdk-rs/aws-iot-device-sdk-cpp-v2" \
    "-DBUILD_SHARED_LIBS=OFF" \
    "-DCMAKE_CROSSCOMPILING=TRUE" \
    "-DCMAKE_SYSTEM_NAME=Linux" \
    "-DCMAKE_SYSTEM_PROCESSOR=aarch64" \
    "-DCMAKE_INSTALL_PREFIX=/target/aarch64-unknown-linux-gnu/debug/build/greengrass-sdk-rs-1bdae08b7f817854/out" \
    "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections" \
    "-DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc" \
    "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections" \
    "-DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++" \
    "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections" \
    "-DCMAKE_ASM_COMPILER=/usr/bin/aarch64-linux-gnu-gcc" \
    "-DCMAKE_BUILD_TYPE=Debug"
```

Is it possible there is some cmake variable that is needed to be set?

### Expected Behavior

The right assembly files dir is copied over and build succeeds.

### Current Behavior

Incorrect assembly files get copied and compilation fails.

### Reproduction Steps

Run the cmake command in the description above.

### Possible Solution

Document how to cross-build in the README or make the build work with the command specified in the description.

### SDK version used

1.34 (git revision: 602121d76832e302472bfbbffb77b75d107ff647)

### Environment details (OS name and version, etc.)

Fedora 40, building under Cargo cross container env (uses Ubuntu images)

**Comment by jmklix** [comment]
It looks like you are having a problem with one of the dependencies: [aws-lc](https://github.com/aws/aws-lc)
aws-lc doesn't seem to be correctly cross compiling for arm. 

Looking on through the aws-lc [build docs](https://github.com/aws/aws-lc/blob/main/BUILDING.md), they mention an additional cmake parameter that you might want to pass:

> If you want to cross-compile then there is an example toolchain file for 32-bit Intel in util/. Wipe out the build directory, run cmake like this:
> 
> cmake -B build -DCMAKE_TOOLCHAIN_FILE=../util/32-bit-toolchain.cmake -GNinja 

I would try adding that to your cmake command and see if that works. Also seeing if you can cross compile aws-lc in your environment on it's own would be helpful.

**Comment by zeenix** [comment]
@jmklix Thanks! I just treat the whole repo as one self-contained project so I didn't even think to check for a README in aws-lc lib. :)

> I would try adding that to your cmake command and see if that works.

I was about to try it but looking at the content of that .cmake file being passed, it is only setting cmake variables, just like I am in my command. So that can't work (especially since that's setting the arch to be 32-bit x86, while I'm targetting 64-bit ARM :smile:).

> Also seeing if you can cross compile aws-lc in your environment on it's own would be helpful.

I'm trying that right now. It's not trivial though since for some reason, it starts to require Go compiler if I build it standalone.

**Comment by zeenix** [comment]
> > Also seeing if you can cross compile aws-lc in your environment on it's own would be helpful.
> 
> I'm trying that right now. It's not trivial though since for some reason, it starts to require Go compiler if I build it standalone

The Go compiler was too old for this to work. I instead went for building against the system openssl and that seems to work. Thanks again for your time.

**Comment by jmklix** [comment]
Can you share how you got it working with openssl? In case someone in the future runs across this issue and is trying to do the same thing

**Comment by zeenix** [comment]
> Actually, it turns out that I only got it to build (by setting `"-DUSE_OPENSSL=ON"`) but later when I try to link my library, I get a lot of undefined symbols errors:

Seems like each time, I comment here things change immediately after. :) If I link my library against another (Rust) binary, it seems to work just fine. :shrug:
