### ISSUE TITLE
Shadow sample: AWS_ERROR_FILE_INVALID_PATH

### ISSUE THREAD

**Issue by certabitmh** [aws/aws-iot-device-sdk-cpp-v2#79]
When I try to run the shadow sample of release v1.3 on emb. linux target, I get:

> Client Configuration initialization failed with error aws-c-common: AWS_ERROR_FILE_INVALID_PATH, Invalid file path.

tried to run it with:
`./shadow-sync --endpoint MYENDPOINT.iot.eu-west-1.amazonaws.com --key "/data/private.pem" --cert "/data/certificate.pem" --thing_name "MY-SECRET-THINGNAME" --shadow_property testSDK`

Private Key and cert are definitely correct and located in provided paths, since I use the same files with SDK v1.

inserted some fprintf debug statements in main.cpp to print decoded cmd line args: both filepaths are successfully decoded in local member strings...           
https://github.com/aws/aws-iot-device-sdk-cpp-v2/blob/fbbc4411cf5eff11cf61304d8d7a33aed97353b5/samples/shadow/shadow_sync/main.cpp#L134

**Comment by JonathanHenson** [comment]
out of curiosity, what happens if you don't quote the path strings?

**Comment by graebm** [comment]
This currently happens in all the samples if the "--ca_file" option is missing. Adding that option should get you up and running.

I'm putting together a fix so that this option is not required in shadow_sync and describe_job_executions samples.

**Comment by graebm** [comment]
https://github.com/aws/aws-iot-device-sdk-cpp-v2/pull/81

**Comment by graebm** [comment]
Fix is merged. Good luck!
