### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by jlamhp** [aws/aws-iot-device-sdk-cpp-v2#9]
In certain environments, proxy support is needed to allow communication to the cloud, as even direct connections over 443 may be blocked.

There was a pull request in the v1 client that added this but it has never been merged (https://github.com/aws/aws-iot-device-sdk-cpp/pull/9).

**Comment by jlamhp** [comment]
Changed request a bit. Ideally proxy support would be made available for both MQTT and websockets, as one may be able to tunnel through the proxy over 443 for MQTT.

**Comment by JonathanHenson** [comment]
Web sockets and proxies are now fully supported. Check the samples in aws-crt-cpp/samples/mqtt-pub-sub for more info.

**Comment by kkozachuk** [comment]
Is it possible to use proxy with MTLS?

**Comment by bretambrose** [comment]
We are targeting mid April for support for mtls-based mqtt through a tunneling http proxy.

**Comment by kkozachuk** [comment]
For MTLS-http proxy, will it be SDK-only changes, or datacenters should be updated too? Does mid-April include time for datacenters update, like US-WEST-2?

**Comment by kkozachuk** [comment]
Hi @bretambrose . For MTLS-http proxy, is this commit 52627fe8bece3d7446aec661dfc072693d739c2c you were talking about?

**Comment by bretambrose** [comment]
No that is some related, preliminary work for different proxy authentication schemes and strategies.

The current "beta" branch for mqtt-through-http-proxy via mtls is here: https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/ExperimentalProxyv2

**Comment by kkozachuk** [comment]
@bretambrose Any plans on merging `ExperimentalProxyv2` branch with MTLS-http proxy? I remember the plan was on mid-April, are there any changes?

**Comment by bretambrose** [comment]
The last of the proxy updates were merged into main and released last week.

**Comment by kkozachuk** [comment]
@bretambrose Thanks, many changes are visible. I saw new function `InitClientWithMtlsSystemPath`, other MTLS functions didn't change. No proxy settings seems to be present in `TlsContextOptions` class. Is it possible to use both MTLS + proxies?

**Comment by bretambrose** [comment]
You can follow the API calls in the integration tests for the feature here:  https://github.com/awslabs/aws-crt-cpp/blob/main/tests/ProxyTest.cpp#L1028

Proxy Options Type: https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/http/HttpConnection.h#L257

Applying it to an Aws IoT mqtt connection:  https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/iot/MqttClient.h#L228

**Comment by flashliqu** [comment]
> You can follow the API calls in the integration tests for the feature here: https://github.com/awslabs/aws-crt-cpp/blob/main/tests/ProxyTest.cpp#L1028
> 
> Proxy Options Type: https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/crt/http/HttpConnection.h#L257
> 
> Applying it to an Aws IoT mqtt connection: https://github.com/awslabs/aws-crt-cpp/blob/main/include/aws/iot/MqttClient.h#L228

Hi: How do we build the ProxyTest app and how to test it? Could you help advise?
