### ISSUE TITLE
Error trying to update job status

### ISSUE THREAD

**Issue by evilone79** [aws/aws-iot-device-sdk-cpp-v2#95]
Hi, I'm trying to update job status with following code:

`
UpdateJobExecutionRequest request = {};
    request.ThingName = thingName;
    request.IncludeJobExecutionState = true;
    request.ClientToken = uuid.ToString();
    request.JobId = jobId;
    request.Status = status;

    jobs.PublishUpdateJobExecution(request,
                                   AWS_MQTT_QOS_AT_LEAST_ONCE,
                                   [&](int ioErr) {
                                       if (ioErr) {
                                           fprintf(stderr, "Error %d occurred\n", ioErr);
                                           conditionVariable.notify_one();
                                           return;
                                       }
                                   });
`

However, I get the request rejected with following:

> Value null at 'status' failed to satisfy constraint: Member must not be null

Looking at the serializer code in UpdateJobExecutionRequest.cpp, I see following:

`
if (Status)
 {
         (JobStatusMarshaller::ToString(*Status));
 }
`
Hmm.. what am I missing?

**Comment by rccarper** [comment]
What is the type of the status variable that you are assigning to request.Status?  Is it possible that it's an Aws::Crt::Optional<Aws::Iotjobs::JobStatus> that doesn't have a contained value?

**Comment by rccarper** [comment]
Hey, nevermind, this does look like there is a bug on our side--looking into a fix.

**Comment by evilone79** [comment]
What would be the rough estimation for this one to be fixed? Should we switch to the old version of SDK? Asking, since deadlines are closing..

**Comment by rccarper** [comment]
We should have a fix in within a day or two.

**Comment by rccarper** [comment]
I merged a fix into master earlier today and we should be able to cut a new release sometime tomorrow.  Once that happens, or if something unexpectedly changes, I'll update this thread.

**Comment by evilone79** [comment]
Thanks a lot for effort!

**Comment by rccarper** [comment]
Not a problem!  We just made a new release (v1.5.3) that has the fix.  I'll go ahead and close this issue, but please feel free to re-open if you encounter a problem.
