### ISSUE TITLE
AWS_ERROR_SYS_CALL_FAILURE when connecting with proxy

### ISSUE THREAD

**Issue by elad-ep** [aws/aws-iot-device-sdk-cpp-v2#99]
Hi, I'm configuring http proxy connection using HttpClientConnectionProxyOptions, similar to the pub sub sample. in order to test it I installed Squid proxy on my Windows 10 machine. I haven't changed the default settings of Squid (i.e. it listens on port 3128 on localhost). 

[I have tested that the proxy is up and functioning by defining the proxy in the Windows system proxy settings and verifying that browsers traffic goes successfully via the proxy.]

I've configured HttpClientConnectionProxyOptions with proxyHost "127.0.0.1" and port 3128. However, when I call MqttConnection.Connect the connect callback function is invoked with error code AWS_ERROR_SYS_CALL_FAILURE. by debugging the source code I can see that the error is returned from s_increment_read_window() line 1335 (in secure_channel_tls_handler.c. QueryContextAttributes returns SEC_E_INVALID_HANDLE). However, I'm not sure what is the root cause of the issue.

Please note that without configuring proxy in HttpClientConnectionProxyOptions the connection is successful.

can you please advise? thanks

**Comment by JonathanHenson** [comment]
Just a guess, have you set the root ca of you’re proxy config to the proxy’s ca?

**Comment by elad-ep** [comment]
the proxy is http proxy. I haven't set up any ca for the proxy.
in the MqttClientConnectionConfigBuilder I do use builder.WithCertificateAuthority() with a cacert file. is that what you mean?

**Comment by JonathanHenson** [comment]
You’re intentionally using plain text over the proxy? If so you need to give it a null tlsconnection options.

If not, you need a ca.

**Comment by JonathanHenson** [comment]
“ in the MqttClientConnectionConfigBuilder I do use builder.WithCertificateAuthority() with a cacert file. is that what you mean?”

I just realized we’re talking about two separate things. I’ll get the info for you shortly

**Comment by elad-ep** [comment]
I've now also tested with Fiddler as a local proxy. again a connection failure when using websockets over proxy, but now the connection callback is invoked with error AWS_ERROR_UNKNOWN. with what proxy the pub sub sample was tested with? any special configuration for the proxy?

I have switched from aws IoT sdk v1 to v2 because of the proxy support in v2, but I don't manage to get it working...

**Comment by JonathanHenson** [comment]
It's entirely possible, we have a bug. We do test with fidler in our CI though. Any chance we could get log output? That would help us narrow what's going on more quickly.

**Comment by elad-ep** [comment]
Attached is the log file in trace level (fiddler local proxy on port 8888).
[sdkv2.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4291651/sdkv2.txt)

Is there any special configuration for the local proxy or on the AWS cloud side that should be performed?

**Comment by JonathanHenson** [comment]
Looks like fidler is sending a 200 to the connect request with a connection: close header. This is the root of the problem.

**Comment by JonathanHenson** [comment]
Is your fidler properly configured as a TLS proxy?

**Comment by elad-ep** [comment]
I haven't done any special configuration in fiddler. by default fiddler configuration listens as a local proxy on port 8888 as shown here:
![fiddler](https://user-images.githubusercontent.com/61790753/75964638-385c4100-5ed0-11ea-8a0f-7f04da4d84fd.png)

browsers and CURL manage to go though fiddler on port 8888 successfully.

**Comment by elad-ep** [comment]
from the describe here it looks like this is the default flow:
https://stackoverflow.com/questions/22875092/why-fiddler-adds-connectionclose-on-connect-response

**Comment by JonathanHenson** [comment]
Okay, those answers are all wrong. But it doesn’t matter, we need bug for bug compatibility with the existing infrastructure out in the wild. I’ll go fix it in aws-c-http. In the meantime using a “doesnt do insane spec breaking behavior” proxy like burp will work, or if you can find a way to disable that in fiddler it should work. You can write your code and test against that while we’re updating our http implementation.

**Comment by elad-ep** [comment]
Hmm... I didn't understand - so you managed to figure out the root cause of the issue from the logs I sent? (we have customers that are waiting on this functionality since they use our product behind organization proxy)

**Comment by JonathanHenson** [comment]
That’s why we wrote the logger, it basically traces the entire system. 

Root cause is aws-c-http (GitHub.com/awslabs/aws-c-http and our http implementation) is strict regarding the rfc in connection close. When the proxy sends a connection close header after the CONNECT call we shut down the connection while we’re simultaneously trying to negotiate TLS with the remote endpoint. The “fix” is for us to ignore that header in this case. That’s incorrect behavior but.... that’s internet infrastructure for ya.

**Comment by JonathanHenson** [comment]
That said, it PROBABLY works on your organization’s proxy as is. We’ve tested this against multiple proxies fine. It seems fidler or its default config is the first we’ve encountered with this behavior.

**Comment by elad-ep** [comment]
I tried with both squid and fiddler and didn't manage to get it working. do you have ETA when the code patch will be ready so I can test it in my environment? thanks...

**Comment by JonathanHenson** [comment]
What was the problem with squid? Same exact behavior or slightly different. I ask because there's another really rough edge with MITM TLS proxies, and that's they have to vend their own CA to decrypt the traffic. The sdk will fail during tls negotiation because it doesn't trust that CA (correct behavior). This is the most common issue folks have run in to in the past.

**Comment by JonathanHenson** [comment]
code patch will not take long.

**Comment by elad-ep** [comment]
Those are trace logs when trying to connect with squid:
[squid.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4294444/squid.txt)

(For both squid and fiddler proxy certificate is not required)

**Comment by JonathanHenson** [comment]
Interesting, this is where that's failing:
```
        SECURITY_STATUS status =
            QueryContextAttributes(&sc_handler->sec_handle, SECPKG_ATTR_STREAM_SIZES, &sc_handler->stream_sizes);

        if (status != SEC_E_OK) {
            aws_raise_error(AWS_ERROR_SYS_CALL_FAILURE);
            aws_channel_shutdown(slot->channel, AWS_ERROR_SYS_CALL_FAILURE);
            return AWS_OP_ERR;
        }
```

What version of windows is this?

**Comment by JonathanHenson** [comment]
oh, here's the key:

from the docs:

> SEC_E_INVALID_HANDLE0x80100003 | The function failed. The phContext parameter specifies a handle to an incomplete context.

From the log:

[TRACE] [2020-03-05T18:22:04Z] [000049a8] [tls-handler] - id=000001FD5C30BF80: Increment read window message received 39

something is kicking this off prematurely, and when we go to query the sizes, and the negotiation isn't complete, windows can't give it to us, because the cipher negotiation is incomplete




> 

SEC_E_INVALID_HANDLE0x80100003 | The function failed. The phContext parameter specifies a handle to an incomplete context.
-- | --



SEC_E_INVALID_HANDLE0x80100003 | The function failed. The phContext parameter specifies a handle to an incomplete context.
-- | --

**Comment by JonathanHenson** [comment]
> [TRACE] [2020-03-05T18:22:01Z] [000049a8] [http-connection] - id=000001FD5C3EF940: Begin processing message of size 39.

Okay so http connection receives 39 bytes, (this is the CONNECT response). it then kicks off a window update (but asynchronously). That window update, would normally be fine, except for on windows where it doesn't like you querying the handle before negotiation completes.

This is where the SYS_CALL_FAILURE comes in. The fiddler proxy issue is a different problem.

**Comment by elad-ep** [comment]
ok, thanks. the OS is windows 10 version 1909. please post here when you create the PR, I'll take the code patch, compile it locally and test... (if you could fix the QueryContextAttributes issue first it would be great)

**Comment by JonathanHenson** [comment]
https://github.com/awslabs/aws-c-io/pull/247

**Comment by JonathanHenson** [comment]
you should just be able to check out that branch in the submodule and rebuild

**Comment by JonathanHenson** [comment]
sorry for the build breakage, i don't have a windows box on hand at the moment. I'll let you know when that build passes.

**Comment by JonathanHenson** [comment]
okay, build passed, sorry about that, should be good to try now.

**Comment by elad-ep** [comment]
now getting in the connect callback: "aws-c-io: AWS_IO_READ_WOULD_BLOCK, Read operation would block, try again later"
logs (tested with squid):
[readblock.txt](https://github.com/aws/aws-iot-device-sdk-cpp-v2/files/4294950/readblock.txt)

**Comment by JonathanHenson** [comment]
looks like we made it through tls negotiation fine. looking into why the encrypt call is failing.

**Comment by JonathanHenson** [comment]
I think I found it, it was a simple oversight with the latest update. Let me test real quick.

**Comment by JonathanHenson** [comment]
@elad-ep I fixed the squid issue I think. Feel free to give it another go.

**Comment by JonathanHenson** [comment]
also, I tested on windows on my side, seems to work correctly now.

**Comment by elad-ep** [comment]
I tested now and it works fine! thanks!!!

**Comment by elad-ep** [comment]
could you also please fix the Fiddler issue and I will test, since there might other production proxies with similar behavior as Fiddler...

**Comment by JonathanHenson** [comment]
https://github.com/awslabs/aws-c-http/pull/198

**Comment by elad-ep** [comment]
thanks! I have a question regarding multiple proxies - the SDK currently gets one proxy host and port when connecting. is there any intention supporting multiple proxies, such as in a PAC file: "PROXY aaa;PROXY bbb;DIRECT"? so if proxy is unavailable the SDK will continue to the second proxy, or directly without a proxy as specified...?

**Comment by JonathanHenson** [comment]
hmmmm. seems like it may be more reasonable to handle this on the user side of things. Loop over different mqtt websocket/proxy configs until one finally connects?

**Comment by elad-ep** [comment]
I see - this will require explicit re-connections, i.e. whenever the "onInterrupted" callback is called, I will need to check whether the current proxy is still available. if not, I will need to disconnect from IoT, and create a new connection to another proxy/directly.

btw, I find the error codes in SDK v2 much less friendly than in v1. in v1, there was an enum with descriptive error codes so I can understand what error occurred. in v2, the error codes are just int number. I cannot know what the int number means - this is not exposed in the header files.
so for example, when "onInterrupted" callback is called I want to act differently depends on the error code but all I got is int number without descriptive meaning...

**Comment by bretambrose** [comment]
A final followup here: the error codes are actually exposed in headers, but they're headers in the dependent libraries (aws-c-*)  So for example, https://github.com/awslabs/aws-c-mqtt/blob/master/include/aws/mqtt/mqtt.h#L36  https://github.com/awslabs/aws-c-http/blob/master/include/aws/http/http.h#L15 etc...)

**Comment by nellaibas** [comment]
I am having the same issue while trying the python sdk in an enterprise proxy (without any authentication). None of the samples work. I have tried basic, proxy, websocket etc...
